### ISSUE TITLE
Failed to install vcluster using clusterctl in openshift

### ISSUE THREAD

**Issue by flacatus** [loft-sh/vcluster#1013]
### What happened?

I tried to install vcluster in openshift cluster using clusterctl command.  I see in the vcluster manager error with helm charts:

```
Error: looks like "https://charts.loft.sh" is not a valid chart repository or cannot be reached: open /.cache/helm/repository/QpP5xSLtrBxrnrYLmxCVtJwTanQ=-index.yaml: no such file or directory
```

Vcluster CR:

```
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: VCluster
metadata:
  name: vcluster
  namespace: virtual-providers
  finalizers:
    - vcluster.loft.sh/cleanup
  labels:
    cluster.x-k8s.io/cluster-name: vcluster
spec:
  controlPlaneEndpoint:
    host: ''
    port: 0
  helmRelease:
    chart: {}
    values: |
      openshift:
        enable: true
      sync:
        networkpolicies:
          enabled: true
        serviceaccounts:
          enabled: true
        services:
          syncServiceSelector: true
```

### What did you expect to happen?

Get a new vcluster

### How can we reproduce it (as minimally and precisely as possible)?

Install vcluster throw openshift using cluster api controllers

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```

</details>
