### ISSUE TITLE
Generic sync export labelSelector has different meaning

### ISSUE THREAD

**Issue by mrysavy** [loft-sh/vcluster#1018]
### What happened?

I'm using vcluster v0.15 and I'm trying to synchronize specific secrets from vcluster to host cluster. I tried to use labelSelector:

```
          generic:
            config: |
              version: v1beta1
              export:
                - apiVersion: v1
                  kind: Secret
                  selector:
                    labelSelector:
                      k8s.trask.cz/synced-secret: "true"
```

Result is that secrets without this label or secrets with this label and value other than "true" are synchronized, but secrets with exactly this label are kept unsynchronized.

### What did you expect to happen?

I expect that secrets with label corresponding to labelSelector are synced and the others not

### How can we reproduce it (as minimally and precisely as possible)?

I have created VCluster with above configuration and try create some secrets in vcluster with different conditions

* without label - it shouldn't be synchronized but it is
* with same label key but different value - it shouldn't be synchronized but it is
* with exactly same label and key (as in labelSelector) - it should be synchronized but it is not

### Anything else we need to know?

I've looked at the source code and I think that the problem is in negation in this condition - [https://github.com/loft-sh/vcluster/blob/917dbaeb53fabb39659bb5eee434625eeaca3558/pkg/controllers/generic/export_syncer.go#L285-L286](https://github.com/loft-sh/vcluster/blob/917dbaeb53fabb39659bb5eee434625eeaca3558/pkg/controllers/generic/export_syncer.go#L285-L286) - with

### Host cluster Kubernetes version

<details>

```
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3+k3s1", GitCommit:"01ea3ff27be0b04f945179171cec5a8e11a14f7b", GitTreeState:"clean", BuildDate:"2023-03-27T22:23:17Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
k3s
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
vcluster version 0.15.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu
Arch: x86_64
```

</details>
