### ISSUE TITLE
Rewriting secrets in the azureFile volume

### ISSUE THREAD

**Issue by ipopovic5** [loft-sh/vcluster#103]
I'm having an issue with the applications deployed in vCluster, whose secret is defined in k8s inline mount. When trying to deploy the application, the secret is looked up in the wrong path.

Example of application deployment:
Host cluster -> vcluster (namespace) -> application (namespace) -> secret

Instead of looking for the secret in the application namespace (inside vCluster), the deployment looks it up in the vcluster/secret namespace. I would expect deployment to search the secret in vCluster's namespace, where the mount and resource are defined.

Here is the k8s resource for the inline mount sample:

```
...
    volumeMounts:
    - mountPath: /some/path/file
    name: secret
volumes:
- azureFile:
    secretName: secret-name
    shareName: sharexyz
    name: secret
...
```

Would it be possible to have vCluster rewriting the secrets in the azureFile volume?
