### ISSUE TITLE
vcluster overrides certain environment variables 

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#1031]
### What happened?

When a user-defined Pod env var matches "$SERVICENAME_PORT" pattern, where $SERVICENAME is a name of a Service that exists in the same namespace, the value set by the user is overridden with `$PROTOCOL://$HOST:$PORT`.

### What did you expect to happen?

The env var explicitly set by the user should take precedence and should not be overridden by the vcluster.

### How can we reproduce it (as minimally and precisely as possible)?

Create this two manifests in vcluster one by one:
```
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: test
spec:
  selector:
    app: testy-woo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
```
```
apiVersion: v1
data:
  LOG_LEVEL: INFO
  REDIS_HOST: redis
  REDIS_PORT: "6379"
kind: ConfigMap
metadata:
  labels:
    pipekit.io/service: testy-woo
  name: testy-woo
  namespace: test
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: testy-woo
  namespace: test
  labels:
    app: testy-woo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testy-woo
  template:
    metadata:
      labels:
        app: testy-woo
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: testy-woo
          name: testy-woo
          image: nginx:stable
```
Wait for the nginx pod to start and run:
```
kubectl exec -n test deployments/testy-woo -- env | grep REDIS_PORT=
```
You should see something like `REDIS_PORT=tcp://10.96.115.242:80`, but instead it should be `REDIS_PORT=6379`.

### Host cluster Kubernetes version

<details>
N/A
</details>

### Host cluster Kubernetes distribution

<details>
N/A
</details>

### vlcuster version

<details>
v0.15.0
</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>
N/A
</details>

### OS and Arch

<details>
N/A
</details>

**Comment by FabianKramm** [comment]
This is rather difficult to fix as it seems that `.env` is taking precedence over `.envFrom` and since we are adding the service discovery environment variables via `.env` it automatically overrides the ones from `.envFrom`. To solve the problem we would need to either find out in the beginning what environment variables are present in the config map / secret (which could change, so wouldn't be 100% reliable) or we omit the service discovery environment variables completely (which potentially breaks stuff that relies on this, how important are those though?). So I'm not sure what the way forward here would be for now.

**Comment by luis-mfc** [comment]
For anyone struggling with this, here are the helm values (chart version 0.30.0) required to [disable the service environment variables](https://kubernetes.io/docs/tutorials/services/connect-applications-service/#accessing-the-service) in case like me you do not need them:
```yaml
controlPlane:
  distro:
    k8s:
      enabled: true
      image:
        tag: "v1.34.1"
      apiServer:
        extraArgs:
          - --runtime-config=admissionregistration.k8s.io/v1beta1=true
          - --feature-gates=MutatingAdmissionPolicy=true

experimental:
  deploy:
    vcluster:
      manifests: |
        ---
        apiVersion: admissionregistration.k8s.io/v1beta1
        kind: MutatingAdmissionPolicy
        metadata:
          name: "disable-service-links"
        spec:
          matchConstraints:
            resourceRules:
              - apiGroups: ["apps"]
                apiVersions: ["v1"]
                operations: ["CREATE", "UPDATE"]
                resources:
                  - deployments
                  - statefulsets
                  - daemonsets
          failurePolicy: Fail
          reinvocationPolicy: IfNeeded
          mutations:
            - patchType: "JSONPatch"
              jsonPatch:
                expression: >
                  [
                    JSONPatch{
                      op: "add",
                      path: "/spec/template/spec/enableServiceLinks",
                      value: false
                    }
                  ]
        ---
        apiVersion: admissionregistration.k8s.io/v1beta1
        kind: MutatingAdmissionPolicyBinding
        metadata:
          name: disable-service-links-binding
        spec:
          policyName: disable-service-links
          matchResources:
```
