### ISSUE TITLE
Global annotations aren't global

### ISSUE THREAD

**Issue by tico24** [loft-sh/vcluster#1071]
### What happened?

Add a basic global annotation to the helm chart:

```
globalAnnotations:
  foo: "bar"
```

The annotations are only applied to a role, rolebinding and service.. so much less global than advertised.

Also it applies with too many indentations:

```
apiVersion: v1
kind: Service
metadata:
  name: vc
  namespace: ci
  labels:
    app: vcluster
    chart: "vcluster-k0s-0.15.0"
    release: "vc"
    heritage: "Helm"
  annotations:
      foo: bar
```

### What did you expect to happen?

Something marked as `global` should apply globally.

Annotations should be correctly indented

### How can we reproduce it (as minimally and precisely as possible)?

Set the above in your values.yaml and run`helm template ... > out.yaml ` to see the resulting manifest.

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

n/a - this is a helm issue

### Host cluster Kubernetes distribution

n/a - this is a helm issue

### vlcuster version

<details>

```
0.15.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

k0s

### OS and Arch

n/a - this is a helm issue
