### ISSUE TITLE
No semverCompare support with init.helm[].chart.version

### ISSUE THREAD

**Issue by daaang** [loft-sh/vcluster#1096]
### What happened?

Usually, when I install helm charts, I set the version to something like `^1` so that it pulls whatever the latest v1 release is. Obviously, vcluster is itself under no obligation to support the syntax, but the experience of figuring out what I'd done wrong was not smooth, so I figured I should share.

Here are the helm chart values I used:

```
init:
  helm:
  - chart:
      name: "argo-cd"
      repo: "https://argoproj.github.io/argo-helm"
      version: "~5.9"
    release:
      name: "argocd"
      namespace: "argocd"
```

Every few minutes, the syncer would try to run helm install, always with these log messages:

```
helm pull argo-cd argo-cd --repo https://argoproj.github.io/argo-helm --version ~5.9
successfully pulled chart argo-cd
initiating installation for release argocd/argocd
 error installing release argocd/argocd
Reconciler error couldn't find chart
```

Eventually, I grepped the source code for that last error line and worked out what was going wrong: [https://github.com/loft-sh/vcluster/blob/main/pkg/controllers/manifests/init.go#L378](https://github.com/loft-sh/vcluster/blob/main/pkg/controllers/manifests/init.go#L378)

It was downloading `./argo-cd-5.9.1.tgz` just fine but then it failed because it couldn't find `./argo-cd-~5.9.tgz`.

The workaround:

```
-      version: "~5.9"
+      version: "5.9.1"
```

### What did you expect to happen?

Any of the following:

1. The syncer could convert a semverCompare string to an explicit version before pulling the chart and installing.
2. The documentation could call out that the `init.helm[].chart.version` value must be an explicit version, not something like `>= 1.2.3 < 2.0.0`.
3. The syncer could detect that a version string is unsupported, and something like `expected explicit chart version, got unsupported version "^1"` in the logs instead of `couldn't find helm chart`.

### How can we reproduce it (as minimally and precisely as possible)?

Create a vcluster with an implicit patch version, like the one above:

```
init:
  helm:
  - chart:
      name: "argo-cd"
      repo: "https://argoproj.github.io/argo-helm"
      version: "~5.9"
    release:
      name: "argocd"
      namespace: "argocd"
```

It won't install, but if you try again with `version: "5.9.1"`, it will.

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.14", GitCommit:"0018fa8af8ffaff22f36d3bd86289753ca61da81", GitTreeState:"clean", BuildDate:"2023-05-17T16:21:16Z", GoVer
sion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
kubeadm
```

</details>

### vlcuster version

<details>

```
loftsh/vcluster:0.14.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: Debian GNU/Linux 11 (bullseye)
Arch: amd64
```

</details>
