### ISSUE TITLE
Proxy metrics API Service not created

### ISSUE THREAD

**Issue by ttreptow** [loft-sh/vcluster#1128]
### What happened?

I enabled the metricsServer proxy, but no APIService is created in the vcluster. The syncer logs show:

> E0731 17:09:43.878472       1 register.go:97] error creating api service the cache is not started, can not read objects                                                                                            
> E0731 17:09:43.878591       1 start.go:381] Error registering metrics apiservice: the cache is not started, can not read objects

It's entirely possible that this is due to something odd in my environment- it's weird that it straight up doesn't work at all. 

Config:

```yaml
sync:
  serviceaccounts:
    enabled: true
  poddisruptionbudgets:
    enabled: true
  nodes:
    enabled: true

storage:
  persistence: true
  size: 10Gi

proxy:
  metricsServer:
    nodes:
      enabled: true
    pods:
      enabled: true
```

### What did you expect to happen?

APIService created in vcluster

### How can we reproduce it (as minimally and precisely as possible)?

I'm not sure if any of my other settings are affecting the metricsServer proxy deployment (see my config above). 

### Host cluster Kubernetes version

<details>

```console
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9+rke2r1", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T19:05:26Z", GoVersion:"go1.19.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
RKE2
```

</details>

### vlcuster version

<details>

```
vcluster version 0.15.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu
Arch: x86_64
```
</details>
