### ISSUE TITLE
Using rewriteLabelKey or rewriteLabelExpressionSelector cause syncer pod crash

### ISSUE THREAD

**Issue by ttreptow** [loft-sh/vcluster#1129]
### What happened?

When using generic sync patches with `op: rewriteLabelKey` or `op: rewriteLabelExpressionSelector`, the syncer pod crash loops with the error:

> F0731 20:19:12.914177       1 main.go:35] start controllers: parsing the config: invalid exports[0].patches[1]: unsupported patch type rewriteLabelExpressionsSelector     

(similar error for rewriteLabelKey)

This seems to be due to the validation function not having cases for those operators: https://github.com/loft-sh/vcluster/blob/00e118f8019c35000aff402b18d14da732f70a86/pkg/config/parse.go#L134

### What did you expect to happen?

The rewriteLabelKey and rewriteLabelExpressionSelector operations are not reported as invalid opeerations

### How can we reproduce it (as minimally and precisely as possible)?

Create a vcluster with the example generic ServiceMonitor syncer from the [documentation](https://www.vcluster.com/docs/architecture/synced-resources#sync-other-resources).

```yaml
sync:
  generic:
    config: |-
      version: v1beta1
      export:
        - apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          patches:
            - op: add
              path: .metadata.labels
              value:
                prometheus-instance: default-instance
            - op: copyFromObject
              fromPath: .metadata.labels['prometheus-instance'] 
              path: .metadata.labels['prometheus-instance']
            - op: replace
              path: .spec.namespaceSelector
              value:
                any: false
                matchNames: []
            - op: rewriteName
              path: .spec.endpoints[*]
            - op: rewriteLabelKey
              path: .spec.jobLabel
            - op: rewriteLabelKey
              path: .spec.targetLabels[*]
            - op: rewriteLabelKey
              path: .spec.podTargetLabels[*]
            - op: rewriteLabelExpressionsSelector
              path: .spec.selector
```

### Host cluster Kubernetes version

<details>

```
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.9+rke2r1", GitCommit:"a1a87a0a2bcd605820920c6b0e618a8ab7d117d4", GitTreeState:"clean", BuildDate:"2023-04-12T19:05:26Z", GoVersion:"go1.19.8 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
RKE2
```

</details>

### vlcuster version

<details>

```
vcluster version 0.15.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu
Arch: x86_64
```
</details>
