### ISSUE TITLE
Deletion of namespace hangs when proxying metrics-server

### ISSUE THREAD

**Issue by trondvindenes-hvikt** [loft-sh/vcluster#1163]
### What happened?

Installed a vcluster using helm chart vcluster-k8s-0.15.5.tgz. Enabled proxy for metrics-server.

I then connect to the vcluster, and try to delete a namespace, even if it's newly created and empty, this happens:
```
Name:         testing
Labels:       kubernetes.io/metadata.name=testing
Annotations:  <none>
Status:       Terminating
Conditions:
  Type                                         Status  LastTransitionTime               Reason                  Message
  ----                                         ------  ------------------               ------                  -------
  NamespaceDeletionDiscoveryFailure            True    Thu, 17 Aug 2023 13:58:06 +0200  DiscoveryFailed         Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server could not find the requested resource
  NamespaceDeletionGroupVersionParsingFailure  False   Thu, 17 Aug 2023 13:58:06 +0200  ParsedGroupVersions     All legacy kube types successfully parsed
  NamespaceDeletionContentFailure              False   Thu, 17 Aug 2023 13:58:06 +0200  ContentDeleted          All content successfully deleted, may be waiting on finalization
  NamespaceContentRemaining                    False   Thu, 17 Aug 2023 13:58:06 +0200  ContentRemoved          All content successfully removed
  NamespaceFinalizersRemaining                 False   Thu, 17 Aug 2023 13:58:06 +0200  ContentHasNoFinalizers  All content-preserving finalizers finished

No resource quota.

No LimitRange resource.
```

### What did you expect to happen?

That I should be able to delete the namespace without messing with namespace finalizers.

### How can we reproduce it (as minimally and precisely as possible)?

Install vcluster
`helm install vcluster vcluster-k8s-0.15.5.tgz -f values.yaml`

values.yaml:
```
proxy:
  metricsServer:
    nodes:
      enabled: true
    pods:
      enabled: true

sync:
  nodes:
    enabled: true
    syncAllNodes: true
  ingresses:
    enabled: true

enableHA: true

syncer:
  image: ghcr.io/loft-sh/vcluster:0.15.5
  replicas: 3

etcd:
  image: registry.k8s.io/etcd:3.5.7-0
  replicas: 3

controller:
  image: registry.k8s.io/kube-controller-manager:v1.24.14
  replicas: 3

api:
  image: registry.k8s.io/kube-apiserver:v1.24.14
  replicas: 3

coredns:
  image: coredns/coredns:1.10.1
  replicas: 3

service:
  type: LoadBalancer
```

`vcluster connect vcluster`
`kubectl create ns testing`
`kubectl delete ns testing`

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:31Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10+vmware.1", GitCommit:"b980a736cbd2ac0c5f7ca793122fd4231f705889", GitTreeState:"clean", BuildDate:"2023-01-24T15:29:49Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
Tanzu Kubernetes Grid Integrated Edition 1.15.x
```
But it's not isolated to TKGI. Happens even in a Kubernetes Kind cluster.

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.15.5
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu Xenial
Arch: x64
```

When running in Kind:
```
OS: RHEL7
Arch: x64
```
</details>

**Comment by ishankhare07** [comment]
Hi @trondvindenes-hvikt I tried reproducing your issues with the following vcluster values:
```yaml
proxy:
  metricsServer:
    nodes:
      enabled: true
    pods:
      enabled: true

sync:
  nodes:
    enabled: true
    syncAllNodes: true
  ingresses:
    enabled: true

enableHA: true

volumes:
  - name: data
    emptyDir: {}

syncer:
  image: ghcr.io/loft-sh/vcluster:0.15.5
  replicas: 3

etcd:
  image: registry.k8s.io/etcd:3.5.7-0
  replicas: 3

controller:
  image: registry.k8s.io/kube-controller-manager:v1.24.14
  replicas: 3

api:
  image: registry.k8s.io/kube-apiserver:v1.24.14
  replicas: 3

coredns:
  image: coredns/coredns:1.10.1
  replicas: 3
```

I can report that I have no issues creating or deleting namespaces inside vcluster. It can be specific to your host cluster environment.

Also can you try this with the latest `0.15.6` or `0.15.7` vcluster releases?
