### ISSUE TITLE
Unable to connect to the VCluster when using an ingress

### ISSUE THREAD

**Issue by mamu-reply** [loft-sh/vcluster#1176]
### What happened?

Hi!
When I configure an ingress I can't connect to the VCluster in any way, if I access the url it always shows "Internal Server Error" and when I try from the command line to do kubectl commands using --kubeconfig it fails to connect.

Can you help me?
Thanks

### What did you expect to happen?

I expect that when I get the kubeconfig I will be able to execute kubectl commands on the VCluster

### How can we reproduce it (as minimally and precisely as possible)?

I've created an ingress like this:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-vcluster-ingress
  namespace: my-vcluster
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-letsencrypt-production-route53
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - my-vcluster.example.com
      secretName: my-vcluster.example.com
  rules:
    - host: my-vcluster.example.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: my-vcluster
                port:
                  number: 443

```
I've also tried without the tls part and adding the annotation `nginx.ingress.kubernetes.io/ssl-passthrough: "true"` and the VCluster values:
```yaml
      sync:
        ingresses:
          enabled: true
      syncer:
        extraArgs:
          - --tls-san=my-vcluster.example.com
```
Then i've created the VCluster with ClusterAPI, and at the end i've used this command to retrive the kubeconfig:

`clusterctl get kubeconfig my-vcluster --namespace my-vcluster | tee ./kubeconfig.yaml`

And after that i've just used this command `kubectl get nodes --kubeconfig ./kubeconfig.yaml`
The result is this:
```
E0824 16:30:02.288468   19622 memcache.go:265] couldn't get current server API group list: Get "https://my-vcluster.example.com:443/api?timeout=32s": tls: failed to verify certificate: x509: certificate is valid for 62488c6dc847af9950d7b9a02d0d0d29.b8ee6d52226ebd3999623e133fa82111.traefik.default, not my-vcluster.example.com
Unable to connect to the server: tls: failed to verify certificate: x509: certificate is valid for 62488c6dc847af9950d7b9a02d0d0d29.b8ee6d52226ebd3999623e133fa82111.traefik.default, not my-vcluster.example.com
```
I've tried also with this command `kubectl get nodes --kubeconfig ./kubeconfig.yaml --insecure-skip-tls-verify=true` and i've obtained this:
```
E0824 16:29:57.047347   19475 memcache.go:265] couldn't get current server API group list: an error on the server ("Internal Server Error") has prevented the request from succeeding
Error from server (InternalError): an error on the server ("Internal Server Error") has prevented the request from succeeding
```

### Anything else we need to know?

I'm trying to create an Helm Chart, after the installation of the CRDs with `clusterctl init --infrastructure vcluster` command i've just created the yaml templates for the namespacess, the ingresses, and Cluster/VCluster resources, but the problem exist also with the normal procedure with command line, with clusterAPI and with vcluster CLI.
I see this problem when i set the ingress.

I've changed annotations with and without SSL-Passthrough and i've also tried to change IngressClass with Nginx, but the problem persist.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:14:48Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.16-eks-2d98532", GitCommit:"af930c12e26ef9d1e8fac7e3532ff4bcc1b2b509", GitTreeState:"clean", BuildDate:"2023-07-28T16:52:47Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
EKS 1.24.0
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# vcluster version 0.15.5
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# k3s (default)
```

</details>

### OS and Arch

<details>

```
OS: MacOS
Arch: ARM64
```
</details>
