### ISSUE TITLE
tolerations for vcluster - Failing - invalid: spec.tolerations[2].operator: Invalid value:

### ISSUE THREAD

**Issue by zohebk8s** [loft-sh/vcluster#1201]
Hi Team,

In Azure AKS, I've created a dedicated namespace along with the nodes bound to it. So that I can create vcluster in that namespace.

However, after adding tolerations, the pod creation is failing with the below error.

```
vcluster-kafka   4s          Warning   FailedCreate           statefulset/vcluster-kafka                     create Pod vcluster-kafka-0 in StatefulSet vcluster-kafka failed error: Pod "vcluster-kafka-0" is invalid: spec.tolerations[2].operator: Invalid value: "Equal": operator must be Exists when `key` is empty, which means "match all values and all keys"
```

I've used the below values for vcluster creation:

```yaml
...
  extraArgs:
  - --tls-san=zoh-kafka-vcluster.k8s-iqra.com
  - --enforce-toleration=app=kafka:NoSchedule
sync:
  nodes:
    enabled: true
    syncAllNodes: true
    nodeSelector: "app=kafka"
```

`app=kafka` is already labeled and tainted at the node level.
