### ISSUE TITLE
Bundled chart deployment fails for more than one bundled chart

### ISSUE THREAD

**Issue by bobh66** [loft-sh/vcluster#1211]
### What happened?

I used the example from the docs:  https://www.vcluster.com/docs/operator/init-manifests#chart-bundle-mode
to create a deployment with two bundled charts:

```
  init:
    helm:
      - bundle: <base64 encoded tar file 1>
        values: |-
          args:
          - -d
        release:
          name: chart1
          namespace: chart1
      - bundle: <base64 encoded tar file 2>
        values: |-
          args:
          - -v
        release:
          name: chart2
          namespace: chart2
```
The first chart applies fine but the second chart fails with an error complaining that the resources from the first chart already exist, which is true, but the second chart shouldn't care.

One clue was in the syncer logs:

```
error executing helm install chart2 /tmp/-.tgz
```

which seemed like a really odd name for a temporary tar file.

Looking at the code:  https://github.com/loft-sh/vcluster/blob/main/pkg/controllers/manifests/init.go#L492
it expects to use chart.name, chart.repo and chart.version in the tar file name for bundles or non-bundles., and clearly chart.name and chart.version are empty in this case, as they are in the example in the docs.

So okay, I'll add the chart info to the inputs:

```
  init:
    helm:
      - bundle: <base64 encoded tar file 1>
        chart:
          name: chart1
          version: 1.0
          repo: dummyrepo
        values: |-
          args:
          - -d
        release:
          name: chart1
          namespace: chart1
      - bundle: <base64 encoded tar file 2>
        chart:
          name: chart2
          version: 1.1
          repo: dummyrepo
        values: |-
          args:
          - -v
        release:
          name: chart2
          namespace: chart2
```
This fails with errors complaining that it can't download the charts from dummyrepo, which is true because the charts are bundled, they don't live in a repo.

Looking at the init configmap it becomes more clear:

```
- name: crossplane
  repo: foo
  version: 1.13.2
- bundle: <base64 encoded tar file 1>
  values: |-
    args:
    - -d
  release:
    name: chart1
    namespace: chart1
- name: vxpresources
  repo: foo
  version: 0.1.0
- bundle: <base64 encoded tar file 2>
  values: |-
     args:
     - -v
  release:
    name: chart2
    namespace: chart2
```

the init configmap template is adding a `-` to the `bundle` and forming a new entry so we end up with four charts instead of two.

I think the solution is to remove the `-` from the bundle entry and update the documentation to show that that chart name, and version are required for bundled charts.

I'll open a PR

### What did you expect to happen?

The two bundled charts should have been applied correctly.

### How can we reproduce it (as minimally and precisely as possible)?

Specify two bundled charts in the init data

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
1.26 client, 1.24 server
```

</details>

### Host cluster Kubernetes distribution

<details>

```
Openshift
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.15.7

```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS:  Linux
Arch: amd64
```
</details>
