### ISSUE TITLE
data mount not added to vcluster container when using TLS for auth to k3s database

### ISSUE THREAD

**Issue by mlbiam** [loft-sh/vcluster#1273]
### What happened?

when using the below vcluster configuration:

```yaml
# Enable HA mode
enableHA: true

# Scale up k3s replicas
replicas: 2

# Set external datastore endpoint
vcluster:
  env:
    - name: K3S_DATASTORE_ENDPOINT
      value: mysql://vcluster_tenant1@tcp(mysql.mysql.svc:3306)/vcluster_tenant1
    - name: K3S_DATASTORE_CERTFILE
      value: /etc/mysql-tls/tls.crt
    - name: K3S_DATASTORE_KEYFILE
      value: /etc/mysql-tls/tls.key
    - name: K3S_DATASTORE_CAFILE
      value: /etc/mysql-tls/ca.crt
  volumeMounts:
  - mountPath: /etc/mysql-tls
    name: mysql-tls
volumes:
- name: mysql-tls
  secret:
    secretName: vcluster-client-tls

# Disable persistent storage as all data (including bootstrap data) is stored in external datastore
storage:
  persistence: false

# Scale up CoreDNS replicas
coredns:
  replicas: 2
```

the `vcluster` would start, but `syncer` container would fail with the error : `I1002 14:27:58.799898       1 start.go:332] couldn't find virtual cluster kube-config, will retry in 1 seconds`

It appears that the `data` volume wasn't attached to the `vcluster` container.  adding it manually in the values.yaml solved the issue:

```yaml
# Enable HA mode
enableHA: true

# Scale up k3s replicas
replicas: 2

# Set external datastore endpoint
vcluster:
  env:
    - name: K3S_DATASTORE_ENDPOINT
      value: mysql://vcluster_tenant1@tcp(mysql.mysql.svc:3306)/vcluster_tenant1
    - name: K3S_DATASTORE_CERTFILE
      value: /etc/mysql-tls/tls.crt
    - name: K3S_DATASTORE_KEYFILE
      value: /etc/mysql-tls/tls.key
    - name: K3S_DATASTORE_CAFILE
      value: /etc/mysql-tls/ca.crt
  volumeMounts:
  - mountPath: /etc/mysql-tls
    name: mysql-tls
  - mountPath: /data
    name: data
volumes:
- name: mysql-tls
  secret:
    secretName: vcluster-client-tls

# Disable persistent storage as all data (including bootstrap data) is stored in external datastore
storage:
  persistence: false

# Scale up CoreDNS replicas
coredns:
  replicas: 2
```

### What did you expect to happen?

For the vcluster to start, connect to the db using the mounted certs 

### How can we reproduce it (as minimally and precisely as possible)?

On an ubuntu 22.04 server running docker:

```console
$ git clone https://github.com/mlbiam/Kubernetes-An-Enterprise-Guide-Third-Edition.git
$ cd Kubernetes-An-Enterprise-Guide-Third-Edition/chapter1
$ ./install-docker.sh
$ cd ../chapter2
$ ./create-cluster.sh
$ cd ../chapter9/ha
$ ./deploy_mysql.sh
$ kubectl create ns tenant1
$ kubectl create -f ./vcluster-tenant1.yaml
```

Create a values file:
```yaml
# Enable HA mode
enableHA: true

# Scale up k3s replicas
replicas: 2

# Set external datastore endpoint
vcluster:
  env:
    - name: K3S_DATASTORE_ENDPOINT
      value: mysql://vcluster_tenant1@tcp(mysql.mysql.svc:3306)/vcluster_tenant1
    - name: K3S_DATASTORE_CERTFILE
      value: /etc/mysql-tls/tls.crt
    - name: K3S_DATASTORE_KEYFILE
      value: /etc/mysql-tls/tls.key
    - name: K3S_DATASTORE_CAFILE
      value: /etc/mysql-tls/ca.crt
  volumeMounts:
  - mountPath: /etc/mysql-tls
    name: mysql-tls
volumes:
- name: mysql-tls
  secret:
    secretName: vcluster-client-tls

# Disable persistent storage as all data (including bootstrap data) is stored in external datastore
storage:
  persistence: false

# Scale up CoreDNS replicas
coredns:
  replicas: 2
```

launch the vcluster:
`vcluster create tenant1 --upgrade -f ./path/to/vaules.yaml -n tenant1`

### Anything else we need to know?

```
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
tenant1 tenant1         1               2023-10-03 15:11:36.798619665 +0000 UTC deployed        vcluster-0.15.7            
```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.3
```

</details>

### Host cluster Kubernetes distribution

<details>

```
KinD
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.15.7
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS:  ubuntu 22.04
Arch: amd64
```
</details>
