### ISSUE TITLE
unable to get kubeconfig for give vcluster after vcluster upgrade

### ISSUE THREAD

**Issue by ashishkamat2791** [loft-sh/vcluster#1277]
### What happened?

`vcluster connect  vcluster-1  -- kubectl config view --raw` stopped working after upgrade of vcluster cli on mac-os

**Before upgrade**
vcluster connect  vcluster-1  -- kubectl config view --raw                                                                                                                                                     ──(Thu,Oct05)─┘
warn   There is a newer version of vcluster: v0.16.0. Run `vcluster upgrade` to upgrade to the newest version.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:  <cert-data>
    server: https://localhost:12087
  name: vcluster-1
contexts:
- context:
    cluster: vcluster-1
    user: vcluster-1-user
  name: vcluster-1
current-context: vcluster-1
kind: Config
preferences: {}
users:
- name: vcluster-1
  user:
    client-certificate-data:  <certificate-data>
    client-key-data:  <key-data>
```
    
  **After upgrade**
  
  `vcluster connect  vcluster-1  -- kubectl config view --raw                                                                                                                                                                                                                                                                                                       1 ↵ ──(Thu,Oct05)─┘
12:35:06 fatal vcluster connect VCLUSTER_NAME [flags]
Invalid Args: received 5 arguments, expected 1, extra arguments: "kubectl, config, view, --raw"
Run with --help for more details on arguments`

### What did you expect to happen?

It should return output as below
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:  <cert-data>
    server: https://localhost:12087
  name: vcluster-1
contexts:
- context:
    cluster: vcluster-1
    user: vcluster-1-user
  name: vcluster-1
current-context: vcluster-1
kind: Config
preferences: {}
users:
- name: vcluster-1
  user:
    client-certificate-data:  <certificate-data>
    client-key-data:  <key-data>
```

### How can we reproduce it (as minimally and precisely as possible)?

Try running 
`vcluster connect  vcluster-1  -- kubectl config view --raw`
on Mac OS

### Anything else we need to know?

_No response_

### Host cluster Kubernetes version

<details>

```console
$ kubectl version

# paste output here
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3+k3s1", GitCommit:"fe9604cac119216e67f8bd5f14eb5608e3bcd3cf", GitTreeState:"clean", BuildDate:"2023-06-26T16:49:54Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3+k3s1", GitCommit:"fe9604cac119216e67f8bd5f14eb5608e3bcd3cf", GitTreeState:"clean", BuildDate:"2023-06-26T16:49:54Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}


</details>


### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>


### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
```
vcluster version 0.16.0
</details>


### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

We have used k3s distribution 
</details>


### OS and Arch

<details>

```
OS: MacOS
Arch:  macOS Ventura
```
</details>
