### ISSUE TITLE
out-kube-config-secret-namespace feature produces unknown namespace for the cache error

### ISSUE THREAD

**Issue by guyguy333** [loft-sh/vcluster#1291]
### What happened?

I try to use out-kube-config-secret-namespace syncer feature but I'm getting this error:

> Error writing kube config to secret: creating xxxxx-kubeconfig secret in the vclusters ns failed: apply generated kube config secret: unable to get: vclusters/xxxxx-kubeconfig because of unknown namespace for the cache

vCluster syncer is running in vcluster-xxxx namespace and I would like my kubeconfig secret to be available in vclusters namespace.
I added this RBAC so syncer pod can read/write secrets in vclusters namespace without luck. Any idea what's wrong ?

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vclusters-kubeconfig-rw
  namespace: vclusters
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vclusters-kubeconfig-rw-xxxxx
  namespace: vclusters
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vclusters-kubeconfig-rw
subjects:
  - kind: ServiceAccount
    name: vc-vcluster
    namespace: vcluster-xxxx
```

### What did you expect to happen?

- No longer syncer error and a secret write in the right namespace 
- Minimal RBAC documented for this feature

### How can we reproduce it (as minimally and precisely as possible)?

Just use `out-kube-config-secret-namespace` feature with a namespace different than vcluster namespace

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
1.28
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
v0.16.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>
