### ISSUE TITLE
K3s HA mode not working

### ISSUE THREAD

**Issue by bbenlazreg** [loft-sh/vcluster#1299]
### What happened?

I set enableHA to true in helm values using k3s mode, however what It tried to do is to replace the statefulset with a Deployment, And the deployment was missing the data volume

```
Error: UPGRADE FAILED: failed to create resource: Deployment.apps "my-vcluster" is invalid: [spec.template.spec.containers[0].volumeMounts[1].name: Not found: "data", spec.template.spec.containers[1].volumeMounts[4].name: Not found: "data"]
}
```

### What did you expect to happen?

k3s in HA mode following k3s documentation

### How can we reproduce it (as minimally and precisely as possible)?
```
values.yaml
enableHA: true
```

```
helm upgrade --install my-vcluster vcluster \                                                    
  --values values.yaml \
  --repo https://charts.loft.sh \
  --namespace vcluster-my-vcluster \
  --repository-config=''
```
### Anything else we need to know?

Chart version
0.16.3

### Host cluster Kubernetes version

1.27

### Host cluster Kubernetes distribution

OCI OKE

### vlcuster version

v1.27.2-k3s1

### vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

k3s

### OS and Arch

Oracle Linux 8

**Comment by ishankhare07** [comment]
possible duplicate #1273 
possibly fixed by #1274

**Comment by ishankhare07** [comment]
Hi @bbenlazreg , thanks for creating this issue. Can you share your full values.yaml file. Can you confirm that it is atleast in line with what the documentation says here - https://www.vcluster.com/docs/deploying-vclusters/high-availability#enabling-high-availability-with-k3s

**Comment by ishankhare07** [comment]
@bbenlazreg as a reference here is what I've tried
values.yaml
```
# Enable HA mode
enableHA: true

# Scale up k3s replicas
replicas: 2

# Set external datastore endpoint
vcluster:
  env:
    - name: K3S_DATASTORE_ENDPOINT
      value: mysql://test:test@tcp(mysql.datastore.svc.cluster.local:3306)/test

# Disable persistent storage as all data (including bootstrap data) is stored in external datastore
storage:
  persistence: false

# Scale up CoreDNS replicas
coredns:
  replicas: 2
```

created vcluster with the following command
`vcluster create vcluster-k3s-ha --chart-version=v0.16.3 -n k3s-ha -f vcluster.yaml`
