### ISSUE TITLE
Multi-Container Apps Failing

### ISSUE THREAD

**Issue by Vertiwell** [loft-sh/vcluster#130]
Hi,
My latest clusters are not deploying apps properly and I can't find enough detail in the logs or events to figure out why.
They are scripted vcluster deployments and have never had an issue before. (last deployed successfully about 2 weeks ago)
An example would be, I deploy Vcluster 
```
rbac:
  clusterRole:
    create: true
vcluster:
  image: rancher/k3s:v1.21.4-k3s1
  extraArgs:
    - --service-cidr=10.43.0.0/16
syncer:
  extraArgs:
    - --disable-sync-resources=ingresses
    - --enable-storage-classes=true
```
Then deploy redis:
helm install redis bitnami/redis --set sentinel.enabled=true --values https://raw.githubusercontent.com/helm/charts/master/stable/redis/values-production.yaml

It fails a few pods in (Sentinel pod).
I have the same issue deploying kubegres, it deploys the first pod (postgres-1-0), then starts crashing on the 2nd replica (postgres-2-0).

Anything with no "multi-pod" setup seems to work fine, it almost seems like an internal networking issue.
Deploying the same apps on the host cluster has no issues, only when deploying on VCluster.

I have lifted these scripts and redeployed it elsewhere with the same results.
