### ISSUE TITLE
Service account token request from synced service account does not work with AWS IRSA

### ISSUE THREAD

**Issue by giepa** [loft-sh/vcluster#1310]
### Is your feature request related to a problem?

In our setup, to facilitate AWS IRSA, we configured service accounts to be synced to the host cluster:
```
sync:
  serviceaccounts:
    enabled: true
```
This works well when service accounts are mounted on pods. However when a service account token is requested in vcluster, for example:
```
kubectl create token mysa
```
Then the token is rejected as invalid by the AWS sdk:
```
WebIdentityErr: failed to retrieve credentials caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://kubernetes.default.svc.cluster.local status code: 400,
```
I suspect it is because the token is issued by the vcluster and not the host cluster. Is there a way around this, how can we request a valid token?

### Which solution do you suggest?

Vcluster should forward service account token requests to the host cluster when service account sync is enabled.

**Comment by FabianKramm** [comment]
@giepa thanks for creating this issue! That is expected, since vcluster has its own service accounts and certificates. You will need to add the annotation to the actual workload service account and then AWS should inject a token automatically.

**Comment by giepa** [comment]
@FabianKramm thanks for your response, could you clarify:
> You will need to add the annotation to the actual workload service account

Which annotation are you referring to?

In our case, the workload service account is not being used, instead a token is requested for a given service account, in a given namespace. 

To give more context, we are running [external-secrets-operator](https://github.com/external-secrets/external-secrets) in vcluster. The operator has the concept of secret store, where a service account reference is provided, for example:
```
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: my-store
  namespace: my-ns
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: my-sa
```
For the above example, external secrets operator, will request a token for service account `my-sa` in `my-ns` and use it to authenticate with the AWS-sdk. It is this token that is rejected as invalid:
```
WebIdentityErr: failed to retrieve credentials caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://kubernetes.default.svc.cluster.local status code: 400,
```

Is there a way around this? Would vcluster be able to request tokens from the host cluster instead, when service account sync is enabled?

**Comment by stdmje** [comment]
I think i am facing a similar issue when trying to use IRSA in a Elasticsearch cluster.
The IRSA is used for backup and restore to S3 and everything works fine but after some time  the credentials are not valid anymore and i get some errors.
If i restart the cluster pods, everything starts to work again until the credentials are expired again.
```
$ curl "http://localhost:9200/_cat/snapshots/mys3repo?pretty" 
{
  "error" : {
    "root_cause" : [
      {
        "type" : "sdk_client_exception",
        "reason" : "sdk_client_exception: Unable to load AWS credentials from any provider in the chain: [org.elasticsearch.repositories.s3.S3Service$ErrorLoggingCredentialsProvider@3f051598: Task java.util.concurrent.FutureTask@65c69887[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@5ba74179[Wrapped task = com.amazonaws.auth.RefreshableTask$1@5438c4da]] rejected from java.util.concurrent.ThreadPoolExecutor@5ff3aaa7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], org.elasticsearch.repositories.s3.S3Service$ErrorLoggingCredentialsProvider@356db0ab: Unauthorized (Service: null; Status Code: 401; Error Code: null; Request ID: null; Proxy: null)]"
      }
    ],
    "type" : "snapshot_exception",
    "reason" : "[mys3repo:manual_snapshot_2023.10.24/UuawRIqLR92R7kxXULC7UA] Snapshot could not be read",
    "caused_by" : {
      "type" : "sdk_client_exception",
      "reason" : "sdk_client_exception: Unable to load AWS credentials from any provider in the chain: [org.elasticsearch.repositories.s3.S3Service$ErrorLoggingCredentialsProvider@3f051598: Task java.util.concurrent.FutureTask@65c69887[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@5ba74179[Wrapped task = com.amazonaws.auth.RefreshableTask$1@5438c4da]] rejected from java.util.concurrent.ThreadPoolExecutor@5ff3aaa7[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0], org.elasticsearch.repositories.s3.S3Service$ErrorLoggingCredentialsProvider@356db0ab: Unauthorized (Service: null; Status Code: 401; Error Code: null; Request ID: null; Proxy: null)]"
    }
  },
  "status" : 500
}
```
If i setup a cluster with the exact same configuration in the host cluster, the credentials are not expiring and everything keeps working.

**Comment by joaocc** [comment]
@giepa did you manage to get an answer to this? we have exactly the same need. It would be wonderful if we could do it via IRSA. If that is not possible, an alternative (which you prob already considered) would be to configure the provider to use explicit IAM account and credentials, but this kind of negates the advantages of IRSA/AWS and is less secure.

**Comment by giepa** [comment]
@joaocc as an interim, we did configure the provider to use explicit IAM account and credentials, as you said its not secure, we are getting away with it only because its for dev environments, for production such an approach would be a no go. If you do come up with something better, please let us know.

**Comment by joaocc** [comment]
Update from recent testing:

When we create the following manifest inside the vcluster, we get no errors and we get `store validated`
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-ssm-ps--0
spec:
  provider:
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: ext-secrets-sa-x-ext-secrets-x-vcluster
      region: eu-west-1
      service: ParameterStore
```

However, if we then add an ExternalSecret with a reference to that cluster secret store, it won't synchronize, and I get the following error
`unable to create session: ServiceAccount "ext-secrets-sa-x-ext-secrets-x-vcluster" not found`
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-ext-secr-1
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm-ps--0
  data:
    - remoteRef:
        key: /path/to/ssm-ps-key/k1
      secretKey: my_k1
    - remoteRef:
        key: /path/to/ssm-ps-key/k2
      secretKey: my_k2
  dataFrom: []
  refreshInterval: 4h
  target:
    ...
```

Additionally:
* using vcluster-eks 0.16.4 on EKS 1.27
* "sync.serviceaccounts" is also set to true
* the AWS role is created correctly and annotated with "ext-secrets-sa-x-ext-secrets-x-vcluster" at the correct host namespace (not vcluster namespace) and has permissions on the SSM-PS 
* the service account is annotated with the ARN of the role

@FabianKramm, would you have any suggestion on this? Thanks
