### ISSUE TITLE
DaemonSet tries to schedule pods to control plane (master) node even though marked NoSchedule.

### ISSUE THREAD

**Issue by GrahamDumpleton** [loft-sh/vcluster#132]
When a DaemonSet is created, it creates a Pod for each fake node in the virtual cluster with an affinity rule.

```
   affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:                                             
         - matchFields:
           - key: metadata.name
             operator: In
             values:
             - ip-10-0-1-192.eu-central-1.compute.internal
```

It appears to do this for all nodes, even when the fake node corresponds to a control plane (master) node which has taint of `NoSchedule`.

From virtual cluster:

```
$ k get nodes -o wide
NAME                                          STATUS   ROLES    AGE     VERSION        INTERNAL-IP      EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION      CONTAINER-RUNTIME
ip-10-0-1-192.eu-central-1.compute.internal   Ready    <none>   14m     v1.19.5+k3s2   10.100.251.37    <none>        Fake Kubernetes Image   4.19.76-fakelinux   docker://19.3.12
ip-10-0-1-33.eu-central-1.compute.internal    Ready    <none>   11m     v1.19.5+k3s2   10.97.142.13     <none>        Fake Kubernetes Image   4.19.76-fakelinux   docker://19.3.12
ip-10-0-1-100.eu-central-1.compute.internal   Ready    <none>   8m47s   v1.19.5+k3s2   10.108.218.223   <none>        Fake Kubernetes Image   4.19.76-fakelinux   docker://19.3.12
ip-10-0-1-11.eu-central-1.compute.internal    Ready    <none>   8m47s   v1.19.5+k3s2   10.111.189.160   <none>        Fake Kubernetes Image   4.19.76-fakelinux   docker://19.3.12
```

From underlying cluster:

```
$ k get nodes -o wide
NAME                                          STATUS   ROLES                  AGE   VERSION            INTERNAL-IP   EXTERNAL-IP   OS-IMAGE         KERNEL-VERSION                  CONTAINER-RUNTIME
ip-10-0-1-100.eu-central-1.compute.internal   Ready    <none>                 55d   v1.20.6+vmware.1   10.0.1.100    <none>        Amazon Linux 2   4.14.231-173.361.amzn2.x86_64   containerd://1.4.3
ip-10-0-1-11.eu-central-1.compute.internal    Ready    <none>                 48d   v1.20.6+vmware.1   10.0.1.11     <none>        Amazon Linux 2   4.14.231-173.361.amzn2.x86_64   containerd://1.4.3
ip-10-0-1-192.eu-central-1.compute.internal   Ready    control-plane,master   55d   v1.20.6+vmware.1   10.0.1.192    <none>        Amazon Linux 2   4.14.231-173.361.amzn2.x86_64   containerd://1.4.3
ip-10-0-1-33.eu-central-1.compute.internal    Ready    <none>                 55d   v1.20.6+vmware.1   10.0.1.33     <none>        Amazon Linux 2   4.14.231-173.361.amzn2.x86_64   containerd://1.4.3
```

Where the control plane (master) node has:

```
spec:
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
```

The result is that the Pod assigned for the DaemonSet to the control plane (master) node fails to be run.

```
status:
   conditions: 
   - lastProbeTime: null
     lastTransitionTime: "2021-09-13T05:49:47Z"                         
     message: '0/4 nodes are available: 1 node(s) had taint {node-role.kubernetes.io/master:}, that the pod didn''t tolerate, 3 node(s) didn''t match Pod''s node affinity.'
```

The fake nodes should possibly replicate the taints related to `NoSchedule` and take that into consideration when creating a Pod for a DaemonSet.
