### ISSUE TITLE
init.helm documentation in vclusters-eks doesn't match documentation

### ISSUE THREAD

**Issue by joaocc** [loft-sh/vcluster#1349]
### What happened?

We are currently not able to deploy helm charts via init (using vcluster-eks). In that process, we found that there is a divergence between what is commented out in values.yaml and what is in the documentation:

in https://github.com/loft-sh/vcluster/blob/6fa4d57efef8f7a9b004d9d905761845706995dd/charts/eks/values.yaml#L429
```
init:
(...)
  helm: []
(...)
    #   release:
    #     releaseName: <string> REQUIRED
    #     releaseNamespace: <string> REQUIRED
```
Is not aligned with documentation in https://www.vcluster.com/docs/deploying-vclusters/init-charts#upstream-mode, where it is mentioned as 
```
    #   release:
    #     name: <string>
    #     namespace: <string>

```
We are still not yet able to get any of these to work, but at least one of these seems in need of a correction.

### What did you expect to happen?

Documentation consistent with examples.
Init to deploy helm releases inside vcluster.

### How can we reproduce it (as minimally and precisely as possible)?

The documentation vs example doesn't need repro.

### Host cluster Kubernetes version

N/A

### Host cluster Kubernetes distribution

EKS

### vlcuster version

<details>

```console
$ vcluster --version
0.16.4
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
eks
```

</details>

### OS and Arch

<details>

```
```
</details>

**Comment by rohantmp** [comment]
The section in the docs works when I used the values minus the private chart example:

`vcluster create -n helm-test helm-test  -f docs-init-helm.yaml`


```

init:
  helm:
    # public chart
    - chart:
        name: cert-manager
        repo: https://charts.jetstack.io
        version: v1.8.0
      # optional field
      values: |-
        installCRDs: true
      release:
        name: cert-manager
        namespace: cert-manager
```

The comment in the values.yaml is wrong and I'll update it.

Perhaps you have  mistake in your indentation? Would be helpful to understand what went wrong. You can look at syncer logs to see if there's an error unmarshalling your config, and paste the values you used here. I can take a look
