### ISSUE TITLE
what is v-cluster-job and why is it starting every 5 sec

### ISSUE THREAD

**Issue by mad01** [loft-sh/vcluster#1360]
### What happened?

We are running the helm k8s release 0.16.4 and even older version in 0.15.x had the same behaviour.  We have a job v-cluster-job that is starting every 5 sec and this is from the looks of it causing argocd to mark the v-cluster as out of sync. I have been looking in the source and docs but can't find what the v-cluster-job is doing and why it's running every 5 sec. We just need to understand why. 

this is a subset of the pod spec for the job. 
```yaml
    template:
      metadata:
          job-name: v-cluster-job
        name: v-cluster-job
      spec:
        containers:
        - args:
          - --prefix=v-cluster
          - --etcd-replicas=1
          command:
          - /vcluster
          - certs
          image: ghcr.io/loft-sh/vcluster:0.16.4
          name: certs
          volumeMounts:
          - mountPath: /certs
            name: cert-storage

```

### What did you expect to happen?

no input

### How can we reproduce it (as minimally and precisely as possible)?

no input

### Anything else we need to know?

no input

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here no input
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here no input 
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here no input
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here no input
```

</details>

### OS and Arch

<details>

```
OS: 
Arch: no input
```
</details>
