### ISSUE TITLE
error when synching StorageClass (vcluster->host) after vcluster restart

### ISSUE THREAD

**Issue by joaocc** [loft-sh/vcluster#1368]
### What happened?

Configured vcluster to sync storage classes.
Added a couple of storage classes (efs.csi driver with parameters) and they replicate without any issues.
After restarting`vcluster` pods, I get `error when patching "manifests": StorageClass.storage.k8s.io "efs--something" is invalid: parameters: Forbidden: updates to parameters are forbidden`.

### What did you expect to happen?

That storage classes synchronize correctly.

### How can we reproduce it (as minimally and precisely as possible)?

Storage class inside vcluster
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs--0adm-root
  annotations:
    something: here
provisioner: efs.csi.aws.com
parameters:
  basePath: /
  directoryPerms: '700'
  ensureUniqueDirectory: ''
  fileSystemId: fs-00000000001111118
  fsType: efs
  gid: ''
  gidRangeEnd: ''
  gidRangeStart: ''
  provisioningMode: efs-ap
  subPathPattern: /
  uid: ''
reclaimPolicy: Retain
mountOptions:
  - noatime
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.7-eks-4f4795d```

</details>


### Host cluster Kubernetes distribution

<details>

```
EKS 1.27
```

</details>


### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.16.4
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
eks
```

</details>

### OS and Arch

N/A
