### ISSUE TITLE
Unable to connect to vcluster via CLI after exposing it via Loadbalancer

### ISSUE THREAD

**Issue by frank-bee** [loft-sh/vcluster#1389]
### What happened?

```
➜  gitrepos vcluster connect tenant-a-tenant-a
11:01:04 fatal unexpected server in kubeconfig: https://cluster-tenant-a.mydomain.com
```

But it works if I download kubeconfig from the related secret.
It also worked before exposing it via Loadbalancer ( NLB in AWS I use)

### What did you expect to happen?

Kubeconfig should be extended and context switched

### How can we reproduce it (as minimally and precisely as possible)?

this is how I create the tenent via Helm and expose it via an extra Service 

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant-a
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: tenant-a
  chart:
    spec:
      chart: vcluster-eks
      sourceRef:
        kind: HelmRepository
        name: loft-sh
        namespace: flux-system
  install:
    remediation:
      retries: 3
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    syncer:
      extraArgs:
        - --tls-san=cluster-tenant-a.mydoain.com
        - --out-kube-config-server=https://cluster-tenant-a.mydomain.com
    sync:
      ingresses:
        enabled: true
    # Service account that should be used by the pods synced by vcluster
    workloadServiceAccount:
      # This is not supported in multi-namespace mode
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::111111111111111:role/tenant-a-main-irsa-role
---
apiVersion: v1
kind: Service
metadata:
  name: vcluster-service-exposed
  namespace: tenant-a
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: cluster-tenant-a.mydomain.com
    service.beta.kubernetes.io/load-balancer-source-ranges: ...
spec:
  selector:
    app: vcluster
    release: tenant-a-tenant-a
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: LoadBalancer
```

### Anything else we need to know?

-

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
$ kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.15-eks-4f4795d
WARNING: version difference between client (1.28) and server (1.25) exceeds the supported minor version skew of +/-1

```

</details>

### Host cluster Kubernetes distribution

<details>

```
AWS EKS
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.17.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
EKS
```

</details>

### OS and Arch

<details>
max book pro 
</details>
