### ISSUE TITLE
Endpoints are not updated in Host -> vCluster Service mappings of headless services

### ISSUE THREAD

**Issue by ndbrew** [loft-sh/vcluster#1401]
### What happened?

When mapping a headless service from the Host to a vCluster, the initial mapping syncs fine but if the underlying endpoint ip's change after that (e.g. pods get restarted, scaled up or down...etc), then the syncer doesn't reconcile the change unless the service resource itself gets updated.

### What did you expect to happen?

If the endpoints underlying a mapped headless service are updated, the change should be synced as well.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a vanilla k8s vCluster
```
#nginx-test.yaml
mapServices:
 fromHost:
   - from: vcluster-nginx-test/nginx-headless
     to: nginx/nginx-headless
etcd:
  storage:
    persistence: false
```
`helm upgrade nginx-test loft-sh/vcluster-k8s -n vcluster-nginx-test --create-namespace --install -f nginx-values.yaml`

2. Create a deployment with multiple replicas.
```
kubectl create deployment nginx --image=nginx --replicas=3 -n vcluster-nginx-test 
```

3. Create a headless service for the deployment.
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  namespace: vcluster-nginx-test
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
  clusterIP: None
  type: ClusterIP
  internalTrafficPolicy: Cluster
```
3a Add endpoints permissions the ClusterRole for the newly created cluster in the host cluster
Not sure this should have been necessary, I have not needed to do this in other deployments, just these simplified steps.
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vc-nginx-test-v-vcluster-nginx-test
  labels:
    app: vcluster
    app.kubernetes.io/managed-by: Helm
    chart: vcluster-k8s-0.18.0
    heritage: Helm
    release: nginx-test
  annotations:
    meta.helm.sh/release-name: nginx-test
    meta.helm.sh/release-namespace: vcluster-nginx-test
rules:
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - ''
    resources:
      - services
      - endpoints
```
4. Check that the sync worked correctly in the vcluster
```
$ kubectl get services -n nginx
$ kubectl get endpoints -n nginx
```
6. Delete a few pods from the deployment in the host cluster
7. Notice that the endpoints in the vCluster are still the same even though the endpoints in the host cluster have changed.

### Anything else we need to know?

<details>
Deleting the synced service in the vCluster triggers the endpoints to be updated again
</details>

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
Talos OS <v1.6.0-beta-0>
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.16.3
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: Talos OS <v1.6.0-beta-0>
Arch: amd64
```
</details>
