### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by frank-bee** [loft-sh/vcluster#1408]
### What happened?

If I install the helm chart, I get restarts on the main pod (syncer container):
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1faffe5]

goroutine 1 [running]:
github.com/loft-sh/vcluster/pkg/telemetry.(*DefaultCollector).RecordError(0xc0003c7200, {0x309d3f0, 0xc000b169f0}, {0x2aca930, 0x5}, {0x306e340, 0xc000bfc780})
	github.com/loft-sh/vcluster/pkg/telemetry/collect.go:234 +0x1a5
github.com/loft-sh/vcluster/cmd/vcluster/cmd.NewStartCommand.func1.1()
	github.com/loft-sh/vcluster/cmd/vcluster/cmd/start.go:61 +0x15b
panic({0x266d620?, 0x48fc850?})
	runtime/panic.go:914 +0x21f
github.com/loft-sh/vcluster/pkg/telemetry.(*DefaultCollector).RecordStart(0xc0003c7200, {0x309d3f0, 0xc000b169f0})
	github.com/loft-sh/vcluster/pkg/telemetry/collect.go:198 +0xc5
github.com/loft-sh/vcluster/pkg/setup.Initialize({0x309d3f0, 0xc000b169f0}, {0x30cb770?, 0xc000595d40?}, {0x30cb770?, 0xc000595d40?}, {0xc000695440?, 0x8?}, {0xc000695440, 0x8}, ...)
	github.com/loft-sh/vcluster/pkg/setup/initialize.go:64 +0x262
github.com/loft-sh/vcluster/cmd/vcluster/cmd.ExecuteStart({0x309d3f0, 0xc000b169f0}, 0xc00097bc00)
	github.com/loft-sh/vcluster/cmd/vcluster/cmd/start.go:112 +0x22b
github.com/loft-sh/vcluster/cmd/vcluster/cmd.NewStartCommand.func1(0xc0009e3b00, {0xc000444e70?, 0x4?, 0x2ac9c14?})
	github.com/loft-sh/vcluster/cmd/vcluster/cmd/start.go:69 +0xd8
github.com/spf13/cobra.(*Command).execute(0xc0009e3b00, {0xc000444dc0, 0xb, 0xb})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009e3800)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(0x309d3b8?, {0x309d3f0?, 0xc000b169f0?})
	github.com/spf13/cobra@v1.8.0/command.go:1032 +0x47
main.main()
	github.com/loft-sh/vcluster/cmd/vcluster/main.go:42 +0x1bc
```

### What did you expect to happen?

no restarts , helm release should be  intalled

### How can we reproduce it (as minimally and precisely as possible)?

Install the helm chart with these values :

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant-a
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: tenant-a
  # should be as short as possible
  releaseName: ta
  chart:
    spec:
      chart: vcluster-eks
      sourceRef:
        kind: HelmRepository
        name: loft-sh
        namespace: flux-system
  install:
    remediation:
      retries: 3
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    sync:
      ingresses:
        enabled: true
      serviceaccounts:
        enabled: true
    # All supported versions are in https://github.com/loft-sh/vcluster/blob/main/pkg/values/eks.go
    # Kubernetes Controller Manager settings
    controller:
      image: public.ecr.aws/eks-distro/kubernetes/kube-controller-manager:v1.25.14-eks-1-25-23
    # Kubernetes API Server settings
    api:
      image: public.ecr.aws/eks-distro/kubernetes/kube-apiserver:v1.25.14-eks-1-25-23
    # Core DNS settings
    coredns:
      image: public.ecr.aws/eks-distro/coredns/coredns:v1.9.3-eks-1-25-27
    # Etcd settings
    etcd:
      image: public.ecr.aws/eks-distro/etcd-io/etcd:v3.5.8-eks-1-25-23
```
      

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.15", GitCommit:"da6089da4974a0a180c226c9353e1921fa3c248a", GitTreeState:"clean", BuildDate:"2023-10-18T13:40:02Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.15-eks-4f4795d", GitCommit:"9587e521d190ecb7ce201993ceea41955ed4a556", GitTreeState:"clean", BuildDate:"2023-10-20T23:22:38Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.17.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
EKS
```

</details>

### OS and Arch

-
