### ISSUE TITLE
OOMKilled Init container

### ISSUE THREAD

**Issue by stand-sure** [loft-sh/vcluster#1420]
### What happened?

I am encountering frequent OOMKilled failures when running vcluster create. The cluster itself is running k3s 1.28.4

The rendered yaml is

```yaml
initContainers:
  - args:
    - -c
    - cp /bin/k3s /k3s-binary/k3s
    command:
    - /bin/sh
    image: rancher/k3s:v1.28.2-k3s1
    imagePullPolicy: IfNotPresent
    name: vcluster
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 20m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      runAsGroup: 0
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /k3s-binary
      name: k3s-binary
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gpt45
      readOnly: true
```

### What did you expect to happen?

The cluster to come up

### How can we reproduce it (as minimally and precisely as possible)?

vcluster create lde-dep-test -f https://raw.githubusercontent.com/loft-sh/vcluster-plugins/master/cert-manager-plugin/plugin.yaml

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here

Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4+k3s2
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
k3s version v1.28.4+k3s2 (6ba6c1b6)
go version go1.20.11
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
k3s
```

</details>

### OS and Arch

<details>

```
Linux lima-rancher-desktop 6.1.57-0-virt #1-Alpine SMP Wed, 11 Oct 2023 07:01:12 +0000 aarch64 Linux
```
</details>

**Comment by stand-sure** [comment]
bumping the initContainer resources.limits.memory to "256Mi" worked for me locally as a hack

```yaml
args:
  - -c
  - cp /bin/k3s /k3s-binary/k3s
command:
  - /bin/sh
image: rancher/k3s:v1.28.2-k3s1
imagePullPolicy: IfNotPresent
name: vcluster
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 20m
    memory: 64Mi
securityContext:
  allowPrivilegeEscalation: false
  runAsGroup: 0
  runAsUser: 0
terminationMessagePath: /dev/termination-log
terminationMessagePolicy: File
volumeMounts:
  - mountPath: /k3s-binary
    name: k3s-binary
```
