### ISSUE TITLE
Allow in the helm charts to specify a k8s version 

### ISSUE THREAD

**Issue by frank-bee** [loft-sh/vcluster#1427]
### Is your feature request related to a problem?

Currently this has to be done like this, which is little complicated 
( In the CLI this is easier )

```
    # Kubernetes Controller Manager settings
    controller:
      image: public.ecr.aws/eks-distro/kubernetes/kube-controller-manager:v1.25.14-eks-1-25-23
    # Kubernetes API Server settings
    api:
      image: public.ecr.aws/eks-distro/kubernetes/kube-apiserver:v1.25.14-eks-1-25-23
    # Core DNS settings
    coredns:
      image: public.ecr.aws/eks-distro/coredns/coredns:v1.9.3-eks-1-25-27
    # Etcd settings
    etcd:
      image: public.ecr.aws/eks-distro/etcd-io/etcd:v3.5.8-eks-1-25-23
```

### Which solution do you suggest?

Encode at least the latest 3-5 k8s version (of EKS) in the helm chart, similar to here:
https://github.com/loft-sh/vcluster/blob/main/pkg/values/eks.go

Allow specifying a single value  in the helm chart values, e.g. 
`kubernetes_version: "1.28"`
