### ISSUE TITLE
Cannot connect to datastore with network isolation

### ISSUE THREAD

**Issue by alpharde** [loft-sh/vcluster#1428]
### What happened?

The vcluster pod cannot connect to external databases while network isolation is enabled.

### What did you expect to happen?

vcluster being able to reach the external server.

### How can we reproduce it (as minimally and precisely as possible)?

Create vcluster with
```
(...)
vcluster:
  env:
    - name: K3S_DATASTORE_ENDPOINT
      value: mysql://user:pass@tcp(10.0.4.139:3306)/database
(...)
isolation:
  enabled: true   
  resourceQuota:
    enabled: true
    quota:
      services.nodeports: 12
      services.loadbalancers: 12
      requests.storage: "256Gi"
  networkPolicy:
    enabled: true
    outgoingConnections:
      ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.4.139/32
```

### Anything else we need to know?

vcluster log:
`2023-12-26 19:39:50	INFO	loghelper/klog.go:24	starting kubernetes: preparing server: creating storage endpoint: building kine: dial tcp 10.0.4.139:3306: connect: connection refused	{"component": "vcluster", "component": "k3s", "time": "2023-12-26T19:39:50Z", "level": "fatal"}`

### Host cluster Kubernetes version

<details>
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.5+k3s1
</details>

### Host cluster Kubernetes distribution

<details>
k3s
</details>

### vlcuster version

<details>
vcluster version 0.18.1
</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>
k3s
</details>

### OS and Arch

<details>
Debian bookworm (amd64)
</details>
