### ISSUE TITLE
Configurable hosts rewrite image

### ISSUE THREAD

**Issue by Fabian-K** [loft-sh/vcluster#148]
Hi,

it would be great if the image used for the host rewrite (vcluster/pkg/controllers/resources/pods/translate/hosts.go) is somehow configurable. In some environments, pulling from the docker registry might be rate-limited. Making this configurable would allow us to pull from a different registry instead.

Thanks, Fabian

**Comment by FabianKramm** [comment]
@Fabian-K yes exactly, the syncer flags also do not show up in the cli unless we create a seperate flag for it.

**Comment by Fabian-K** [comment]
Sorry, my fault! I got it working with

```yaml
syncer:
  extraArgs:
    - --override-hosts-container-image=alpine:3.13.1

```
or with
```yaml
syncer:
  extraArgs:
    - --override-hosts-container-image
    - alpine:3.13.1
```

Your suggesting caused the vcluster pod to CrashLoopBackOff state with the following log output of the syncer container.

```
syncer F1019 10:39:24.220870       1 main.go:143] unknown flag: --override-hosts-container-image alpine:3.13.1
```

Thanks for your support!
