### ISSUE TITLE
anti affinity missing on synced pod if namespace selector matches all namespaces

### ISSUE THREAD

**Issue by ytizhang** [loft-sh/vcluster#1484]
### What happened?

We are installing multiple charts in different namespaces, and for some pods, they need pod anti affinity across all the namespaces, to make sure no two pods from the same role are scheduled to the same node.

```
affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: sfcn.cisco.com/enforcement-point
                operator: Exists
          topologyKey: kubernetes.io/hostname
          namespaceSelector: {}
```

The "[sfcn.cisco.com/enforcement-point](http://sfcn.cisco.com/enforcement-point)" label is used to indicate the pod is an enforcer role, and no two enforcer pods should be scheduled to the same node, regardless of namespace.
However, when this pod is synced to the host cluster, the "[sfcn.cisco.com/enforcement-point](http://sfcn.cisco.com/enforcement-point)" label is missing. We are seeing the following anti affinity rule, which matches all the pods installed in the corresponding vcluster.

```
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              vcluster.loft.sh/managed-by: <vcluster-name>
          topologyKey: kubernetes.io/hostname
```

### What did you expect to happen?

I expect to see the matchExpressions preserved in the synced pod

```
matchExpressions:
    - key: sfcn.cisco.com/enforcement-point
      operator: Exists
```

### How can we reproduce it (as minimally and precisely as possible)?

Create a pod using the following spec in a vcluster

```
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: aws-cli
      image: amazon/aws-cli:latest
      command:
        - /bin/bash
        - '-c'
        - sleep infinity
      imagePullPolicy: Always
  affinity:
    podAntiAffinity:  
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: sfcn.cisco.com/enforcement-point
                operator: Exists
          topologyKey: kubernetes.io/hostname
          namespaceSelector: {}
```

Go to the host cluster, read the pod spec, you'll have the following affinity config

```
affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              vcluster.loft.sh/managed-by: <vcluster-name>
          topologyKey: kubernetes.io/hostname
```

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.16", GitCommit:"c5f43560a4f98f2af3743a59299fb79f07924373", GitTreeState:"clean", BuildDate:"2023-11-15T22:39:12Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25+", GitVersion:"v1.25.16-eks-8cb36c9", GitCommit:"3a3ea80e673d7867f47bdfbccd4ece7cb5f4a83a", GitTreeState:"clean", BuildDate:"2023-11-22T21:53:22Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.18.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
vcluster-eks
```

</details>

### OS and Arch

<details>

```
OS: N/A
Arch: N/A
```

</details>
