### ISSUE TITLE
PVCs are always created with vCluster 0.19.0-alpha.4

### ISSUE THREAD

**Issue by paalkr** [loft-sh/vcluster#1491]
### What happened?

I have specified that a k3s vCluster should use Postgres as the state store backend, and I have for this reason disabled persistence. With vCluster 0.19.0-alpha.4 PVCs are created for the statefulset regardless of the persistence configuration, if the config is under syncer or root of the values file does not make any difference

```
syncer:
  storage:
    persistence: false
  env:
  - name: K3S_DATASTORE_ENDPOINT
    value: "postgres://postgres:xx@foo.bar:5432/vcluster_1"

storage: 
  persistence: false
```

I belive this commit introduced the problem https://github.com/loft-sh/vcluster/commit/d06294c0a0201ca3517e157b2f734f552a23171b#diff-6a6c423adc693fd96601abc863cd546962bf6b6d9de1ab00835b37409bd9c124

vCluster 0.19.0-alpha.3 does not have the same bug

### What did you expect to happen?

No PVCs should be created for the statefulset

### How can we reproduce it (as minimally and precisely as possible)?

Create vcluster with persistence: false, and observe that the PVCs are actaully created

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
v1.28.4-eks-8cb36c9
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
0.19.0-alpha.4
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: Amazon Linux 2
Arch: AMD64
```
</details>
