### ISSUE TITLE
Object status is not synced from host objects to virtual objects

### ISSUE THREAD

**Issue by paalkr** [loft-sh/vcluster#1499]
### What happened?

I have enabled this `sync.generic.config` in a vcluster in multi namespace mode

```
sync:
  generic:
    role:
      extraRules:
        - apiGroups: ["cert-manager.io"]
          resources: ["issuers", "certificates", "certificaterequests"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
        - apiGroups: ["cert-manager.io"]
          resources: ["clusterissuers"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["acme.cert-manager.io"]
          resources: ["orders"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
    clusterRole:
      extraRules:
        - apiGroups: ["apiextensions.k8s.io"]
          resources: ["customresourcedefinitions"]
          verbs: ["get", "list", "watch"]
    config: |-
      version: v1beta1
      export:
        - apiVersion: cert-manager.io/v1
          kind: Certificate
        - apiVersion: cert-manager.io/v1
          kind: Issuer
      import:
        - kind: Secret
          apiVersion: v1
        - apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
        - apiVersion: acme.cert-manager.io/v1
          kind: Order
        - apiVersion: cert-manager.io/v1
          kind: Certificate
```

Certificate objects created on the host is synced correctly to the virtual cluster, except for the status part of the object. The status is just not available in the imported certificate object.

This is the host namespace, notice the `vcluster.loft.sh/object-name: pktest` label
```
❯ k describe ns vcluster-d9b151e9-2f96135e
Name:         vcluster-d9b151e9-2f96135e
Labels:       kubernetes.io/metadata.name=vcluster-d9b151e9-2f96135e
              pod-security.kubernetes.io/enforce=baseline
              pod-security.kubernetes.io/warn=restricted
              vcluster.loft.sh/label-vcluster-vk8s1-x-vk8s1-x-cf1227b7b2=pktest
              vcluster.loft.sh/managed-by=vcluster-vk8s1-x-vk8s1
              vcluster.loft.sh/vcluster-name=vk8s1
              vcluster.loft.sh/vcluster-namespace=vcluster-vk8s1
Annotations:  policies.kyverno.io/last-applied-patches:
                add-baseline-enforce-restricted-warn.add-psa-labels.kyverno.io: added /metadata/labels/pod-security.kubernetes.io~1warn
              vcluster.loft.sh/object-name: pktest
              vcluster.loft.sh/object-uid: 26209e71-249c-4220-ba1f-eb6bb90e1da6
Status:       Active
```

Into this namespace on the host, I deployed a `testcert2` certificate object. The status present.
```
❯ k get cert -n vcluster-d9b151e9-2f96135e
NAME        READY   SECRET      AGE
testcert2   True    testcert2   2m52s

❯ k describe cert -n vcluster-d9b151e9-2f96135e
Name:         testcert2
Namespace:    vcluster-d9b151e9-2f96135e
Labels:       <none>
Annotations:  vcluster.loft.sh/controlled-by: certificate/cert-manager.io/v1/GenericImport
API Version:  cert-manager.io/v1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2024-01-31T20:47:37Z
  Generation:          1
  Resource Version:    83401906
  UID:                 06dce37b-8c8f-4166-bae8-e634c337dfa8
Spec:
  Dns Names:
    testcert2.vk8s1.test.vcluster.geodata.ek8s1.geopoint.no
  Issuer Ref:
    Group:      cert-manager.io
    Kind:       ClusterIssuer
    Name:       letsencrypt-staging
  Secret Name:  testcert2
Status:
  Conditions:
    Last Transition Time:  2024-01-31T20:47:44Z
    Message:               Certificate is up to date and has not expired
    Observed Generation:   1
    Reason:                Ready
    Status:                True
    Type:                  Ready
  Not After:               2024-04-30T19:47:39Z
  Not Before:              2024-01-31T19:47:40Z
  Renewal Time:            2024-03-31T19:47:39Z
  Revision:                1
Events:
  Type    Reason     Age    From                                       Message
  ----    ------     ----   ----                                       -------
  Normal  Issuing    3m29s  cert-manager-certificates-trigger          Issuing certificate as Secret does not exist
  Normal  Generated  3m28s  cert-manager-certificates-key-manager      Stored new private key in temporary Secret resource "testcert2-2jqcj"
  Normal  Requested  3m28s  cert-manager-certificates-request-manager  Created new CertificateRequest resource "testcert2-grrn4"
  Normal  Issuing    3m22s  cert-manager-certificates-issuing          The certificate has been successfully issued
```

The testcert2 object is correctly imported to the pktest namespace in the vcluster. But the status is not present.
```
❯ k get cert -n pktest
NAME        READY   SECRET      AGE
testcert2           testcert2   5m25s

❯ k describe cert -n pktest
Name:         testcert2
Namespace:    pktest
Labels:       <none>
Annotations:  vcluster.loft.sh/controlled-by: certificate/cert-manager.io/v1/GenericImport
API Version:  cert-manager.io/v1
Kind:         Certificate
Metadata:
  Creation Timestamp:  2024-01-31T20:47:38Z
  Generation:          1
  Resource Version:    1916
  UID:                 9a17da83-21a6-440d-91cc-2925838ac145
Spec:
  Dns Names:
    testcert2.vk8s1.test.vcluster.geodata.ek8s1.geopoint.no
  Issuer Ref:
    Group:      cert-manager.io
    Kind:       ClusterIssuer
    Name:       letsencrypt-staging
  Secret Name:  testcert2
Events:         <none>
```

### What did you expect to happen?

The status of the certificate object should be synced from the host to the virtual cluster.

### How can we reproduce it (as minimally and precisely as possible)?

Create a certificate object in a vcluster namespace on the host.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
v1.28.4-eks-8cb36c9
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
0.19.0-alpha.3. I have observed similar behaviour on version 0.18.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s: v1.28.5+k3s1
```

</details>

### OS and Arch

<details>

```
OS: Amazon Linux 2
Arch: AMD64
```
</details>

**Comment by paalkr** [comment]
I have also tried to add the `patches `option to the import config, but that did not make any difference.

```
      import:
        - apiVersion: cert-manager.io/v1
          kind: Certificate
          patches:
            - op: copyFromObject
              fromPath: status
              path: status
```

**Comment by paalkr** [comment]
Certificate objects created in the virtual cluster is correctly synced (exported) to the host cluster and processed by cert-manager on the host cluster. In this export case the status of the certificate object is present in both the virtual and the host cluster.

So, the problem seems only to apply to the import generic sync, not the export generic sync.

**Comment by ThomasK33** [comment]
Hey @paalkr, thanks for opening this issue. We're taking a look at this.

**Comment by ThomasK33** [comment]
Hey @paalkr, I'm unable to reproduce your issue.

These are the steps I've taken:

1. Deploy a host cluster with Kubernetes version 1.29.

<details>
<summary>eksctl config file</summary>

```yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: "issue-1499"
  region: "eu-central-1"
  version: "1.29"
  tags:
    karpenter.sh/discovery: "issue-1499"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: external-dns
        namespace: external-dns
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        namespace: cert-manager
        name: cert-manager
      wellKnownPolicies:
        certManager: true
    - metadata:
        namespace: kube-system
        name: aws-load-balancer-controller
      wellKnownPolicies:
        awsLoadBalancerController: true

vpc:
  manageSharedNodeSecurityGroupRules: true
  cidr: "172.31.0.0/17"

managedNodeGroups:
  - name: managed-t3a
    instanceType: "t3a.small"
    minSize: 1
    maxSize: 3
    desiredCapacity: 2

karpenter:
  version: "v0.31.3" # Exact version must be provided
  createServiceAccount: true # default is false
  withSpotInterruptionQueue: true # adds all required policies and rules for supporting Spot Interruption Queue, default is false

addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies: # add IAM and service account
      ebsCSIController: true
```
</details>

2. Deployed cert-manager `v1.13.3` onto the host cluster.
3. Configured a ClusterIssuer called `letsencrypt` with a dns01 solver.

<details>
<summary>ClusterIssuer spec</summary>

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: "[redacted]"
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: route53-issuer-account-key
    solvers:
      - selector:
          dnsZones:
            - aws-eng-02.loft.rocks
        dns01:
          route53:
            region: eu-central-1
```
</details>

4. Deployed a vCluster using `vcluster create issue-1499 -f issue-1499.yaml` (cli version 0.19.0-beta.2) with the following values in the `issue-1499.yaml` file:
<details>
  <summary>vCluster values</summary>

```yaml
syncer:
  image: ghcr.io/loft-sh/vcluster:0.19.0-beta.2

multiNamespaceMode:
  enabled: true

sync:
  generic:
    role:
      extraRules:
        - apiGroups: ["cert-manager.io"]
          resources: ["issuers", "certificates", "certificaterequests"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
        - apiGroups: ["cert-manager.io"]
          resources: ["clusterissuers"]
          verbs: ["get", "list", "watch"]
        - apiGroups: ["acme.cert-manager.io"]
          resources: ["orders"]
          verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
    clusterRole:
      extraRules:
        - apiGroups: ["apiextensions.k8s.io"]
          resources: ["customresourcedefinitions"]
          verbs: ["get", "list", "watch"]
    config: |-
      version: v1beta1
      export:
        - apiVersion: cert-manager.io/v1
          kind: Certificate
        - apiVersion: cert-manager.io/v1
          kind: Issuer
      import:
        - kind: Secret
          apiVersion: v1
        - apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
        - apiVersion: acme.cert-manager.io/v1
          kind: Order
        - apiVersion: cert-manager.io/v1
          kind: Certificate
```
</details>

5. Applied a Certificate resource into the vCluster.
<details>
<summary>Certificate resource</summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: issue-1499
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: issue-1499-tls
  namespace: issue-1499
spec:
  secretName: issue-1499-tls
  dnsNames:
    - issue-1499.aws-eng-02.loft.rocks
  commonName: issue-1499.aws-eng-02.loft.rocks
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
```
</details>

After waiting some time, the certificate within the vCluster got updated and now contains the status from the host cluster.

<details>
<summary>Updated Certificate resource</summary>

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"cert-manager.io/v1","kind":"Certificate","metadata":{"annotations":{},"name":"issue-1499-tls","namespace":"issue-1499"},"spec":{"commonName":"issue-1499.aws-eng-02.loft.rocks","dnsNames":["issue-1499.aws-eng-02.loft.rocks"],"issuerRef":{"kind":"ClusterIssuer","name":"letsencrypt"},"secretName":"issue-1499-tls"}}
  creationTimestamp: "2024-02-09T15:09:31Z"
  generation: 2
  name: issue-1499-tls
  namespace: issue-1499
  resourceVersion: "491"
  uid: 5db15e9d-6540-4f12-a93a-f9a161f72b09
spec:
  commonName: issue-1499.aws-eng-02.loft.rocks
  dnsNames:
  - issue-1499.aws-eng-02.loft.rocks
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: issue-1499-tls
status:
  conditions:
  - lastTransitionTime: "2024-02-09T15:18:02Z"
    message: Certificate is up to date and has not expired
    observedGeneration: 2
    reason: Ready
    status: "True"
    type: Ready
  notAfter: "2024-05-09T14:18:01Z"
  notBefore: "2024-02-09T14:18:02Z"
  renewalTime: "2024-04-09T14:18:01Z"
  revision: 1
```
</details>

---

Is there anything in the above steps that's different from your setup?
