### ISSUE TITLE
Network Policies don't work

### ISSUE THREAD

**Issue by fritterhoff** [loft-sh/vcluster#155]
I'm playing around with the vcluster and recognized that network polices don't work. Is this an known bug/not working feature?

I created (only) a simple deployment and a super stupid policy. Executing an `apt update` inside the pod is stil working. Where is my error?
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: container
          image: ubuntu:20.10
          args:
            - sleep
            - "infinity"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: demo-deny
spec:
  podSelector:
    matchLabels:
      app: demo
  policyTypes:
    - Ingress
    - Egress
```
