### ISSUE TITLE
Project `serviceAccountToken` volume `expirationSeconds` is ignored and always produces a token with an expiry of ten years

### ISSUE THREAD

**Issue by strideynet** [loft-sh/vcluster#1579]
### What happened?

When configuring a projected `serviceAccountVolume` volume you are usually able to set an `expirationSeconds` that controls the expiry time of the token e.g 

```yaml
        - name: join-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: join-sa-token
                  # 600 seconds is the minimum that Kubernetes supports. We
                  # recommend this value is used.
                  expirationSeconds: 600
                  # `example.teleport.sh` must be replaced with the name of
                  # your Teleport cluster.
                  audience: example.teleport.sh
````

See https://kubernetes.io/docs/concepts/storage/projected-volumes/#serviceaccounttoken for the Kubernetes side documentation of this.

When inspecting a token produced by this configuration within `vcluster`, we see that instead of producing an expiry of 600 seconds, one of 10 years is produced instead.

This is problematic for two reasons:

- It leaves these tokens vulnerable to long-term use if exfiltrated. If someone has configured some sort of federated trust with the Kubernetes cluster, and these tokens are being validated by another service as an OIDC Identity Token, that service will continue to trust the token for 10 years.
- Some services (e.g Teleport) enforce a limitation that it will only trust tokens with a short expiry (e.g 30 minutes) to mitigate the above risk.

This issue was reported by a customer of ourselves (Teleport) so I have limited details on the actual cluster configuration.

### What did you expect to happen?

The `expirationSeconds` should be respected and used for the service account tokens expiry:

```yaml
        - name: my-token
          projected:
            sources:
              - serviceAccountToken:
                  path: my-token
                  expirationSeconds: 600
                  audience: example.com
````

### How can we reproduce it (as minimally and precisely as possible)?

Add a Projected Service Account token to your PodSpec with a specified `expirationSeconds` and inspect the mounted JWTs expiry.

### Anything else we need to know?

This looks to be caused by a hardcoded value here: https://github.com/loft-sh/vcluster/blob/0c001e9ab6665202a0d8af6a9f67b5a697046685/pkg/controllers/resources/pods/translate/translator.go#L480 - instead the value from the projected volume should be used.

### Host cluster Kubernetes version

<details>

```console
❯ k version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2+k3s1
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```console
❯ v version
vcluster version 0.17.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>
