### ISSUE TITLE
Unable to provision kyverno on vcluster

### ISSUE THREAD

**Issue by L1ghtman2k** [loft-sh/vcluster#1586]
### What happened?

Attempted to provision kyverno on vcluster using helm chart.

Slack Thread: https://loft-sh.slack.com/archives/C01N273CF4P/p1709839247076549 (contains logs for kyverno)

Instead, kyverno is constantly in an unhealthy state causing a lot of errors:
```
{"level":"info","ts":1709864300.967543,"logger":"webhooks.server","caller":"logging/log.go:156","msg":"2024/03/08 02:18:20 http: TLS handshake error from 172.29.88.244:57426: secret \"kyverno-svc.kyverno.svc.kyverno-tls-pair\" not found"}
{"level":"info","ts":1709864307.2370067,"logger":"webhooks.server","caller":"logging/log.go:156","msg":"2024/03/08 02:18:27 http: 
```

(172.29.88.244) refers to node IP

### What did you expect to happen?

Kyverno fails to deploy

### How can we reproduce it (as minimally and precisely as possible)?

values for vcluster:
```
proxy:
  metricsServer:
    nodes:
      enabled: true

hostpathMapper:
  enabled: false

syncer:
  extraArgs:
    - --mount-physical-host-paths=true

sync:
  pods:
    enabled: true
    ephemeralContainers: true
    status: true

  hoststorageclasses:
    enabled: true

  networkpolicies:
    enabled: true

  nodes:
    enabled: true
    syncAllNodes: true
    enableScheduler: true

  priorityclasses:
    enabled: true

  secrets:
    all: true

  configmaps:
    all: true

  persistentvolumes:
    enabled: true

isolation:
  enabled: true
  # We enforce via kyverno
  podSecurityStandard: privileged

  resourceQuota:
    enabled: false

  limitRange:
    enabled: false

  networkPolicy:
    enabled: false
```

kyverno helm chart values. Chart version: 3.1.4
```
admissionController:
    resources:
      limits:
        cpu: 10m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 100Mi
  enabled: true
  priorityClassName: system-cluster-critical
  replicas: 3

features:
  forceFailurePolicyIgnore:
    enabled: true
  logging:
    format: json
    verbosity: 0
  policyExceptions:
    enabled: true
    namespace: kyverno

```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"28", GitVersion:"v1.28.7", GitCommit:"c8dcb00be9961ec36d141d2e4103f85f92bcf291", GitTreeState:"clean", BuildDate:"2024-02-16T11:43:13Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/amd64"}
```

### vlcuster version

helm chart: 0.19.3

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

k3s

### OS and Arch

microk8s amd64
