### ISSUE TITLE
vcluster on OpenShift 4

### ISSUE THREAD

**Issue by tobru** [loft-sh/vcluster#171]
I'd like to get vcluster running on OpenShift and hit the well-known security constraints of OpenShift.

With the following `values.yaml` I got the `vcluster` Pod up and running:

```
volumes:
- name: data
  emptyDir: {}
- name: k3s-config
  emptyDir: {}
- name: kubeconfig
  emptyDir: {}
- name: roothome
  emptyDir: {}
- name: vclusterdata
  emptyDir: {}
vcluster:
  volumeMounts:
  - mountPath: /data
    name: data
  - mountPath: /k3s-config
    name: k3s-config
  - mountPath: /.kube
    name: kubeconfig
syncer:
  volumeMounts:
  - mountPath: /data
    name: data
  - mountPath: /.kube
    name: kubeconfig
  - mountPath: /root
    name: roothome
  - mountPath: /var/lib/vcluster
    name: vclusterdata
```

This solves all the filesystem permission constraints.
It's not perfect (e.g. no persistence), but enough for a PoC to at least get the vcluster Pod running.

The issue I now face is that the CoreDNS Pod which is synced from the vcluster to the host cluster isn't able to start. I get the following message in the syncer container log:

```
E1029 14:47:09.744026       1 controller.go:302] controller-runtime: manager: reconciler group  reconciler kind Pod: controller: pod-forward: name coredns-7448499f4d-rzmd7 namespace kube-system: Reconciler error pods "coredns-7448499f4d-rzmd7-x-kube-system-x-vcluster-1" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.capabilities.add: Invalid value: "NET_BIND_SERVICE": capability may not be added, provider "nonroot": Forbidden: not usable by user or serviceaccount, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "machine-api-termination-handler": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "syn-cluster-backup-etcd": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]
```

That means I have to probably reconfigure the CoreDNS Pod which is started in the vcluster context. Any hints how I can this up and running?
