### ISSUE TITLE
Consider making charts more dynamic via use of tpl

### ISSUE THREAD

**Issue by joaocc** [loft-sh/vcluster#1760]
### Is your feature request related to a problem?

Not a problem but a need and having seen more productivity in other contexts.
Bitnami charts make heavy use of the "tpl" function to allow many/most/all evaluations to be dynamic.
This would also reduce the need to resort to other tools (namely gitops or other ways of evaluating values at deploy time).

### Which solution do you suggest?

Convert the new v0.20.x chart (or on a follow up version) to use tpl when evaluating variables in the various templates.
the bitnami.common chart already includes a "common.tplvalues.render" template/function.

### Which alternative solutions exist?

Using combinations of gitops, external tools (ansible, bash), or variables in tools like vcluster or other TACOS. All of them increase complexity, even for simple/trivial scenarios.

### Additional context

Examples on no particular order:
* https://github.com/bitnami/charts/blob/main/bitnami/zookeeper/templates/statefulset.yaml#L15
* https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/admin-ingress.yaml#L31
* https://github.com/kubernetes/dashboard/blob/main/charts/kubernetes-dashboard/templates/security/pdb.yaml#L22
* https://github.com/seaweedfs/seaweedfs/blob/master/k8s/charts/seaweedfs/templates/master-statefulset.yaml#L226

**Comment by rohantmp** [comment]
Could you provide specific examples of which values could be automatically determined that aren't already? You'll see a few `.tpl` files already here:  https://github.com/loft-sh/vcluster/tree/main/chart/templates

**Comment by joaocc** [comment]
Hi. Didn't explain myself correctly. These values are indeed determined dynamically in the sense that they are conditionally assessed at template generation time. However, all referenced values are values defined statically in values.yaml.

It is not possible, for instance, to define "global.myname: abc" and then refer to abc in the name of the persistence volume (ex: path in NFS) and in the ingress name, without repeating the "abc" string in the different places.
With common.tplvalues.render (or tpl) when evaluating the persistence volume var, and on ingress name, we can reference to global.myname in the values.yaml, making values.yaml more dynamic/DRY.

**Comment by joaocc** [comment]
Forgot to add an example to illustrate (different domain, but same concept)
```
global:
  myname: example.com

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      URL: {{ printf "http://%s:%d" .Values.global.myname 80 | quote }}
    - name: https
      port: 443
      targetPort: https
      URL: {{ printf "https://%s:%d" .Values.global.myname 443 | quote }}

```

**Comment by garryod** [comment]
I've just come across the need for this with the `.Values.controlPlane.ingress.spec` field. Where I would like to use it as such:
**values.yaml**
```yaml
vcluster:
  controlPlane:
    ingress:
      spec:
        tls:
          - secretName: '{{ include "common.names.fullname" $ }}-ingress-tls'
```
Where if `spec` in `templates/ingress.yaml` used the following, it would be evaluated at render time:
```yaml
spec:
  {{- if .Values.controlPlane.ingress.spec }}
  {{- tpl (toYaml .Values.controlPlane.ingress.spec) | indent 2 }}
  {{- end }}
```
Happy to throw in a PR for your consideration
