### ISSUE TITLE
Vcluster is not picking up the configs defined in my `vcluster.yaml` 

### ISSUE THREAD

**Issue by MichaelKora** [loft-sh/vcluster#1772]
### What happened?

i am new to vclsuter and am having trouble gettning it production ready. i was able to deploy the vcluster to my cluster and access it to using vcluster. but it is not working as expected.

### What did you expect to happen?

here is my vcluster.yaml file..i deploy it using helm

```
exportKubeConfig:
  context: "vcluster-context1"
controlPlane:
  distro:
    k3s:
      enabled: true

  coredns:
    enabled: true
    deployment:
      replicas: 3
      nodeSelector:
        kubernetes.io/hostname: "my-node-name"
  statefulSet:
    persistence:
      volumeClaim:
        enabled: true
        size: 3Gi
        storageClass: "my-sc"
    scheduling:
      nodeSelector:
        kubernetes.io/hostname: "my-node-name"
```

i except it to deploy it in the given node and i expect 3 replicas of the coredns pod..but none of this is working.

Another issue is exporting the config file...is it possible to have the config file generated so that it con be used to connect to the vcluster without accessing the host cluster? for now `vcluster connect` shows that it is using port forwarding to access the cluster..i would like to have the kube config file so i can share it without allowing the users to access the host cluster

### How can we reproduce it (as minimally and precisely as possible)?

using the providing vcluster.yaml file and applying it using helm

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.11
```

</details>

### Host cluster Kubernetes distribution

<details>

```
k3s (with talos -bare metal cluster-)```

</details>


### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.19.5
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: talos
Arch: metal-amd64
```
</details>
