### ISSUE TITLE
Configure topologySpreadConstraints for coredns using values file

### ISSUE THREAD

**Issue by tamasborsstriva** [loft-sh/vcluster#1834]
### Is your feature request related to a problem?

The topologySpreadConstraints for coredns only checks for `hostname` only, therefore all three pods can be in the same region.

```
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
    matchLabels:
    k8s-app: kube-dns
```

### Which solution do you suggest?

Allow topologySpreadConstraints to be configurable from the config.yaml file, therefore additional `topologyKey`s can be used, for example: `"topologyKey": "topology.kubernetes.io/zone"`

### Which alternative solutions exist?

patch the deployment manually after deployed, add this:

`- labelSelector:
          matchLabels:
            k8s-app: kube-dns
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule`
