### ISSUE TITLE
Virtual Node in NodeNotReady  State

### ISSUE THREAD

**Issue by L1ghtman2k** [loft-sh/vcluster#1866]
### What happened?

When describing a node, I receive the following events for the virtual node:

```
Events:
  Type    Reason        Age                    From             Message
  ----    ------        ----                   ----             -------
  Normal  NodeNotReady  3m14s (x562 over 13h)  node-controller  Node onprem-node69.hstlabs.glcp.hpecorp.net status is now: NodeNotReady
```

### What did you expect to happen?

Node is in a healthy state

### How can we reproduce it (as minimally and precisely as possible)?

values file used:

```
USER-SUPPLIED VALUES:
api:
  extraArgs:
  - --service-node-port-range=80-32767
  image: registry.k8s.io/kube-apiserver:v1.28.7
controller:
  image: registry.k8s.io/kube-controller-manager:v1.28.7
isolation:
  enabled: true
  limitRange:
    enabled: false
  networkPolicy:
    enabled: false
  podSecurityStandard: privileged
  resourceQuota:
    enabled: false
scheduler:
  image: registry.k8s.io/kube-scheduler:v1.28.7
sync:
  configmaps:
    all: true
  hoststorageclasses:
    enabled: true
  networkpolicies:
    enabled: true
  nodes:
    enableScheduler: true
    enabled: true
    syncAllNodes: true
  persistentvolumes:
    enabled: false
  pods:
    enabled: true
    ephemeralContainers: true
    status: true
  priorityclasses:
    enabled: true
  secrets:
    all: true
syncer:
  extraArgs:
  - --mount-physical-host-paths=true
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 0
      memory: 0
```

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

```console
$ kubectl version
Client Version: v1.28.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7
```

</details>

### Host cluster Kubernetes distribution

<details>

```
MicroK8s
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
Client Version: v1.28.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7
```

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

```
k8s
```

### OS and Arch

```
OS: Ubuntu
Arch: x86_64
```
