### ISSUE TITLE
[feature request] Allow importing of cluster-scoped resources using genericSync without multiNamespaceMode enabled

### ISSUE THREAD

**Issue by mtougeron** [loft-sh/vcluster#1907]
### Is your feature request related to a problem?

no

### Which solution do you suggest?

It would be nice to be able to import additional cluster-scoped resources such as PriorityClasses or ClusterRole(Binding)s into the vcluster using genericSync without having to enabled multiNamespaceMode.

Specifically for PriorityClasses, it would be nice to either allow importing though the experimental genericSync options or to enable it as a feature similar to the fromHost like is done for StorageClasses or CSI drivers.

For ClusterRole(Binding)s I would think it would have to happen through the genericSync options (assuming there's a label selector available).

Example desired Helm values file:

```yaml
experimental:
  genericSync:
    import:
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        selector:
          matchLabels:
            sync-to-vcluster: "true"
      - apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        selector:
          matchLabels:
            sync-to-vcluster: "true"
      - apiVersion: scheduling.k8s.io/v1
        kind: PriorityClass
```

### Which alternative solutions exist?

A custom plugin could be written to do this. 

### Additional context

In our clusters we don't give tenants the elevated RBAC to create PriorityClasses so we cannot allow the vcluster to sync PriorityClasses on the host cluster. This means that when someone tries to create a Pod with a priority class that they expect from the host cluster it doesn't exist on the vcluster.

edit: adjusted the example for clarity
