### ISSUE TITLE
[bug] k8s OIDC auth doesn't consistently work when running in high availability mode with 0.20.0-beta.11

### ISSUE THREAD

**Issue by mtougeron** [loft-sh/vcluster#1910]
### What happened?

When configuring vcluster 0.20.0-beta.11 to run in high availability mode with 3 replicas and using OIDC authentication with Azure AD for Kubernetes. The kubectl requests intermittently respond with

```
Error from server (Forbidden): pods is forbidden: User "https://sts.windows.net/REDACTED/#REDACTED" cannot list resource "pods" in API group "" in the namespace "kube-system"
```

As near as I can tell, this happens whenever the request is routed to the last pod in the statefulset (in this case, ending in `-2`). I've tried `kubectl port-forward pod/touge-test-0 8443:8443` (and -1 and -2) and it only fails on the -2 across multiple recreation attempts. I don't know if that's a coincidence or an indication of where the problem is.

### What did you expect to happen?

I would expect the OIDC authentication to consistently work.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create an Azure AD tenant
2. Configure the vcluster yaml to use the Azure AD tenant for authentication with OIDC
3. Create the vcluster
4. Apply a ClusterRoleBinding giving a user from Azure AD access to the vcluster
5. Create a kubeconfig that uses [kubelogin](https://github.com/Azure/kubelogin) to connect & authenticate to the vcluster (example below)
6. Run kubectl commands against the vcluster

### Anything else we need to know?

kubeconfig example

```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true # using this flag since it's easier than frequently updating it during the testing
    server: https://localhost:8443
  name: touge-test
contexts:
- context:
    cluster: touge-test
    namespace: kube-system
    user: azuread
  name: touge-test
current-context: touge-test
kind: Config
preferences: {}
users:
- name: azuread
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - get-token
      - --login
      - devicecode
      - --server-id
      - REDACTED
      - --client-id
      - REDACTED
      - --tenant-id
      - REDACTED
      - --environment
      - AzurePublicCloud
      command: kubelogin
      env: null
      installHint: |2
 
        kubelogin is not installed which is required to connect to AAD enabled cluster.
 
        To learn more, please go to https://azure.github.io/kubelogin/
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

</details>

Assuming the vcluster is called `touge-test`, you can port

```sh
kubectl port-forward service/touge-test 8443:443
```

or

```sh
kubectl port-forward pod/touge-test-0 8443:8443
```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2
```

### vcluster version

```console
$ vcluster --version
# paste output here
```

</details>

### VCluster Config

<details>

```yaml
sync:
  toHost:
    storageClasses:
      enabled: false
  fromHost:
    csiDrivers:
      enabled: true
    csiStorageCapacities:
      enabled: true
    storageClasses:
      enabled: true

controlPlane:
  statefulSet:
    image:
      repository: ghcr.io/loft-sh/vcluster-oss
    highAvailability:
      replicas: 3
  distro:
    k8s:
      enabled: true
      apiServer:
        image:
          tag: v1.30.2
        extraArgs:
        - --oidc-client-id=spn:REDACTED
        - --oidc-groups-claim=groups
        - --oidc-issuer-url=https://sts.windows.net/REDACTED/
        - --oidc-username-claim=oid
      controllerManager:
        image:
          tag: v1.30.2
      scheduler:
        image:
          tag: v1.30.2
  backingStore:
    database:
      embedded:
        enabled: true

  proxy:
    extraSANs:
      - "localhost" # so port-forwarding works
      - "127.0.0.1" # so port-forwarding works

experimental:
  deploy:
    vcluster:
      manifests: |
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: azure-ad-cluster-admin
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: cluster-admin
        subjects:
        - apiGroup: rbac.authorization.k8s.io
          kind: Group
          name: REDACTED
```

**Comment by mtougeron** [comment]
FYI, fwiw, I was playing around with the k8s provider using external etcd (3 replicas) and I was not able to reproduce it with that configuration. Other than the change to use external etcd, the vcluster configuration was the same.

**Comment by rmweir** [comment]
@mtougeron that vcluster yaml doesn't look like it has HA enabled. It would help if you could answer a few questions:
* Did you enable HA throught the HA toggle button in the UI?
* Did you enable HA after creating the cluster?
* What did your final vcluster yaml look like?

**Comment by mtougeron** [comment]
@rmweir updated. All that was changed was adding the 

```yaml
controlPlane:
  statefulSet:
    highAvailability:
      replicas: 3
```

To specifically answer your questions,

> Did you enable HA throught the HA toggle button in the UI?

no, I did everything with helm.

```sh
helm upgrade --install touge-test vcluster --version 0.20.0-beta.11 --repo https://charts.loft.sh -f bugreport.yaml --repository-config=''
```
> Did you enable HA after creating the cluster?

no, this happens on a clean install.

> What did your final vcluster yaml look like?

updated with original post with the proper yaml

**Comment by rmweir** [comment]
@mtougeron is there a reason why under `controlPlane` you did not add:
```yaml
backingStore:
    etcd:
      deploy:
        statefulSet:
          highAvailability:
            replicas: 3
```
the platform UI as well as the [vCluster docs for HA](https://www.vcluster.com/docs/vcluster/deploy/topologies/high-availability#create-the-ha-virtual-cluster) include this.

**Comment by rmweir** [comment]
Thank you @mtougeron, I was able to reproduce. I'm investigating further but I have found that embedded etcd works, just not embedded sqlite which is the default when using `database`. If you need a work around or want to test it yourself you can try swapping
```yaml
backingStore:
    database:
      embedded:
        enabled: true
```
for
```yaml
backingStore:
    etcd:
      embedded:
        enabled: true
```
