### ISSUE TITLE
Vcluster deletion using cli is not working as expected with VCluster argocd application

### ISSUE THREAD

**Issue by adamissaoui** [loft-sh/vcluster#1917]
### What happened?

when creating vcluster using cli, the deletion works fine however when creating the vcluster using argocd application the deletion is not works.

only if i delete the argocd application the vcluster got deleted.

### What did you expect to happen?

The vcluster delete should delete any vcluster that can be listed through cli 

### How can we reproduce it (as minimally and precisely as possible)?

1. create vcluster using argocd application :

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vc-1
  namespace: argocd
spec:
  project: vcluster
  destination:
    server: https://kubernetes.default.svc/
    namespace: vcluster-vc-1
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    path: ''
    repoURL: 'https://charts.loft.sh/'
    targetRevision: 0.19.6
    chart: vcluster
```

2.  vcluster list should return the vcluster vc-1 :

`vcluster list | grep vc-1`

Output :

 vc-1 | arn:aws:eks:us-east-1:123456789:cluster/VCLUSTER | vcluster-vc-1 | Running | 0.19.6  |           |  2024-07-09 10:39:54 +0100 IST |  24h57m51s | OSS  
 
 
 3. try to use vcluster using : ` vcluster delete vc-1 --debug  `
 
               
```
20:55:17 debug Error creating pro client: couldn't find vCluster.Pro config: please make sure to run 'vcluster login' to connect to an existing instance or 'vcluster pro start' to deploy a new instance
20:55:18 info Delete vcluster vc-1...
20:55:19 debug Delete helm chart with helm delete vc-1 --namespace vcluster-vc-1 --kubeconfig /var/folders/t7/x7xdvdh90ms9_rcynjbh00rr0000gs/T/2513715556 --repository-config=''
20:55:20 fatal release 'vc-1' was not found in namespace 'vcluster-vc-1'
```

 

### Host cluster Kubernetes version

<details>

```console
$ kubectl version

kubectl version
Client Version: v1.28.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b

```

</details>

### vcluster version

<details>

```console
$ vcluster --version
 vcluster version 0.19.5
```

</details>

### VCluster Config

<details>

```
# My vcluster.yaml / values.yaml here
```

</details>
