### ISSUE TITLE
Fails to configure dual-stack properly in a k0s virtual cluster

### ISSUE THREAD

**Issue by ananace** [loft-sh/vcluster#1929]
### What happened?

Was setting up a new K0s cluster with minimal configuration for testing usage for an external user, using the 0.21 alpha. (and also occuring on the 0.20 pre-releases)
The cluster failed first startup, then came up properly on the next attempt, though the the log is continuously filled with errors like;
```
2024-07-15 11:22:13     ERROR   controller/controller.go:324    Reconciler error        {"component": "vcluster", "controller": "service", "namespace": "default", "name": "kubernetes", "reconcileID": "112bd4a6-166e-4eaa-ae32-d725cc571f5d", "error": "Service \"kubernetes\" is invalid: spec.ipFamilies[1]: Invalid value: \"IPv6\": not configured on this cluster"}
```

<details>
<summary>The generated k0s config in the container</summary>

```yaml
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    port: 6443
    k0sApiPort: 9443
    extraArgs:
      bind-address: 127.0.0.1
      enable-admission-plugins: NodeRestriction
      endpoint-reconciler-type: none
  network:
    # Will be replaced automatically by the syncer container on first startup
    serviceCIDR: 10.64.0.0/16
    provider: custom
    clusterDomain: cluster.local
  controllerManager:
    extraArgs:
      controllers: '*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle,-ttl'
```

</details>

The configuration seems to lack the necessary parameters to enable dual-stack support  - i.e. it's lacking the `spec.network.dualStack` block

### What did you expect to happen?

The cluster has dual-stack configured similarly to the host cluster.

### How can we reproduce it (as minimally and precisely as possible)?

Set up a dual-stack Kubernetes cluster, create a new virtual k0s cluster inside it.

### Anything else we need to know?

Attaching a custom config template with the necessary dual stack parameters set works as expected

<details>
<summary>Example configuration snippet</summary>

```yaml
controlPlane:
  distro:
    k0s:
      config: |
        apiVersion: k0s.k0sproject.io/v1beta1
        kind: Cluster
        metadata:
          name: k0s
        spec:
          api:
            port: 6443
            k0sApiPort: 9443
            extraArgs:
              bind-address: 127.0.0.1
              enable-admission-plugins: NodeRestriction
              endpoint-reconciler-type: none
          network:
            serviceCIDR: 10.64.0.0/16
            provider: custom
            clusterDomain: cluster.local
            dualStack:
              enabled: true
              IPv6podCIDR: fd03:2b4f:588e::/64
              IPv6serviceCIDR: fd03:2b4f:588e:1::/108
          controllerManager:
            extraArgs:
              controllers: '*,-nodeipam,-nodelifecycle,-persistentvolume-binder,-attachdetach,-persistentvolume-expander,-cloud-node-lifecycle,-ttl'
```

</details>

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Server Version: v1.26.13
```

</details>

### vcluster version

<details>

No `vcluster` calls involved in the creation or log reading, only helm and kubectl

</details>

### VCluster Config

<details>

```
controlPlane:
  distro:
    k0s:
      enabled: true
  service:
    spec:
      allocateLoadBalancerNodePorts: false
      externalTrafficPolicy: Local
      ipFamilyPolicy: PreferDualStack
      type: LoadBalancer
```

</details>
