### ISSUE TITLE
fluent bit running inside a vcluster can collect logs from pods deployed in the host and other vclusters.

### ISSUE THREAD

**Issue by vicaya** [loft-sh/vcluster#1989]
### What happened?

I was trying out the new relic k8s bundle inside a virtual cluster following the observability documentation. To my surprise the collected logs contains logs from pods in the host and other vclusters. It collected name/namespace/status of all the pods in the host cluster and other vclusters as well.

### What did you expect to happen?

Any monitoring tools deployed inside a vcluster should only see metrics and logs generated by the pods in the vcluster only.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a vcluster with values from the docs for observability: syncAllNodes etc (see the included vcluster config values).
2. Deploy the vcluster-hpm helm chart in the vcluster namespace (vcluster-test0 with --set VclusterReleaseName=test0)
3. Deploy of a new relic helm chart (really easy to follow).

### Anything else we need to know?

If this is a known bug, what's the timeline to fix this rather annoying security issue?

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.5+k3s1
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
# paste output here
vcluster version 0.19.6
```

</details>

### VCluster Config

<details>

```
# My vcluster.yaml / values.yaml here (from helm get value <vcluster> ...)
proxy:
  metricsServer:
    nodes:
      enabled: true
    pods:
      enabled: true
serviceCIDR: 10.43.0.0/16
sync:
  nodes:
    enabled: true
    syncAllNodes: true
syncer:
  extraArgs:
  - --tls-san=test0.internal
  - --mount-physical-host-paths=true
vcluster:
  image: rancher/k3s:v1.29.0-k3s1
```

</details>
