### ISSUE TITLE
Value of ephemeral container property targetContainerName not present on host

### ISSUE THREAD

**Issue by dee0sap** [loft-sh/vcluster#2073]
### What happened?

We have enabled ephemeral container syncing
```
sync:
  pods:
    enabled: true 
    ephemeralContainers: true

```
Within our vcluster we have set values for `.spec.ephemeralContainers[].targetContainerName` however when we examine the pods that syncing created on the host targetContainerName is unset.

See example yaml in attached zip.
[pod-target-has-multiple-mounts0-redacted.zip](https://github.com/user-attachments/files/16628188/pod-target-has-multiple-mounts0-redacted.zip)

### What did you expect to happen?

I expect the pod on the host to have the same targetContainerName value as the pod in the vcluster.

### How can we reproduce it (as minimally and precisely as possible)?

- Enable syncing as above 
- Use 'kubectl debug' with the '--target' option 

### Anything else we need to know?

Not sure if it is related, but will mention for completeness' sake.

kubectl debug creates ephemeral containers via PATCH.   I have code that is doing this programmatically and I found that rapidly PATCHing in effort to add a pair of ephemeral containers causes the pods on the host and the vcluster to get out of sync and/or corrupted.    Generally 'out of sync' would look like 
- ephemeral container missing from host 
- resource version data suggesting that syncer things the objects are in sync when they are not 
Corruption would look like 
- Possibly an ephemeral container missing from the pod on the host 
- On host ephemeralContainerStatuses show that the ephemeral containers all using same image when they should have been using different ones

### Host cluster Kubernetes version

<details>

```console
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.19.6

```

</details>

### VCluster Config

<details>

```
sync:
  priorityclasses:
    enabled: true
  pods:
    enabled: true 
    ephemeralContainers: true
syncer:
  extraArgs:
  - --tls-san=XXXX
init:    
  manifests: |-
   # A priority class definition 
    ---
   # A secret for docker image pull

```

Above is the config.  Note that I redacted a few things.

</details>
