### ISSUE TITLE
The tls certificate issued in 0.20.0 is not valid for `controlPlane.ingress.host`

### ISSUE THREAD

**Issue by felipecrs** [loft-sh/vcluster#2086]
### What happened?

Issue is simple. The certificate generated for kubernetes after 0.20.0 no longer is valid for `controlPlane.ingress.host`.

### What did you expect to happen?

To work as before.

### How can we reproduce it (as minimally and precisely as possible)?

I can reproduce it consistently. Let me know if you need help to reproduce it.

### Anything else we need to know?

The workaround is to specify extraSans:

```yaml
controlPlane:
  ingress:
    enabled: true
    host: my-host.com

  # previously this was not required
  proxy:
    extraSANs:
      - my-host.com
```

### Host cluster Kubernetes version

1.27.16

### vcluster version

0.20.0

### VCluster Config

Check above.
