### ISSUE TITLE
Cronjob with time zone

### ISSUE THREAD

**Issue by andrea-pavan** [loft-sh/vcluster#2104]
### What happened?

It's not possible to create a Cronjob with time zone defined in vcluster.
When try to submit the manifest, you receive the error:
```
The CronJob "xyz" is invalid: spec.timeZone: Invalid value: "XXX/YYY" unknown time zone XXX/YYY
```

### What did you expect to happen?

Able to create Cronjob.
Presence of `timezone` file where Kubernetes looks for time zones info.

### How can we reproduce it (as minimally and precisely as possible)?

Create a fresh vcluster.
Try to schedule this CronJob

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  timeZone: Europe/Rome
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

### Anything else we need to know?

The same issue was present in older version of k3s.
They solved by adding `tzdata` package in their Alpine-based Docker images.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.0+k3s1
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.19.7
```

</details>

### VCluster Config

<details>

Default config

</details>
