### ISSUE TITLE
KUBECONFIG reference not switching back to initial value after vcluster disconnect

### ISSUE THREAD

**Issue by iomarcovalente** [loft-sh/vcluster#2225]
### What happened?

When using vcluster connect the `KUBECONFIG` env var value changes to the temporary vcluster kube config. Once we disconnect it doesn't revert bach to what it was. That could mean that the docs instruction would also fail: https://vcluster.com/docs/vcluster?x0=3&x1=2&x2=1#view-resources-inside-the-host-cluster

### What did you expect to happen?

I would expect `KUBECONFIG` to go back to the original value

### How can we reproduce it (as minimally and precisely as possible)?

run the following:
```
ζ echo $KUBECONFIG                                                                                                                                                                           

```
note how `KUBECONFIG` is empty.
Then run:
```
ζ vcluster --context ${CONTEXT} connect ${VC_USER}-vcluster -n ${VC_NAMESPACE} --server=https://${VC_DOMAIN} --service-account ${VC_USER} --cluster-role cluster-admin -- zsh
```
and then:
```
ζ echo $KUBECONFIG
```
note that the response is the below:
```
/var/folders/c0/ycb8260d39l3k5gd1gk3w7w00000gp/T/2799991471
```
and if we run the following:
```
ζ kubectl get po --all-namespaces                                                                                                                                                            
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-5b6697b4f4-gsgz4   1/1     Running   0          31m
ζ vcluster disconnect                                                                                                                                                                        
14:17:06 info Successfully disconnected and switched back to the original context: main_us-west-2
ζ kubectl get po --all-namespaces                                                                                                                                                            
Error in configuration: context was not found for specified context: nbcu-aws_cpeng_main_us-west-2_mgmt
```
we get error "context was not found"
That is because:
```
ζ echo $KUBECONFIG                                                                                                                                                                           
/var/folders/c0/ycb8260d39l3k5gd1gk3w7w00000gp/T/2799991471
```
`KUBECONFIG` was not reverted

### Anything else we need to know?

at least you should  
`unset KUBECONFIG`
when `vcluster disconnect` is ran

### Host cluster Kubernetes version

<details>

```
ζ kubectl version                                                                                                                                                                            
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.8-eks-a737599
```

</details>

### vcluster version

<details>

```console
ζ vcluster --version                                                                                                                                                                         
vcluster version 0.21.0-beta.2
```

</details>

### VCluster Config

<details>

```
controlPlane:
  proxy:
    extraSANs:
    - ${VC_DOMAIN}
  distro:
    k8s:
      enabled: true
  backingStore:
    database:
      embedded:
        enabled: true
  statefulSet:
    highAvailability:
      replicas: 1
    security:
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 63000
        fsGroup: 63000
      containerSecurityContext:
        runAsNonRoot: true
        runAsUser: 63000
        runAsGroup: 63000
  service:
    annotations:
      projectcontour.io/upstream-protocol.tls: "443"
sync:
  toHost:
    pods:
      enabled: true
    serviceAccounts:
      enabled: true
  fromHost:
    events:
      enabled: true

exportKubeConfig:
  context: vcluster-cpeng-mgmt-main
  server: https://${VC_DOMAIN}
  secret:
    name: vcluster-kubeconfig
```

</details>
