### ISSUE TITLE
expose ca data, certificate and key along kubeconfig

### ISSUE THREAD

**Issue by janwillies** [loft-sh/vcluster#226]
When creating a `vcluster` there's a Kubernetes Secret created which holds the information to connect to the vcluster. The single key of the secret is `config` and the value is an encoded [kubeconfig](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/), which is by default consumable by many clients (kubectl, crossplane provider-helm, provider-kubernetes, ...).

Some clients however are not able to consume a `kubeconfig` file, but rather use dedicated parameters to setup the connection (e.g. https://github.com/argoproj/argo-cd/issues/4651)

It would be great if `vcluster` would expose the connectivity information as top level keys in the Kubernetes Secret:
 
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: vcluster-1
data:
  certificate-authority-data: LS0tL...
  client-certificate-data: LS0tL...
  client-key-data: LS0tL...
  config: YXBpVm...
```
