### ISSUE TITLE
vcluster 0.21.1 crashloops when syncing of network policy is enabled, but feature is not

### ISSUE THREAD

**Issue by everflux** [loft-sh/vcluster#2307]
### What happened?

I tried to setup a fresh vcluster v0.21.1 with a config that worked with a previous version. I use talos as base distribution. The vcluster pod is crashlooping.

### What did you expect to happen?

vcluster is running

### How can we reproduce it (as minimally and precisely as possible)?

I am not sure, I guess network policy is not working.

### Anything else we need to know?

Logfile from a vcluster pod

```
2024-12-03 08:31:14	INFO	controller/controller.go:175	Starting EventSource	{"component": "vcluster", "controller": "event", "source": "kind source: *v1.Event"}
2024-12-03 08:31:14	INFO	controller/controller.go:175	Starting EventSource	{"component": "vcluster", "controller": "event", "source": "kind source: *v1.Event"}
2024-12-03 08:31:14	INFO	controller/controller.go:183	Starting Controller	{"component": "vcluster", "controller": "event"}
2024-12-03 08:31:14	INFO	controller/controller.go:183	Starting Controller	{"component": "vcluster", "controller": "ingressclass"}
2024-12-03 08:31:14	INFO	controller/controller.go:217	Starting workers	{"component": "vcluster", "controller": "ingressclass", "worker count": 10}
2024-12-03 08:31:14	INFO	controller/controller.go:132	Starting EventSource	{"component": "vcluster", "controller": "ingressclass", "source": "kind source: *v1.IngressClass"}
2024-12-03 08:31:14	INFO	controller/controller.go:175	Starting EventSource	{"component": "vcluster", "controller": "ingress", "source": "kind source: *v1.Ingress"}
2024-12-03 08:31:14	INFO	controller/controller.go:132	Starting EventSource	{"component": "vcluster", "controller": "ingressclass", "source": "kind source: *v1.IngressClass"}
2024-12-03 08:31:14	INFO	controller/controller.go:175	Starting EventSource	{"component": "vcluster", "controller": "ingress", "source": "kind source: *v1.Ingress"}
2024-12-03 08:31:14	INFO	controller/controller.go:183	Starting Controller	{"component": "vcluster", "controller": "ingress"}
2024-12-03 08:31:14	ERROR	cmd/root.go:50	error	{"component": "vcluster", "error": "start controllers: start controllers: start networkpolicy syncer: start object cache: mapper for gvk networking.k8s.io/v1, Kind=NetworkPolicy couldn't be found"}
```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.2

```

</details>

### vcluster version

<details>

```console
$ vcluster --version
# I use a helm chart: 
install.go:224: 2024-12-03 09:27:36.243797792 +0100 CET m=+0.055086465 [debug] Original chart version: "v0.21.1"


```

</details>

### VCluster Config

<details>

```
controlPlane:
  advanced:
    defaultImageRegistry: ""
    globalMetadata:
      annotations: {}
    headlessService:
      annotations: {}
      labels: {}
    serviceAccount:
      annotations: {}
      enabled: true
      imagePullSecrets: []
      labels: {}
      name: ""
    virtualScheduler:
      enabled: false
    workloadServiceAccount:
      annotations: {}
      enabled: true
      imagePullSecrets: []
      labels: {}
      name: ""
  backingStore:
    database:
      embedded:
        enabled: true
      external:
        caFile: ""
        certFile: ""
        connector: ""
        dataSource: ""
        enabled: false
        keyFile: ""
    etcd:
      deploy:
        enabled: false
        headlessService:
          annotations: {}
          enabled: false
        service:
          annotations: {}
          enabled: false
        statefulSet:
          annotations: {}
          enableServiceLinks: true
          enabled: true
          env: []
          extraArgs: []
          highAvailability:
            replicas: 1
          image:
            registry: registry.k8s.io
            repository: etcd
            tag: 3.5.13-0
          imagePullPolicy: ""
          labels: {}
          persistence:
            addVolumeMounts: []
            addVolumes: []
            volumeClaim:
              accessModes:
              - ReadWriteOnce
              enabled: true
              retentionPolicy: Retain
              size: 5Gi
              storageClass: ""
            volumeClaimTemplates: []
          pods:
            annotations: {}
            labels: {}
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
          scheduling:
            affinity: {}
            nodeSelector: {}
            podManagementPolicy: Parallel
            priorityClassName: ""
            tolerations: []
            topologySpreadConstraints: []
          security:
            containerSecurityContext: {}
            podSecurityContext: {}
      embedded:
        enabled: false
        migrateFromDeployedEtcd: false
  coredns:
    deployment:
      affinity: {}
      annotations: {}
      image: ""
      labels: {}
      nodeSelector: {}
      pods:
        annotations: {}
        labels: {}
      replicas: 1
      resources:
        limits:
          cpu: 500m
          memory: 170Mi
        requests:
          cpu: 20m
          memory: 64Mi
      tolerations: []
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            k8s-app: kube-dns
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
    embedded: false
    enabled: true
    overwriteConfig: ""
    overwriteManifests: ""
    priorityClassName: ""
    service:
      annotations: {}
      labels: {}
      spec:
        type: ClusterIP
  distro:
    k0s:
      command: []
      config: ""
      enabled: false
      extraArgs: []
      image:
        registry: ""
        repository: k0sproject/k0s
        tag: v1.30.2-k0s.0
      imagePullPolicy: ""
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 40m
          memory: 64Mi
      securityContext: {}
    k3s:
      command: []
      enabled: true
      extraArgs: []
      image:
        registry: ""
        repository: rancher/k3s
        tag: v1.30.6-k3s1
      imagePullPolicy: ""
      resources:
        limits:
          cpu: 1000m
          memory: 320Mi
        requests:
          cpu: 100m
          memory: 64Mi
      securityContext: {}
    k8s:
      apiServer:
        command: []
        enabled: true
        extraArgs: []
        image:
          registry: registry.k8s.io
          repository: registry.k8s.io/kube-apiserver
          tag: v1.30.2
        imagePullPolicy: ""
      controllerManager:
        command: []
        enabled: true
        extraArgs: []
        image:
          registry: registry.k8s.io
          repository: kube-controller-manager
          tag: v1.30.2
        imagePullPolicy: ""
      enabled: false
      env: []
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 40m
          memory: 64Mi
      scheduler:
        command: []
        extraArgs: []
        image:
          registry: registry.k8s.io
          repository: kube-scheduler
          tag: v1.30.2
        imagePullPolicy: ""
      securityContext: {}
      version: ""
  hostPathMapper:
    enabled: true
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    enabled: false
    host: my-host.com
    labels: {}
    pathType: ImplementationSpecific
    spec:
      tls: []
  proxy:
    bindAddress: 0.0.0.0
    extraSANs:
    - student01.t9v.de
    - student01.student01-vcluster
    port: 8443
  service:
    annotations: {}
    enabled: true
    httpsNodePort: 0
    kubeletNodePort: 0
    labels: {}
    spec:
      type: ClusterIP
  serviceMonitor:
    annotations: {}
    enabled: false
    labels: {}
  statefulSet:
    annotations: {}
    args: []
    command: []
    enableServiceLinks: true
    env: []
    highAvailability:
      leaseDuration: 70
      renewDeadline: 45
      replicas: 1
      retryPeriod: 10
    image:
      registry: ghcr.io
      repository: loft-sh/vcluster-pro
      tag: ""
    imagePullPolicy: ""
    labels: {}
    persistence:
      addVolumeMounts: []
      addVolumes: []
      binariesVolume:
      - emptyDir: {}
        name: binaries
      dataVolume: []
      volumeClaim:
        accessModes:
        - ReadWriteOnce
        enabled: auto
        retentionPolicy: Retain
        size: 5Gi
        storageClass: local-path
      volumeClaimTemplates: []
    pods:
      annotations: {}
      labels: {}
    probes:
      livenessProbe:
        enabled: true
      readinessProbe:
        enabled: true
      startupProbe:
        enabled: true
    resources:
      limits:
        cpu: 2000m
        ephemeral-storage: 8Gi
        memory: 2Gi
      requests:
        cpu: 200m
        ephemeral-storage: 200Mi
        memory: 256Mi
    scheduling:
      affinity: {}
      nodeSelector: {}
      podManagementPolicy: Parallel
      priorityClassName: ""
      tolerations: []
      topologySpreadConstraints: []
    security:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsGroup: 0
        runAsUser: 0
      podSecurityContext: {}
    workingDir: ""
experimental:
  deploy:
    host:
      manifests: ""
      manifestsTemplate: ""
    vcluster:
      helm: []
      manifests: ""
      manifestsTemplate: ""
  genericSync:
    clusterRole:
      extraRules: []
    role:
      extraRules: []
  isolatedControlPlane:
    headless: false
  multiNamespaceMode:
    enabled: false
  syncSettings:
    disableSync: false
    rewriteKubernetesService: false
    setOwner: true
    targetNamespace: ""
exportKubeConfig:
  context: ""
  insecure: false
  secret:
    name: ""
    namespace: ""
  server: ""
  serviceAccount:
    clusterRole: ""
    name: ""
    namespace: ""
external: {}
integrations:
  externalSecrets:
    enabled: false
    sync:
      clusterStores:
        enabled: false
        selector:
          labels: {}
      externalSecrets:
        enabled: true
      stores:
        enabled: false
    webhook:
      enabled: false
  kubeVirt:
    enabled: false
    sync:
      dataVolumes:
        enabled: false
      virtualMachineClones:
        enabled: true
      virtualMachineInstanceMigrations:
        enabled: true
      virtualMachineInstances:
        enabled: true
      virtualMachinePools:
        enabled: true
      virtualMachines:
        enabled: true
    webhook:
      enabled: true
  metricsServer:
    enabled: true
    nodes: true
    pods: true
networking:
  advanced:
    clusterDomain: cluster.local
    fallbackHostCluster: false
    proxyKubelets:
      byHostname: true
      byIP: true
  replicateServices:
    fromHost: []
    toHost: []
  resolveDNS: []
plugins: {}
policies:
  centralAdmission:
    mutatingWebhooks: []
    validatingWebhooks: []
  limitRange:
    annotations: {}
    default:
      cpu: "1"
      ephemeral-storage: 8Gi
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      ephemeral-storage: 3Gi
      memory: 128Mi
    enabled: false
    labels: {}
    max: {}
    min: {}
  networkPolicy:
    annotations: {}
    enabled: false
    fallbackDns: 8.8.8.8
    labels: {}
    outgoingConnections:
      ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 100.64.0.0/10
        - 127.0.0.0/8
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
      platform: true
  resourceQuota:
    annotations: {}
    enabled: false
    labels: {}
    quota:
      count/configmaps: 100
      count/endpoints: 40
      count/persistentvolumeclaims: 20
      count/pods: 20
      count/secrets: 100
      count/services: 20
      limits.cpu: 20
      limits.ephemeral-storage: 160Gi
      limits.memory: 40Gi
      requests.cpu: 10
      requests.ephemeral-storage: 60Gi
      requests.memory: 20Gi
      requests.storage: 100Gi
      services.loadbalancers: 1
      services.nodeports: 0
    scopeSelector:
      matchExpressions: []
    scopes: []
rbac:
  clusterRole:
    enabled: auto
    extraRules: []
    overwriteRules: []
  role:
    enabled: true
    extraRules: []
    overwriteRules: []
sync:
  fromHost:
    csiDrivers:
      enabled: auto
    csiNodes:
      enabled: auto
    csiStorageCapacities:
      enabled: auto
    events:
      enabled: true
    ingressClasses:
      enabled: true
    nodes:
      clearImageStatus: false
      enabled: true
      selector:
        all: true
        labels: {}
      syncBackChanges: false
    priorityClasses:
      enabled: false
    runtimeClasses:
      enabled: false
    storageClasses:
      enabled: true
    volumeSnapshotClasses:
      enabled: false
  toHost:
    configMaps:
      all: false
      enabled: true
    endpoints:
      enabled: true
    ingresses:
      enabled: true
    networkPolicies:
      enabled: true
    persistentVolumeClaims:
      enabled: true
    persistentVolumes:
      enabled: true
    podDisruptionBudgets:
      enabled: false
    pods:
      enabled: true
      enforceTolerations: []
      rewriteHosts:
        enabled: true
        initContainer:
          image: library/alpine:3.20
          resources:
            limits:
              cpu: 30m
              memory: 64Mi
            requests:
              cpu: 30m
              memory: 64Mi
      translateImage: {}
      useSecretsForSATokens: false
    priorityClasses:
      enabled: false
    secrets:
      all: false
      enabled: true
    serviceAccounts:
      enabled: false
    services:
      enabled: true
    storageClasses:
      enabled: false
    volumeSnapshotContents:
      enabled: false
    volumeSnapshots:
      enabled: false
telemetry:
  enabled: true
```

</details>

**Comment by everflux** [comment]
I guess I found the cause, perhaps instead of crashing the behaviour could be improved when syncing of network policies is enabled but the feature is not active:

```
...
policies:
  networkPolicy:
    enabled: false
...
toHost:
    networkPolicies:
      enabled: true
```
