### ISSUE TITLE
Syncer forces unwanted defaults to services

### ISSUE THREAD

**Issue by olljanat** [loft-sh/vcluster#233]
Might be or might not be related to #211 but anyway as new case I noticed that I cannot use Kyverno on host cluster to set some environment specific settings because syncer forces some default to there.

Here is my Kyverno policy:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-lb-service
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: lb-service
    match:
      resources:
        kinds:
        - Service
        namespaces:
        - "vcluster-*"
    preconditions:
      all:
      - key: "{{request.operation}}"
        operator: In
        value:
        - CREATE
      - key: "{{request.object.spec.type}}"
        operator: Equals
        value: LoadBalancer
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            metallb.universe.tf/address-pool: "{{ request.namespace }}"
        spec:
          allocateLoadBalancerNodePorts: false
          externalTrafficPolicy: Local
          sessionAffinity: ClientIP
```

Annotation for MetalLB and `allocateLoadBalancerNodePorts: false` gets added just fine but those other settings does not get applied. Afaiu it because k8s on vcluster adds these defaults to services:
```yaml
spec:
  externalTrafficPolicy: Cluster
  sessionAffinity: None
```
and then syncer logic on https://github.com/loft-sh/vcluster/blob/f3a2d29dd8de1b6773797ebc18621ebdecdbe5d1/pkg/controllers/resources/services/translate.go#L89-L99 copies those over values set by Kyverno.
