### ISSUE TITLE
experimenal.deploy manifests helm deployment order

### ISSUE THREAD

**Issue by leunamnauj** [loft-sh/vcluster#2360]
### Is your feature request related to a problem?

When bootstrapping a vcluster, manifests are always being deployed before the helm chart installation. This breaks the setup since the helm chart needs to be installed first.

### Which solution do you suggest?

Add configuration to control deployment order, either by honoring the sequence defined in config files or adding explicit ordering options.

**Comment by FabianKramm** [comment]
Hey @leunamnauj ! Thats an interesting idea, we'll think about it, meanwhile you could use a simple helm chart that allows you to specify resources as values to circumvent that problem, e.g. using the `raw` helm chart from k8s-at-home:
```
helm repo add k8s-at-home https://k8s-at-home.com/charts/
helm repo update
```

Then do the following as values.yaml:
```
resources:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: my-config
    data:
      key: "value"
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: my-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: my-app
      template:
        metadata:
          labels:
            app: my-app
        spec:
          containers:
            - name: my-container
              image: nginx:alpine
```
