### ISSUE TITLE
Change logic to not include controlPlane.backingStore.etcd 's image when it's not enabled on the vCluster

### ISSUE THREAD

**Issue by deniseschannon** [loft-sh/vcluster#2398]
# Problem & Impact

On a default cluster that's created using 0.20 vCluster - vcluster create <name>, generate a yaml using helm get values VCLUSTER_NAME -n VCLUSTER_NAMESPACE command, and you will notice controlPlane.backingStore.etcd 's image is populated even though its disabled by default (The host cluster is on 1.29 in this case)

```
controlPlane:
  backingStore:
    etcd:
      deploy:
        statefulSet:
          image:
            tag: 3.5.10-0
  distro:
    k0s:
      image:
        tag: v1.29.6-k0s.0
    k3s:
      image:
        tag: v1.29.6-k3s1
    k8s:
      apiServer:
        image:
          tag: v1.29.6
      controllerManager:
        image:
          tag: v1.29.6
      scheduler:
        image:
          tag: v1.29.6
  service:
    spec:
      type: NodePort
sync:
  fromHost:
    nodes:
      enabled: true
telemetry:
  instanceCreator: vclusterctl
  machineID: 4f52a059183efb60979cbe81e105eac94519bb3be9910fbc141fe3dfc38a5833
```

# Goals

Change logic to not include controlPlane.backingStore.etcd 's image when it's not enabled on the vCluster
