### ISSUE TITLE
vcluster doesn't seem to honor domain suffix notation in NO_PROXY

### ISSUE THREAD

**Issue by joaocc** [loft-sh/vcluster#2426]
### What happened?

We are configuring vcluster to work behind a corporate proxy.
We are using the following:
```
      controlPlane:
        statefulSet:
          env:
            - name: HTTP_PROXY
              value: http://10.1.2.3:3128
            - name: HTTPS_PROXY
              value: http://10.1.2.3:3128
            - name: NO_PROXY
              value: 10.0.0.0/8,192.168.0.0/16,127.0.0.1,172.16.0.0/16,10.1.2.0/24,vc-etcd,.svc,.local,.svc.cluster.local,localhost,10.2.3.221,10.2.3.1
```
the settings above would fail if `vc-etcd` is not there.
In our understanding, the NO_PROXY should not require `vc-etcd`, as it should be caught by ´.local´ (or `.svc.cluster.local`).

### What did you expect to happen?

that the following should work
```
            - name: NO_PROXY
              value: 10.0.0.0/8,192.168.0.0/16,127.0.0.1,172.16.0.0/16,10.1.2.0/24,.svc,.local,.svc.cluster.local,localhost,10.2.3.221,10.2.3.1
```
or even
```
            - name: NO_PROXY
              value: 10.0.0.0/8,192.168.0.0/16,127.0.0.1,172.16.0.0/16,10.1.2.0/24,.svc.cluster.local,localhost,10.2.3.221,10.2.3.1
```

### How can we reproduce it (as minimally and precisely as possible)?

deploy in an VPC with 2 VMs, where only one (proxy) would have internet access, deploy squid to that VM, and configure the other VM with a k8s+vcluster, and then configure vcluster to try and access the internet.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
microk8s:
Client Version: v1.31.0
Kustomize Version: v5.4.2
Server Version: v1.31.4
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.20.0
```
</details>

### VCluster Config

<details>

```
# My vcluster.yaml / values.yaml here
```

</details>
