### ISSUE TITLE
Proposal: Enable rootless mode by default

### ISSUE THREAD

**Issue by olljanat** [loft-sh/vcluster#243]
Open this as proposal here to see if community thinks that vcluster charts should use rootless mode by default.

I would prefer it because nowadays applications should be secure by default.

Anyone supporting idea please leave 👍 for this message.

---
Alternative solution is that use policy engine. I example use this Kyverno policy to make sure that vcluster with all components and all pods deployed inside of it will be running without root permissions by default (but that still can be overwritten by providing alternative securityContext where ever needed):
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-default-securitycontext
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: add-default-securitycontext
    match:
      resources:
        kinds:
        - Pod
        namespaces:
        - "vcluster-*"
    mutate:
      patchStrategicMerge:
        spec:
          securityContext:
            +(runAsUser): 1000
            +(runAsGroup): 3000
            +(fsGroup): 2000
```
That one works fine with vanilla k8s. Note that `fsGroup` is critical parameter. Other why etcd does not start as it cannot write to disk without root permissions.
