### ISSUE TITLE
Setting server in exportKubeConfig overwrites default secret

### ISSUE THREAD

**Issue by irizzant** [loft-sh/vcluster#2464]
### What happened?

Hi
I'm facing the same issue as https://github.com/loft-sh/vcluster/issues/2234

I'm currently on vcluster v0.22.4, deployed with the following config:
```yaml
exportKubeConfig:       
     context: ""               
     insecure: false          
     secret:                      
       name: example-environment-vcluster 
       namespace: ""                                      
     server: https://somedomain.org         
```

I get 2 secrets created:
example-environment-vcluster
vc-example-environment-vcluster

but both contains the same `server `value `https://somedomain.org`

### What did you expect to happen?

vcluster creating 2 secrets , 1 with default `server `and 1 with overriden value

### How can we reproduce it (as minimally and precisely as possible)?

Create a vcluster with the above `extraKubeConfig`

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: v1.32.0
Kustomize Version: v5.5.0
Server Version: v1.31.4-eks-2d5f260
</details>

### vcluster version

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### VCluster Config

<details>

```
# My vcluster.yaml / values.yaml here
```
vcluster version 0.22.4
</details>
