### ISSUE TITLE
Allow setting imagePullSecret for coredns

### ISSUE THREAD

**Issue by jhwagner** [loft-sh/vcluster#2479]
### Is your feature request related to a problem?

When using the default coredns deployment, the image pull secret is not configurable. This becomes an issue when using private image registries, for example in many enterprise settings where we might use a private registry as a pull through cache or for other security concerns. Currently, the only way to address this is to override the entire coredns manifest config in `controlplane.coredns.overwriteManifests`, which is a bit cumbersome as it requires us to redefine all of the manifests just to add a single field.

This seems to have been brought up before, e.g. in https://github.com/loft-sh/vcluster/issues/488, which was marked resolved and the suggestion was to use `serviceAccount.imagePullSecrets` (which looks to now be `advanced.serviceAccount.imagePullSecrets` and `advanced.workloadServiceAccount.imagePullSecrets` but neither work). I'm not sure if this used to work and is just a regression but that field does not set the image pull secret on the coredns serviceaccount or deployment.

### Which solution do you suggest?

Similar to previous issue, add `imagePullSecret` parameter to coredns values, making the serviceaccount or deployment configurable. Something like `controlplane.coredns.imagePullSecret`

### Which alternative solutions exist?

Use `controlplane.coredns.overwriteManifests` and copy default coredns config from `coredns.yaml` in https://github.com/loft-sh/vcluster/blob/main/chart/templates/coredns-configmap.yaml#L13

**Comment by squ94wk** [comment]
Hi @jhwagner , thanks for raising the issue.
I tried to replicate the problem with 0.26.0 and the following config:
```
controlPlane:
  advanced:
    workloadServiceAccount:
      enabled: true
      name: some
      imagePullSecrets:
        - name: my-secret
```
It created the SA accordingly and set it on the CoreDNS Pod in the host cluster.
I edited the Deployment in the vcluster, specified a different image pointing to my local registry with basic auth and it successfully pulled the image using the credentials from the Secret.
Note that the Secret must exist on the host with the correct name so Kubelet can pick it up.

Can you please verify on your end or supply configuration where this doesn't work?

**Comment by jhwagner** [comment]
Hi @squ94wk thanks so much for the help!

I believe this may be related to service account host syncing? I've just replicated my issue with the following config:
```
sync:
  toHost:
    serviceAccounts:
      enabled: true

controlPlane:
  advanced:
    workloadServiceAccount:
      enabled: true
      name: workload-sa
      imagePullSecrets:
        - name: my-pull-secret
```
It seems that while I see `workload-sa` being created with the correct pull secrets in the host cluster, it is not used by the CoreDNS deployment which instead uses a `coredns` service account (in fact, I do not see `workload-sa` anywhere in the vCluster at all, only on the host).

### **serviceAccount host syncing enabled**:
coredns deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
spec:
...
    spec:
...
      serviceAccount: coredns
      serviceAccountName: coredns
 ...
```

coredns serviceaccount (no `imagePullSecrets`)
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coredns
  namespace: kube-system
```

coredns pod (from the **host** cluster):
```
apiVersion: v1
kind: Pod
metadata:
  name: coredns-94f599b5-ngv8l-x-kube-system-x-test-vcluster
  namespace: team-x
spec:
...
  serviceAccount: coredns-x-kube-system-x-test-vcluster
  serviceAccountName: coredns-x-kube-system-x-test-vcluster
```


### **serviceAccount host syncing disabled**:
If I use your config as-is (no service account host syncing), CoreDNS does use the `workload-sa` and therefore uses my `my-pull-secret`, however it does seem there is perhaps some vCluster "magic" going on here? Within the vCluster, the CoreDNS deployment looks as if it is still using the `coredns` service account (which does not have image pull secrets), but from the host cluster perspective, it is using `workload-sa` with proper pull secrets.
