### ISSUE TITLE
"tokenreviews.authentication.k8s.io is forbidden" when using OIDC on vcluster's kube-apiserver

### ISSUE THREAD

**Issue by systemstart** [loft-sh/vcluster#2490]
### What happened?

I'm trying to use OIDC to authenticate on the kube-apiserver:

```
controlPlane:
  distro:
    k8s:
      apiServer:
        extraArgs:
          - --oidc-issuer-url
          - https:/my-issuer.example.com
          - --oidc-client-id
          - my-client-id
```

After getting through the OIDC/OAuth2 flow this appears in the logs:
```
    isyncer 2025-02-13 10:14:10    ERROR    webhook/webhook.go:154    Failed to make webhook authenticator request: tokenreviews.authentication.k8s.io is forbidden: User "system:serviceaccount:vcluster-0:vc-vcluster-0" cannot create resource "tokenreviews" in API group "authentication.k8s.io" at the cluster scope    {"component": "vcluster"}          
    syncer 2025-02-13 10:14:10    ERROR    filters/authentication.go:73    Unable to authenticate the request    {"component": "vcluster", "error": "tokenreviews.authentication.k8s.io is forbidden: User \"system:serviceaccount:vcluster-0:vc-vcluster-0\" cannot create resource \"tokenreviews\" in API group \"authentication.k8s.io\" at the cluster scope", "errorCauses": [{"error": "tokenreviews.authentication.k8s.io is forbidden: User \"system:serviceaccount:vcluster-0:vc-vcluster-0\" cannot create resource \"tokenreviews\" in API group \"authentication.k8s.io\" at the cluster scope"}]}  
```

I saw this error in other(resolved) issues, but this doesn't seem to match.

Any idea?

### What did you expect to happen?

Authentication should work, or at least show new errors messages ;)

### How can we reproduce it (as minimally and precisely as possible)?

	helm install \
		--namespace 0 \
                --create-namespace \
		--values values.yaml \
		--repo https://charts.loft.sh \
		0 \
		vcluster

### Host cluster Kubernetes version

<details>

Server Version: v1.32.0+k3s1

</details>

### vcluster version

<details>

0.22.4

</details>

### VCluster Config

<details>

```
controlPlane:
  distro:
    k8s:
      apiServer:
        extraArgs:
          - --oidc-issuer-url
          - https:/my-issuer.example.com
          - --oidc-client-id
          - my-client-id
```

</details>
