### ISSUE TITLE
Helm version check fails with Fedora packaged Helm

### ISSUE THREAD

**Issue by jawsper** [loft-sh/vcluster#2545]
### What happened?

Running Fedora 41, with Fedora package `helm` installed (version `3.17.0-1.fc41`).

`helm version --client --template '{{.Version}}'` outputs `3.17.0`

Running `vcluster create ...` or `vcluster delete ...` fails with the error message:
```
fatal please ensure that the "helm" binary in your PATH is valid. Currently only Helm >= v3.10.0 is supported
```

### What did you expect to happen?

No error about `helm` not being valid.

### How can we reproduce it (as minimally and precisely as possible)?

On Fedora 41, install helm:
```
sudo dnf install helm
```
And check that the version is missing the `v` prefix:
```
helm version --client --template '{{.Version}}'
```

### Anything else we need to know?

From looking at the code, it seems that the `semver` package requires the semver to start with a `v` which is not the case for the helm I have installed.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.9-dispatcher
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.9-gke.1046000

```

</details>

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.22.4
```

</details>

### VCluster Config

<details>

```
# My vcluster.yaml / values.yaml here
controlPlane:
  distro:
    k3s:
      enabled: true
  statefulSet:
    resources:
      limits:
        memory: 4Gi
    scheduling:
      podManagementPolicy: OrderedReady
    persistence:
      volumeClaim:
        size: 10Gi
sync:
  fromHost:
    ingressClasses:
      enabled: true
  toHost:
    ingresses:
      enabled: true
    serviceAccounts:
      enabled: true

```

</details>
