### ISSUE TITLE
Support external standalone ETCD

### ISSUE THREAD

**Issue by P0t4T0o** [loft-sh/vcluster#2558]
### Is your feature request related to a problem?

We would like to have support for standalone external ETCD as a backing store (for K3S at least) in recent vcluster versions and onwards. Our project runs over 1000 vclusters (currently on v0.15.7) and we would like to further stick to this awesome project with possibility to continue using external ETCD.

### Which solution do you suggest?

Support external ETCD configuration in vcluster config and create etcd client accordingly.
values.yaml:
```yaml
controlPlane:
  statefulSet:
    persistence:
      addVolumes:
      - name: etcd-root-client-tls
        secret:
          defaultMode: 420
          secretName: etcd-root-client-tls
      addVolumeMounts:
      - mountPath: /etc/etcd/certs
        name: etcd-root-client-tls
  backingStore:
    etcd:
      external:
        enabled: true
        service: "https://etcd.dummy-namespace.svc.cluster.local:2379"
        tls:
          certFile: "/etc/etcd/certs/tls.crt"
          keyFile: "/etc/etcd/certs/tls.key"
          caFile: "/etc/etcd/certs/ca.crt"
```
