### ISSUE TITLE
podAntiAffinity rewrite

### ISSUE THREAD

**Issue by pasztorl** [loft-sh/vcluster#2584]
### Is your feature request related to a problem?

For example if i create a statefulset in the host cluster and add:
```
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - test
          topologyKey: kubernetes.io/hostname
```

then I add the same statefulset on the vcluster environment the pods will not schedule because of the app.kubernetes.io/instance will be the same and the previous statefulset use all available nodes in the example.

### Which solution do you suggest?

I"m not sure what can be broken if vlcuster rewrite this label in the statefulset everywhere.. just asking this is something that vcluster plan to handle in the future? or it will stay as a limitation?
