### ISSUE TITLE
Unable to connect to clusters using 0.24.0 (previously working with 0.19.x)

### ISSUE THREAD

**Issue by khaled** [loft-sh/vcluster#2673]
### What happened?

I just updated from vcluster 0.19.x to 0.24.0.  Previously I used to connect to clusters using:
```
vcluster connect <clustername> --server=https://<domain>/<endpoint> --service-account admin --cluster-role cluster-admin --insecure --update-current=false --kube-config=path/to/kubeconfig
```
With 0.24.0 i'm trying to do what seems to be the equivalent, which is 
```
vcluster connect <clustername> --server=https://<domain>/<endpoint> --service-account admin --cluster-role cluster-admin --insecure --print > path/to/kubeconfig
```
 I'm running into the following error: 
```
fatal create service account token: namespaces "kube-system" is forbidden: User "system:anonymous" cannot get resource "namespaces" in API group "" in the namespace "kube-system"
```

This occurs with clusters previously created with 0.19.x as well as clusters newly created with 0.24.0.

### What did you expect to happen?

To be able to connect to clusters like before.

### How can we reproduce it (as minimally and precisely as possible)?

Create a cluster using the Ingress without SSL-Passthrough method and try connecting to it per the instructions (https://www.vcluster.com/docs/vcluster/manage/accessing-vcluster?x1=2#expose-vcluster)

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### vcluster version

vcluster version 0.24.0

### VCluster Config

<details>

```yaml
controlPlane:
  distro:
    k3s:
      enabled: true
  hostPathMapper:
    enabled: true
  statefulSet:
    scheduling:
      podManagementPolicy: OrderedReady
integrations:
  metricsServer:
    enabled: true
networking:
  replicateServices:
    fromHost:
    - from: ns/svc-name
      to: ns/svc-name
sync:
  fromHost:
    ingressClasses:
      enabled: true
    nodes:
      enabled: true
      selector:
        all: true
  toHost:
    ingresses:
      enabled: true
```
</details>
