### ISSUE TITLE
Add the ability to prefix pod names

### ISSUE THREAD

**Issue by ben-z** [loft-sh/vcluster#2684]
### Is your feature request related to a problem?

Some k8s distros use janky logic for distro-specific functionalities. I'm using microk8s and they use string-matching to determine whether an addon is enabled:

https://github.com/canonical/microk8s/blob/750edecb7b73b87347810b52b0444688cafdeb5c/scripts/wrappers/common/utils.py#L561-L587

https://github.com/canonical/microk8s-core-addons/blob/f44892bb5fcae23c0a7329b96652c0015e181064/addons.yaml#LL7C3-L7C3

For example, coredns comes with vcluster by default, and microk8s checks for the string `pod/coredns` in `kubectl get pods -A` to determine whether its coredns addon is enabled. As a result, even when the addon is disabled, the coredns pod from vcluster makes microk8s think that the addon is enabled. This makes it difficult to perform infrastructure-as-code using declarative provisioning (e.g. using the microk8s Ansible playbook).

### Which solution do you suggest?

We could fix the janky string matching logic on the microk8s side, but their developers seem to be [very unresponsive](https://github.com/canonical/microk8s/issues/4245#issuecomment-2351074790). Instead, we could also add the ability to give a string prefix to all of the pods in vCluster. I tried using the [patch](https://www.vcluster.com/docs/vcluster/configure/vcluster-yaml/sync/to-host/core/pods#patches) functionality, but got the following error:

```yml
    sync: {
      toHost: {
        pods: {
          enabled: true,
          patches: [
            {
              path: "metadata.name",
              expression: "context.vcluster.name + '-' + value"
            }
          ]
sync:
  toHost:
    pods:
      enabled: true
      patches:
      - path: metadata.name
        expression: 'context.vcluster.name + "-" + value'
```

```
pods: metadata.name or metadata.namespace is not allowed as a path
```

### Which alternative solutions exist?

We could also add a feature to scramble the name completely when syncing from vCluster to the host. In this way, there's additional privacy benefits for the tenants, as well as prevents conflicts with janky logic that attempts to parse the kubectl output.
