### ISSUE TITLE
I am having trouble getting up a statefulset pod when appArmor configuration is set via pod securityContext.

### ISSUE THREAD

**Issue by SomanathThilak** [loft-sh/vcluster#2726]
### What happened?

When deploying a StatefulSet pod with AppArmor configuration specified via the pod's securityContext, the pod fails to start. The following error is observed:

Warning  SyncError  12m (x21 over 15m)  pod-syncer  Error syncing: patch virtual object: update object: Pod "sts-0" is invalid: [metadata.annotations[container.apparmor.security.beta.kubernetes.io/vcluster-rewrite-hosts]: Invalid value: "vcluster-rewrite-hosts": container not found, metadata.annotations[container.apparmor.security.beta.kubernetes.io/vcluster-rewrite-hosts]: Forbidden: may not add AppArmor annotations]

This issue does not occur when the host Kubernetes version is 1.30 or lower.

### What did you expect to happen?

The StatefulSet pod should start successfully with the specified AppArmor configuration, regardless of the host Kubernetes version, provided that the configuration is valid.

### How can we reproduce it (as minimally and precisely as possible)?

1. Set up a vcluster on a host Kubernetes cluster with version 1.31 or higher.​
2. Deploy a StatefulSet pod within the vcluster, specifying an AppArmor profile via the pod's securityContext.​
3. Observe that the pod fails to start with the aforementioned error.​
4. Repeat the same steps on a host Kubernetes cluster with version 1.30 or lower, and observe that the pod starts successfully.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.32.2+k3s1
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
0.22.4
```

</details>

### VCluster Config

<details>

```
USER-SUPPLIED VALUES:
controlPlane:
  advanced:
    defaultImageRegistry: ""
    globalMetadata:
      annotations: {}
    headlessService:
      annotations: {}
      labels: {}
    serviceAccount:
      annotations: {}
      enabled: true
      imagePullSecrets: []
      labels: {}
      name: ""
    virtualScheduler:
      enabled: false
    workloadServiceAccount:
      annotations: {}
      enabled: true
      imagePullSecrets: []
      labels: {}
      name: ""
  distro:
    k0s:
      command: []
      config: ""
      enabled: false
      extraArgs: []
      image:
        registry: ""
        repository: k0sproject/k0s
        tag: v1.30.2-k0s.0
      imagePullPolicy: ""
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 40m
          memory: 64Mi
      securityContext: {}
    k3s:
      command: []
      enabled: true
      extraArgs: []
      image:
        registry: xxxx
        repository: rancher/k3s
        tag: v1.32.2-k3s1
      imagePullPolicy: ""
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 40m
          memory: 64Mi
      securityContext: {}
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    enabled: false
    host: my-host.com
    labels: {}
    pathType: ImplementationSpecific
    spec:
      tls: []
  service:
    annotations: {}
    enabled: true
    httpsNodePort: 0
    kubeletNodePort: 0
    labels: {}
    spec:
      type: ClusterIP
  serviceMonitor:
    annotations: {}
    enabled: false
    labels: {}
  statefulSet:
    annotations: {}
    args: []
    command: []
    enableServiceLinks: true
    env: []
    highAvailability:
      leaseDuration: 60
      renewDeadline: 40
      replicas: 1
      retryPeriod: 15
    image:
      registry: ghcr.io
      repository: loft-sh/vcluster-oss
      tag: 0.22.4
    imagePullPolicy: ""
    labels: {}
    persistence:
      addVolumeMounts: []
      addVolumes: []
      binariesVolume:
      - emptyDir: {}
        name: binaries
      dataVolume: []
      volumeClaim:
        accessModes:
        - ReadWriteOnce
        enabled: auto
        retentionPolicy: Retain
        size: 5Gi
        storageClass: ""
      volumeClaimTemplates: []
    pods:
      annotations: {}
      labels: {}
    probes:
      livenessProbe:
        enabled: true
      readinessProbe:
        enabled: true
      startupProbe:
        enabled: true
    resources:
      limits:
        ephemeral-storage: 8Gi
        memory: 2Gi
      requests:
        cpu: 200m
        ephemeral-storage: 400Mi
        memory: 256Mi
    scheduling:
      affinity: {}
      nodeSelector: {}
      podManagementPolicy: Parallel
      priorityClassName: ""
      tolerations: []
      topologySpreadConstraints: []
    security:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        runAsGroup: 0
        runAsUser: 0
      podSecurityContext: {}
    workingDir: ""
exportKubeConfig:
  context: vcluster104
  server: vcluster104
external: {}
integrations:
  metricsServer:
    enabled: false
    nodes: true
    pods: true
networking:
  advanced:
    clusterDomain: cluster.local
    fallbackHostCluster: false
    proxyKubelets:
      byHostname: true
      byIP: true
  replicateServices:
    fromHost: []
    toHost: []
  resolveDNS: []
plugin:
  contour:
    env:
    - name: CONFIG
      value: |-
        version: v1beta1
        mappings:
          - fromVirtualCluster:
              # CRD for the apiVersion+Kind is implicitly copied to the virtual cluster
              apiVersion: projectcontour.io/v1
              kind: HTTPProxy
              patches:
                - op: rewriteName
                  path: spec.routes..services..name
                - op: rewriteName
                  path: spec.virtualhost.tls.secretName
                  sync:
                    secret: true
                - op: rewriteName
                  path: spec.routes..services..validation.caSecret
                - op: rewriteName
                  path: spec.tcpproxy.services..name
                - op: rewriteName
                  path: spec.includes
                  namePath: name
                  namespacePath: namespace
              reversePatches:
                - op: copyFromObject
                  fromPath: status
                  path: status
    image: ghcr.io/loft-sh/vcluster-generic-crd-plugin:latest
    imagePullPolicy: IfNotPresent
    rbac:
      clusterRole:
        extraRules:
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - list
          - watch
      role:
        extraRules:
        - apiGroups:
          - projectcontour.io
          resources:
          - httpproxies
          - extensionservices
          - tlscertificatedelegations
          verbs:
          - create
          - delete
          - patch
          - update
          - get
          - list
          - watch
plugins: {}
policies:
  centralAdmission:
    mutatingWebhooks: []
    validatingWebhooks: []
  limitRange:
    annotations: {}
    default:
      cpu: "1"
      ephemeral-storage: 8Gi
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      ephemeral-storage: 3Gi
      memory: 128Mi
    enabled: auto
    labels: {}
  networkPolicy:
    annotations: {}
    enabled: false
    fallbackDns: 8.8.8.8
    labels: {}
    outgoingConnections:
      ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 100.64.0.0/10
        - 127.0.0.0/8
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
      platform: true
  resourceQuota:
    annotations: {}
    enabled: auto
    labels: {}
    quota:
      count/configmaps: 100
      count/endpoints: 40
      count/persistentvolumeclaims: 20
      count/pods: 20
      count/secrets: 100
      count/services: 20
      limits.cpu: 20
      limits.ephemeral-storage: 160Gi
      limits.memory: 40Gi
      requests.cpu: 10
      requests.ephemeral-storage: 60Gi
      requests.memory: 20Gi
      requests.storage: 100Gi
      services.loadbalancers: 1
      services.nodeports: 0
    scopeSelector:
      matchExpressions: []
    scopes: []
rbac:
  clusterRole:
    enabled: auto
    extraRules: []
    overwriteRules: []
  role:
    enabled: true
    extraRules: []
    overwriteRules: []
sync:
  fromHost:
    csiDrivers:
      enabled: auto
    csiNodes:
      enabled: auto
    csiStorageCapacities:
      enabled: auto
    events:
      enabled: true
    ingressClasses:
      enabled: false
    nodes:
      clearImageStatus: false
      enabled: false
      syncBackChanges: false
    storageClasses:
      enabled: auto
  toHost:
    endpoints:
      enabled: true
    ingresses:
      enabled: false
    networkPolicies:
      enabled: false
    persistentVolumeClaims:
      enabled: true
    persistentVolumes:
      enabled: false
    podDisruptionBudgets:
      enabled: false
    pods:
      enabled: true
      enforceTolerations: []
      translateImage: {}
      useSecretsForSATokens: false
    secrets:
      all: false
      enabled: true
    serviceAccounts:
      enabled: false
    services:
      enabled: true
    storageClasses:
      enabled: false
    volumeSnapshots:
      enabled: false
telemetry:
  enabled: false
```

</details>
