### ISSUE TITLE
[Question] about storageClass sync

### ISSUE THREAD

**Issue by pasztorl** [loft-sh/vcluster#2755]
Hi,

I have multiple storage class on the host k8s system. There is a possibility to filter what is synced from host by label or annotation?

thanks!

**Comment by matskiv** [comment]
There isn't such possibility now, it but it would make sense to add it. Would you be interested in contributing code for this kind of feature? I am just asking, the design should be consulted with maintainers before starting any coding :)

**Comment by ulyssessouza** [comment]
Hello @pasztorl ,

We are about to implement a new feature to address this issue.
It's currently in a design phase. That should look like a standard label selector.
I'll keep you posted with the next steps.

**Comment by ulyssessouza** [comment]
@pasztorl A feature for limiting classes by labels will be present in `v0.26.0`. 

This includes:
- StorageClasses
- IngressClasses
- PriorityClasses
- RuntimeClasses

**Comment by ulyssessouza** [comment]
@pasztorl
The following configuration syncs all `StorageClasses` that match the specified labels and expressions from the host cluster to the virtual cluster:
```YAML
sync:
  fromHost:
    storageClasses:
      enabled: true
      selector:
        matchLabels:
          # Match all StorageClasses with the label `environment` with value `development`
          environment: "development"
        matchExpressions:
          # Match StorageClasses with the label `kubernetes.io/storage.class` that are either `network-nas` or `fast-sdd`
          - key: "kubernetes.io/storage.class"
            operator: In
            values:
              - network-nas
              - fast-ssd
```

The `selector` field follows the same syntax as Kubernetes label selectors. Use it to filter which `StorageClass` resources are synced from the host cluster based on their labels.
All specified label conditions must match for an `StorageClass` to be included in the sync.


Please note that this feature is still in development but it's already available in the current `v0.26.0` beta versions.
