### ISSUE TITLE
K3S_DATASTORE_ENDPOINT and related environment variables not working

### ISSUE THREAD

**Issue by Symbianx** [loft-sh/vcluster#2779]
### What happened?

We're trying to upgrade vcluster from 0.19.2 all the way to 0.24.1.

We are relying on the environment variables `K3S_DATASTORE_ENDPOINT` and `K3S_DATASTORE_CAFILE` to configure the connection to the database.

However, it never connects to the database and uses the SQLITE3 connection instead.

See logs:
> 2025-05-12 15:15:00     INFO    commandwriter/commandwriter.go:128      Configuring sqlite3 database connection pooling: maxIdleConns=2, maxOpenConns=0, connMaxLifetime=0s   {"component": "vcluster", "component": "k3s", "time": "2025-05-12T15:15:00Z", "level": "info"}

### What did you expect to happen?

The vcluster k3s should connect and use the database specified by the environment variable.

### How can we reproduce it (as minimally and precisely as possible)?

Create a mysql database. e.g.:

<details>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: miguel-test-vcluster
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: vcluster
        - name: MYSQL_DATABASE
          value: vcluster
        - name: MYSQL_USER
          value: vcluster
        - name: MYSQL_PASSWORD
          value: vcluster
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: miguel-test-vcluster
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP

```

</details>

Create the vcluster pointing at the database (using config below).

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# Client Version: v1.33.0
# Kustomize Version: v5.6.0
# Server Version: v1.32.3-eks-bcf3d70
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
# vcluster version 0.24.1
```

</details>

### VCluster Config

<details>

```yaml
controlPlane:
  backingStore:
    database:
      external:
        enabled: true
      embedded:
        enabled: false
  # Deploy vCluster with 3 replicas
  statefulSet:
    env:
    - name: K3S_DATASTORE_ENDPOINT
      value: mysql://vcluster:vcluster@tcp(mysql:3306)/vcluster
    highAvailability:
      replicas: 3
  distro:
    k3s:
      enabled: true
      image:
        tag: v1.32.3-k3s1
```

</details>
