### ISSUE TITLE
Point `Service` of type `ExternalName` to internal service if externalName is like `*.svc.cluster.local`

### ISSUE THREAD

**Issue by lucasfcnunes** [loft-sh/vcluster#2784]
### Is your feature request related to a problem?

Yes.

I need to create services that point to services in other namespaces. It doesn't work in the vcluster as it works in the host cluster.

### Which solution do you suggest?

Map any VCluster `Kind: Service, spec.type: ExternalName, externalName: [<pod>.][<svc>[.<namespace>]][.svc[.cluster.local|<custom_suffix>]]` only to resources inside the VCluster.

*All resources are inside a vcluster created with `vcluster create vcluster -n vcluster`
```yaml
...
---
apiVersion: v1
kind: Service
metadata:
  name: svc-a
  namespace: a
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    # ...
---
apiVersion: v1
kind: Service
metadata:
  name: svc-b
  namespace: b
spec:
  type: ExternalName
  # map from:
  externalName: svc-a.a.svc.cluster.local
  # to: (right now, only this 👇 fqdn works)
  # externalName: svc-a-x-a-x-vcluster.vcluster.svc.cluster.local
  ports:
    - name: http
      port: 80
      targetPort: 80
```

### Which alternative solutions exist?

Use e.g. `svc-a-x-a-x-vcluster.vcluster.svc.cluster.local`

### Additional context

vcluster v0.24.1
