### ISSUE TITLE
[v0.24] [CLONE] Connector compatibility between 0.24.x and 0.25.0

### ISSUE THREAD

**Issue by cbron** [loft-sh/vcluster#2794]
### What happened?

Use connector without setting controlPlane.backingStore.database.external.enabled in 0.24.x, then upgrade to 0.25.0. The connector is not used, but instead an SQLite database.

### What did you expect to happen?

We want vCluster to continue using the database that was provisioned for it.

### How can we reproduce it (as minimally and precisely as possible)?

Use connector without setting controlPlane.backingStore.database.external.enabled in 0.24.x, then upgrade to 0.25.0

### Host cluster Kubernetes version

N/A

### vcluster version

0.24.x -> 0.25.x

### VCluster Config

```
controlPlane:
  backingStore:
    database:
      external:
        connector: <connector>
```

ENG-6900
