### ISSUE TITLE
Services with mismatching selectors after upgrading vcluster from 0.20.0 to 0.25.0

### ISSUE THREAD

**Issue by cinesia** [loft-sh/vcluster#2887]
### What happened?

After upgrading a vcluster from version 0.20.0 to 0.25.0, we noticed that all Kubernetes services were **not** recreated, resulting in mismatched selectors that no longer aligned with the labels of the pods.

Below is an example of the mismatch observed in the cluster when inspecting services and pods in the namespace of the specific virtual cluster.

**Selector of the old kube-dns service:**

```yaml
selector:
  vcluster.loft.sh/label-env-dev-plan-v20-x-0257408089: vcluster-kube-dns
  vcluster.loft.sh/managed-by: env-dev-plan-v20
  vcluster.loft.sh/namespace: kube-system
```

**New labels of the kube-dns pod:**

```yaml
labels:
  vcluster.loft.sh/managed-by: env-dev-plan-v20
  vcluster.loft.sh/namespace: kube-system
  vcluster.loft.sh/ns-label-env-dev-plan-v20-x-cf1227b7b2: kube-system
```

As you can see, there is a UID-like suffix in the label key that no longer matches the old selector.

This issue affects all services in the cluster — both system and application services.

---

### What did you expect to happen?

We expected the upgrade process to manage label changes automatically, ensuring that services would be recreated or at least patched to match the new labels.

---

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a vcluster using version 0.20.0.
2. Install a simple application that includes services and pods.
3. Upgrade the vcluster to version 0.25.0.

---

### Anything else we need to know?

The entire process was managed using a Helm chart.

---

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.15
```

</details>

---

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.20.4
```

</details>

---

### vcluster Config

<details>

> Note: Some placeholders in the format `${PLACEHOLDER}` are replaced before applying.

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: env-${env}
  namespace: flux-system
spec:
  interval: 1m
  releaseName: env-${env}
  targetNamespace: env-${env}
  chart:
    spec:
      chart: vcluster
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: loft-sh
  values:
    controlPlane:
      backingStore:
        etcd:
          deploy:
            enabled: true
            statefulSet:
              labels:
                name: ${env}-etcd
              highAvailability:
                replicas: 3
              persistence:
                volumeClaim:
                  storageClass: ${storageClass}
      distro:
        k8s:
          enabled: true
          version: 1.32.0
      proxy:
        extraSANs:
        - api.${env}.${host}.${zone}
      statefulSet:
        scheduling:
          podManagementPolicy: OrderedReady
      ingress:
        enabled: true
        host: api.${env}.${host}.${zone}
        annotations:
          cert-manager.io/cluster-issuer: ${clusterIssuer}
          external-dns.alpha.kubernetes.io/hostname: api.${env}.${host}.${zone}
        spec:
          ingressClassName: nginx
          tls:
          - hosts:
            - api.${env}.${host}.${zone}
            secretName: api-${env}-tls
    sync:
      toHost:
        ingresses:
          enabled: true
      fromHost:
        nodes:
          enabled: true
          selector:
            all: true
        storageClasses:
          enabled: true
    exportKubeConfig:
      server: https://api.${env}.${host}.${zone}
    networking:
      replicateServices:
        fromHost:
          - from: sso-auth/sso-auth-login-service
            to: from-host-sso-auth/sso-auth-login-service
        toHost:
          - from: logs/prometheus-kube-prometheus-thanos-discovery
            to: from-${env}-thanos
```

</details>

**Comment by SCLogo** [comment]
Happens to me as well. Sometimes the upgrade goes well without any issue. sometimes labels from host sync into v and after that nothing works inside vcluster since svc cannot find pods based on label selectors.

**Comment by cbron** [comment]
> we noticed that all Kubernetes services were not recreated, resulting in mismatched selectors that no longer aligned with the labels of the pods.

@cinesia or @SCLogo  can you clarify which part is breaking here ? I'm not clear what you mean by recreated. Are the selectors and labels matching on the virtual but not on the host ? And on the host what are the selectors labels post upgrade.

**Comment by cinesia** [comment]
> > we noticed that all Kubernetes services were not recreated, resulting in mismatched selectors that no longer aligned with the labels of the pods.
> 
> [@cinesia](https://github.com/cinesia) or [@SCLogo](https://github.com/SCLogo) can you clarify which part is breaking here ? I'm not clear what you mean by recreated. Are the selectors and labels matching on the virtual but not on the host ? And on the host what are the selectors labels post upgrade.

Hi, see the example above (in the very first post of the issue). 

**Selector of the old kube-dns service:**

```yaml
selector:
  vcluster.loft.sh/label-env-dev-plan-v20-x-0257408089: vcluster-kube-dns <--- THE LABEL BEFORE THE UPDATE
  vcluster.loft.sh/managed-by: env-dev-plan-v20
  vcluster.loft.sh/namespace: kube-system
```

**New labels of the kube-dns pod:**

```yaml
labels:
  vcluster.loft.sh/managed-by: env-dev-plan-v20
  vcluster.loft.sh/namespace: kube-system
  vcluster.loft.sh/ns-label-env-dev-plan-v20-x-cf1227b7b2: kube-system  <--- THE LABEL AFTER THE UPDATE
```

As you can see the **kube-dns pod** labels were updated after the upgrade, but the **kube-dns service** didn't . The same mismatch happened to each components of the vcluster synced to the host cluster. This led to an interruption of  communications between the pods , and so, to a non-working vcluster.
