### ISSUE TITLE
After deleting the PVC, the corresponding PV was not deleted

### ISSUE THREAD

**Issue by leonyzhe** [loft-sh/vcluster#2939]
### What happened?

After deleting a PVC in the virtual cluster (vcluster), I observed that the PVC on the virtual cluster side was deleted, but the PV was not. Meanwhile, on the host cluster side, the corresponding PVC and PV could be deleted normally.

### What did you expect to happen?

All PVCs and PVs should be purged from both the virtual cluster and the host cluster.

### How can we reproduce it (as minimally and precisely as possible)?

```
#Create a Pod that declares a PVC using the YAML file below.

# pod-with-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-csi
---
apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: web-server
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: app-storage
      mountPath: "/usr/share/nginx/html"  
  volumes:
  - name: app-storage
    persistentVolumeClaim:
      claimName: app-data-pvc

# then delete this resource
kubectl delete -f pod-with-pvc.yaml
```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.6
```

</details>

### vcluster version

<details>

```console
$ vcluster --version
vcluster version 0.23.0
```

</details>

### VCluster Config

<details>

```
# My vcluster.yaml / values.yaml here

controlPlane:
  advanced:
    globalMetadata: {}
    headlessService: {}
    virtualScheduler: {}
    workloadServiceAccount: {}
  backingStore:
    database:
      embedded: {}
      external: {}
    etcd:
      deploy:
        enabled: true
        headlessService: {}
        service: {}
        statefulSet:
          highAvailability:
            replicas: 3
          image: {}
          persistence:
            volumeClaim:
              enabled: true
              size: 50Gi
          resources:
            limits:
              cpu: "2"
              memory: 6Gi
            requests:
              cpu: 200m
              memory: 1Gi
          security: {}
      embedded: {}
  coredns:
    deployment:
      pods: {}
      replicas: 2
      resources: {}
    enabled: true
    service: {}
  distro:
    k0s:
      image: {}
    k3s:
      image: {}
    k8s:
      apiServer:
        image:
          tag: v1.30.6
      controllerManager:
        image:
          tag: v1.30.6
      enabled: true
      scheduler:
        image:
          tag: v1.30.6
      version: v1.30.6
  hostPathMapper: {}
  ingress: {}
  proxy:
    extraSANs:
    - 10.237.234.50
  service: {}
  serviceMonitor: {}
  statefulSet:
    highAvailability:
      replicas: 3
    persistence:
      volumeClaim:
        enabled: true
    probes:
      livenessProbe: {}
      readinessProbe: {}
      startupProbe: {}
    resources:
      limits:
        cpu: "4"
        memory: 6Gi
      requests:
        cpu: 300m
        memory: 1Gi
    security: {}
experimental:
  deploy:
    host: {}
    vcluster: {}
  genericSync:
    clusterRole: {}
    role: {}
  isolatedControlPlane: {}
  multiNamespaceMode: {}
  syncSettings: {}
  virtualClusterKubeConfig: {}
integrations:
  certManager:
    sync:
      fromHost:
        clusterIssuers:
          selector: {}
      toHost:
        certificates: {}
        issuers: {}
  externalSecrets:
    sync:
      clusterStores:
        selector: {}
      externalSecrets: {}
      stores: {}
    webhook: {}
  kubeVirt:
    apiService:
      service: {}
    sync:
      dataVolumes: {}
      virtualMachineClones: {}
      virtualMachineInstanceMigrations: {}
      virtualMachineInstances: {}
      virtualMachinePools: {}
      virtualMachines: {}
    webhook: {}
  metricsServer:
    apiService:
      service: {}
networking:
  advanced:
    proxyKubelets: {}
  replicateServices: {}
policies:
  centralAdmission: {}
  limitRange:
    default:
      cpu: 100m
      ephemeral-storage: 10Gi
      memory: 200Mi
    defaultRequest:
      cpu: "0"
      ephemeral-storage: 0Gi
      memory: "0"
    enabled: true
  networkPolicy:
    enabled: true
    outgoingConnections:
      ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 172.26.0.0/16
  resourceQuota:
    enabled: true
    quota:
      count/configmaps: 1000
      count/endpoints: 1000
      count/persistentvolumeclaims: 1000
      count/pods: 1000
      count/secrets: 1000
      count/services: 1000
      limits.cpu: 1000
      limits.ephemeral-storage: 10000Gi
      limits.memory: 2000Gi
      requests.cpu: 500
      requests.ephemeral-storage: 2000Gi
      requests.memory: 4000Gi
      requests.storage: 10000Gi
      services.loadbalancers: 100
      services.nodeports: 100
rbac:
  clusterRole: {}
  role: {}
sync:
  fromHost:
    configMaps:
      mappings: {}
    csiDrivers: {}
    csiNodes: {}
    csiStorageCapacities: {}
    events: {}
    ingressClasses: {}
    nodes:
      clearImageStatus: true
    priorityClasses: {}
    runtimeClasses: {}
    secrets:
      mappings: {}
    storageClasses:
      enabled: true
    volumeSnapshotClasses: {}
  toHost:
    configMaps: {}
    endpoints: {}
    ingresses: {}
    networkPolicies:
      enabled: true
    persistentVolumeClaims:
      enabled: true
    persistentVolumes:
      enabled: true
    podDisruptionBudgets: {}
    pods:
      rewriteHosts:
        initContainer:
          resources: {}
    priorityClasses:
      enabled: true
    secrets: {}
    serviceAccounts: {}
    services: {}
    storageClasses: {}
    volumeSnapshotContents: {}
    volumeSnapshots: {}
telemetry: {}
```

</details>

After I added a label to the PV using the command below, the PV was triggered for deletion.
`kubectl label pv pvc-a5f95675-b9a9-4183-860e-0a347a53f55e leon=test`
