### ISSUE TITLE
can not mkdir /data/server permission denied when using non root user

### ISSUE THREAD

**Issue by caedo960** [loft-sh/vcluster#314]
I'm trying to create a vcluster (version v0.5.2) using the the following configuration:

```yaml
vcluster:
  image: rancher/k3s:v1.22.5-k3s1

securityContext:
  runAsUser: 12345
  runAsNonRoot: true
```
The vcluster pod ends up to a crashloopbackoff and logs shows permission denied for creating directory. Any idea what could cause this?

`vcluster time="2022-01-18T16:43:14Z" level=info msg="Starting k3s v1.22.5+k3s1 (405bf79d)"`                                                                                                                                                                                 
`vcluster time="2022-01-18T16:43:14Z" level=fatal msg="can not mkdir /data/server: mkdir /data/server: permission denied"`
`syncer I0118 16:48:24.023374 1 start.go:136] couldn't find virtual cluster kube-config, will retry in 1 seconds`
