### ISSUE TITLE
Select nodes for the initial k3s StatefulSet

### ISSUE THREAD

**Issue by efrecon** [loft-sh/vcluster#34]
The documentation [describes](https://www.vcluster.com/docs/architecture/nodes#node-syncing-modes) how to select nodes that will receive deployments and other resources. But is it possible to similarly force the initial k3s StatefulSet to be restricted to node using a `nodeSelector`?

Manually modifying the `StatefulSet` once it has been created as of `vcluster create` works, but the UX would benefit from being able to pick nodes at creation time already.

The content of my `values.yml` file was as follows (I have a windows/linux hybrid cluster at hand).

```
rbac:
  clusterRole:
    create: true

syncer:
  extraArgs:
    - --fake-nodes=false
    - --node-selector=beta.kubernetes.io/os=linux
    - --enforce-node-selector
```
