### ISSUE TITLE
sts syncing ignores limit & requests

### ISSUE THREAD

**Issue by kotaner** [loft-sh/vcluster#372]
### What happened?

When we sync a sts with : 
...
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "1"
...
vcluster fails to sync this to the host k8s. Our host k8s has strict enforcement for limits & requests and gives us following error :
 Warning  SyncError  8s (x13 over 28s)  pod-syncer  Error syncing to physical cluster: pods "XXXX-x-kayra-x-YYY" is forbidden: failed quota: compute-resources: must specify limits.cpu,limits.memory,requests.cpu,requests.memory

When we try to deploys with same requests/limits vcluster properly syncs them to the host cluster. This is only happening on sts, and all other constructs (svc,pvc etc) are properly synced.

### What did you expect to happen?

Proper syncing of all requests & limits down to host cluster

### How can we reproduce it (as minimally and precisely as possible)?

Create a sts, and specify requests & limits and see if they're synced to host cluster.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
1.16
```
</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
icp
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.5.3```

</details>


### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```
k0s
</details>


### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

**Comment by FabianKramm** [comment]
@kotaner thanks for creating this issue! In order for vcluster to function correctly it will create an init container during statefulset syncing to set the FQDN correctly. This init container has no resources set by default and you'll need to use a `LimitRange` to set the resources there automatically. We could also think about adding those to avoid such problems in future vcluster versions. A potential limit range for the host cluster could look like:
```
apiVersion: v1
kind: LimitRange
metadata:
  name: vcluster-limit-range
spec:
  limits:
  - default:
      cpu: 100m
      memory: 256Mi
    defaultRequest:
      cpu: 20m
      memory: 64Mi
    min:
      cpu: 10m
      memory: 32Mi
    type: Container
```
