### ISSUE TITLE
`--expose` not working as advertised

### ISSUE THREAD

**Issue by codeprefect** [loft-sh/vcluster#373]
### What happened?

Run the following:

```[bash]
vcluster create vcluster-1 -n host-namespace-1 --expose
vcluster connect vcluster-1 --namespace host-namespace-1
```
It gets stuck at
```[bash]
[info]   Waiting for vcluster LoadBalancer IP...
```
It stays here for a very long time and finally times out.

A quick investigation I did reveal that the service load balancer could not be assigned a port.
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-02-14T00:54:34Z"
  generateName: svclb-vcluster-1-
  labels:
    app: svclb-vcluster-1
    controller-revision-hash: 579b5cd9bc
    pod-template-generation: "1"
    svccontroller.k3s.cattle.io/svcname: vcluster-1
  ...
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-14T00:54:34Z"
    message: '0/1 nodes are available: 1 node(s) didn''t have free ports for the requested
      pod ports.'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: BestEffort
```

### What did you expect to happen?

A load balancer should be created.

### How can we reproduce it (as minimally and precisely as possible)?

```[bash]
vcluster create vcluster-1 -n host-namespace-1 --expose
vcluster connect vcluster-1 --namespace host-namespace-1
```
It gets stuck at
```[bash]
[info]   Waiting for vcluster LoadBalancer IP...
```

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:35:46Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1+k3s2", GitCommit:"a0cadcd3436745396c82821b4a0803ee460401e1", GitTreeState:"clean", BuildDate:"2022-01-14T08:14:22Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
v1.23.1 (Rancher Desktop v1.0.1)
```
</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.6.0-beta.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s(default)
```

</details>

### OS and Arch

<details>

```
OS: MacOS Monterey
Arch: M1 Pro
```
</details>
