### ISSUE TITLE
Syncer option to persist labels on physical resources 

### ISSUE THREAD

**Issue by bschwenn** [loft-sh/vcluster#386]
### Is your feature request related to a problem?

Mutating webhooks often use label selectors to determine which resources to process. Since vcluster mutates all the labels on synced resources, this can prevent webhooks in the physical cluster from being able to mutate the physical resources.

In particular we've encountered this issue for synced pods. 
### Which solution do you suggest?

Add a configuration option to persist the labels on resources to the syncer. The option could disable label mutation entirely for some resource types, or add both the vcluster labels and the original labels. 

### Which alternative solutions exist?

- This could be implemented by consumers via a vcluster plugin. However, this seems onerous and would require a lot of wrapping of the standard syncers.  
- Consumers could update their webhooks to catch vcluster mutated labels. However, when using vcluster only as a development workflow this would entail updating production services to handle development cases, which is a bit of an antipattern. 
- Consumers can deploy the webhooks into the vcluster. This complicates the process of spinning up clusters and could lead to quite a sprawl. 

### Additional context

My apologies if there is already a way to achieve this (or a reason it's impossible), I didn't see it in my perusal of the docs and code if so.

**Comment by FabianKramm** [comment]
@bschwenn thanks for creating this issue! vcluster hashes labels to avoid conflicts between resources in the host cluster, for example it would be possible for a vcluster workload to become an endpoint of vcluster itself if we wouldn't do that, so its also a security measure.

What would be your use case for this where you would require labels to be 1:1 synced from the vcluster? Any particular pod you need to identify?

**Comment by bschwenn** [comment]
Thanks for the response @FabianKramm, makes sense. 

To be more specific about our use case here, say we have a mutating webhook configured similarly to the following: 
```
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-mutating-webhook
webhooks:
  - name: ...
    admissionReviewVersions:
      - "v1beta1"
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - "v1"
        operations:
          - "CREATE"
        resources:
          - pods
    ...
    objectSelector:
      matchExpressions:
      - key: example.com/enable-pod-mutating-webhook
        operator: In
        values:
        - "true"
```
where the `example.com/enable-pod-mutating-webhook` label is used to "opt-in" to having the webhook operate on a pod. (Our real world use case is operating on pods + pod labels in particular.) Since vcluster translates this label, the webhook will not operate on the virtual pods. In our case, this prevents some configuration from being injected into the pod, which prevents it from properly initializing.

> an option where vcluster would rewrite the labels like it does currently ... as well as add the original labels or only parts of them to the resource as well.

Yeah this would be great for our purposes. The presence of the translated labels doesn't cause any issue, rather the absence of one particular label on pods. So the smallest change to unblock this use case would be an option to sync specific untranslated labels onto the real cluster pods.
