### ISSUE TITLE
Hide Selected Host Storage Class from Vcluster

### ISSUE THREAD

**Issue by ikandars** [loft-sh/vcluster#395]
### Is your feature request related to a problem?

Yes. In my case I have 2 storageClass, longhorn and rook-ceph. When I enabled these option:

```yaml
sync:
  persistentvolumes:
    enabled: true
  storageclasses:
    enabled: true
```

all my host storageClass synced to vcluster

### Which solution do you suggest?

I need a way to hide some storageClass, which I use only for host internal storage and synced some storageClass, which dedicated for any storage within vluster.

Thanks in advance!
