### ISSUE TITLE
Cant get pods logs or exec on a service account

### ISSUE THREAD

**Issue by mhaddon** [loft-sh/vcluster#429]
### What happened?

I am probably doing something stupid, so maybe you guys can give me some insight.

If I create a VCluster (normal k3s), then create a Service Account inside of it, I can give that Service Account roles such as "cluster-admin".

On the host, I can then expose the VCluster pod, over port 663. Which is not the default port that VCluster exposes itself over, but it is the port that K3S is using. Then I can create my own kubeconfig like:

```
apiVersion: "v1"
kind: "Config"
clusters:
  - name: "xxx"
    cluster:
      certificate-authority-data: "xxx"
      server: "xxx"
contexts:
  - name: "xxx"
    context:
      cluster: "xxx"
      namespace: "default"
      user: "system:serviceaccount:kube-system:my-service"
current-context: "xxx"
users:
  - name: "system:serviceaccount:kube-system:my-service"
    user:
      token: "xxx"
```

Which then gives me the ability to connect to this vcluster, and be authenticated as this service-account.

Now this completely works for everything, except for exec and getting logs.

If you try you get an error like this:

```
> kubectl exec coredns-5cb85f495c-kvbtp -n kube-system --kubeconfig kubeconfig sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Error from server (Forbidden): forbidden: User "kube-apiserver" cannot post path "/exec/kube-system/coredns-5cb85f495c-kvbtp/coredns"
```

I assume this is because the vcluster pod is missing some permissions, but the role the vcluster on the host is running as has the permissions:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
--redacted--
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - pods
  - pods/attach
  - pods/portforward
  - pods/exec
  - endpoints
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - patch
  - update
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - pods/log
  verbs:
  - get
  - list
  - watch
--redacted--
```

Any idea?

### What did you expect to happen?

ability for a vcluster sa to get logs and exec

### How can we reproduce it (as minimally and precisely as possible)?

i think as i said above

### Host cluster Kubernetes version

<details>

1.23.5, but i dont think its version specific, ive tried on a few versions

</details>

### Host cluster Kubernetes distribution

<details>

</details>

### vlcuster version

<details>
0.7.1
</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

k3s

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>
