### ISSUE TITLE
CoreDNS cannot connect to K8s when using custom domain

### ISSUE THREAD

**Issue by olljanat** [loft-sh/vcluster#459]
### What happened?

On combination of K8s + custom cluster domain + custom CodeDNS config + separate namespace per for K8s and vcluster pods the CoreDNS get stuck to message:
```
[INFO] plugin/ready: Still waiting on: "kubernetes"
```

Same config worked before included custom domain and CoreDNS config to it.

### What did you expect to happen?

That it works :)

### How can we reproduce it (as minimally and precisely as possible)?

values.yaml
```yaml
serviceCIDR: "<serviceCIDR>"

enableHA: false

syncer:
  replicas: 1
  securityContext:
    runAsUser: 12345
    runAsNonRoot: true
  extraArgs:
    - --fake-persistent-volumes=false
    - --enable-storage-classes
    - --fake-nodes=false
    - --sync-all-nodes=false
    - --target-namespace=vcluster-example-dev
    - --disable-sync-resources=ingresses
    - --cluster-domain=example-dev.k8s.local

etcd:
  image: k8s.gcr.io/etcd:3.5.1-0
  replicas: 1
  securityContext:
    runAsUser: 12345
    runAsNonRoot: true

controller:
  image: k8s.gcr.io/kube-controller-manager:v1.23.5
  replicas: 1
  securityContext:
    runAsUser: 12345
    runAsNonRoot: true

api:
  image: k8s.gcr.io/kube-apiserver:v1.23.5
  replicas: 1
  securityContext:
    runAsUser: 12345
    runAsNonRoot: true

rbac:
  clusterRole:
    create: true

ingress:
  enabled: false

coredns:
  enabled: true
  replicas: 1
  config: |-
    .:1053 {
        errors
        health
        ready
        kubernetes example-dev.k8s.local cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }

isolation:
  enabled: false
```

Deployed with commands:
```bash
kubectl create ns "vcluster-example-dev-k8s"
kubectl create ns "vcluster-example-dev"
vcluster create --distro k8s --namespace "vcluster-example-dev-k8s" --create-namespace=false --extra-values values.yaml example-dev
kubectl -n "vcluster-example-dev" apply -f role.yaml
kubectl -n "vcluster-example-dev" apply -f rolebinding.yaml
```
(role and rolebinding.yaml are same than vcluster normally creates to added to that separate namespace too)

### Host cluster Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6+rke2r1", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-20T19:41:09Z", GoVersion:"go1.17.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
RKE2
```

</details>

### vlcuster version

<details>

```console
vcluster version 0.7.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
K8s
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu 20.04
Arch: amd64
```
</details>
