### ISSUE TITLE
Add mapping between host and virtual cluster services

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/vcluster#462]
In an effort to make it easier to reuse host or virtual cluster services, we can add a feature that maps a virtual cluster service to an host cluster service or vice versa. This would allow easy sharing of components between host and virtual cluster. We could make this happen by creating an external name service that would point to another service either in the host or virtual cluster. Configuration could happen through the helm chart:

```
mapPhysicalServices:
- from: my-physical-namespace/service-name
  to: my-virtual-namespace/service-name

mapVirtualServices:
- from: my-virtual-namespace/service-name
  to: physical-service-name
```

vcluster would then make sure the appropriate RBAC permissions are available as well as syncing those services between the physical and virtual cluster
