### ISSUE TITLE
Package applications with vcluster

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/vcluster#508]
## Use Case

One of the great advantages of vcluster is its easy way to install and maintain. You can install it into every CNCF conformant cluster and it usually works right out of the box. There are also applications that depend on other operators such as cert manager or argo cd. If you distribute such an an application, those operators could be conflicting with other operators already in the cluster or you don't have permissions to install those into the cluster which can cause trouble. 

One potential use case of vcluster could be to package applications into vcluster and then expose certain services within the vcluster to the outside for consumption. This has the great advantage of making it a lot easier to install and remove applications that depend on certain assumptions about the target cluster.

## Implementation

We don't want to create yet another marketplace for applications or want to create yet another registry. Hence the idea is to generate out of a vcluster file a helm chart that can be pushed directly to any helm repository. This could have the format of (example):
```yaml
apiVersion: vcluster.loft.sh/v1alpha1
kind: VCluster
metadata:
  name: my-vcluster
version: v0.0.1
chart:
  name: vcluster
  repo: loft...
  version: v0.8.0
valueFiles:
  - my-values.yaml
  - https://...
values:
  mapVirtualServices:
    - from: loft/loft # -> Regular Service created by someone inside the vcluster
      to: loft        # -> Generated ExternalName service
  sync:
    ...
manifests:
  - test.yaml
helmCharts: 
  - name: argo-cd
    repo: ...
  - path: ./charts/my-chart
hostManifests:
  - ...
```
And running `vcluster package my-vcluster.yaml` would create a `my-vcluster.tar.gz` which can be pushed to any helm repository.

**Comment by lucasfcnunes** [comment]
My thoughts on `apiVersion: vcluster.loft.sh/v1alpha1; kind: VCluster`
I think it should be implemented as to be possible to apply it as a native [k8s CRD resource](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/) in the future.
The same thing happens with the [kind config spec](https://pkg.go.dev/sigs.k8s.io/kind/pkg/apis/config/v1alpha4#Cluster) - it can't become a "`kubectl apply -f`" resource.

```yaml
apiVersion: vcluster.loft.sh/v1alpha1
kind: VCluster
metadata:
  name: my-vcluster
spec: # <<<: indent everything below this
  version: v0.0.1
  chart:
    name: vcluster
    repo: loft...
    version: v0.8.0
  valueFiles:
    - my-values.yaml
    - https://...
  values:
    mapVirtualServices:
      - from: loft/loft # -> Regular Service created by someone inside the vcluster
        to: loft        # -> Generated ExternalName service
    sync:
      ...
  manifests:
    - test.yaml
  helmCharts: 
    - name: argo-cd
      repo: ...
    - path: ./charts/my-chart
  hostManifests:
    - ...
```
