### ISSUE TITLE
Invalid ConfigMap / Secret ref names in Pods when the 52th character is a period (.)

### ISSUE THREAD

**Issue by nktpro** [loft-sh/vcluster#51]
As of the latest release of `v0.3.0-beta.3`, when a ConfigMap / Secret contains a period character (.) at index 51, `vcluster` will rewrite the Pod definition with a bad ref name. Here's a minimum reproducer:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: vcluster-bug
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres.admin-pg.credentials.postgresql.acid.zalan.do
  namespace: vcluster-bug
data:
  username: foobar
---
apiVersion: v1
kind: Pod
metadata:
  name: vcluster-bug
  namespace: vcluster-bug
spec:
  containers:
  - name: nginx
    image: k8s.gcr.io/nginx-slim:0.8
    env:
      - name: USERNAME_FROM_ENV
        valueFrom:
          configMapKeyRef:
            key: username
            name: postgres.admin-pg.credentials.postgresql.acid.zalan.do
``` 

This Pod will then be stuck at "Pending" state with this error message:

```
Error syncing to physical cluster: Pod "vcluster-bug-x-vcluster-bug-x-my-vcluster" is invalid:
spec.containers[0[].env[0[].valueFrom.configMapKeyRef.name: 
Invalid value: "postgres.admin-pg.credentials.postgresql.acid.zalan.-ac00eb36f8": 
a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' 
or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex 
used for validation is '[a-z0-9[]([-a-z0-9[]*[a-z0-9[])?(\.[a-z0-9[]([-a-z0-9[]*[a-z0-9[])?)*')
```
Notice that the newly referenced ConfigMap name is `postgres.admin-pg.credentials.postgresql.acid.zalan.-ac00eb36f8` which is indeed an invalid RFC 1123 subdomain. 

A long ConfigMap / Secret name is truncated to a length of 52, then appended with a generated suffix of length 11 in the form of `-XXXXXXXXXX` (for a total of 63 chars). If the truncated result ends with a period, we'll end up with this issue.

We actually ran into this while installing [postgres-operator](https://github.com/zalando/postgres-operator). This operator generates all Secrets with a (non-configurable) suffix of `.credentials.postgresql.acid.zalan.do`.
