### ISSUE TITLE
Allow context name in generated kube config to be specified

### ISSUE THREAD

**Issue by tekumara** [loft-sh/vcluster#523]
### Is your feature request related to a problem?

`vcluster connect` creates a _kubeconfig.yaml_ with a context named `Default`:

```
...
contexts:
- context:
    cluster: local
    namespace: default
    user: user
  name: Default
current-context: Default
...
```

I'd like to merge this with my existing _kubeconfig.yaml_ which already has a context named `default`

### Which solution do you suggest?

An option to specify the generated context name, eg:
```
vcluster connect vcluster-1 --kube-config ~/.kube/vcluster.yaml --kube-config-context-name my-awesome-vcluster
```

### Which alternative solutions exist?

Manually modifying the generated kubeconfig yaml
