### ISSUE TITLE
Unable to expose vcluster using steps in documentation

### ISSUE THREAD

**Issue by ramanNarasimhan77** [loft-sh/vcluster#54]
Hello,
I followed the steps mentioned in [External Access - Ingress](https://www.vcluster.com/docs/operator/external-access#ingress) documentation to access vcluster directly without port forwarding.

Latest release did not have some flags specified in the documentation, hence I built the vcluster cli from master and tried to use the same.

```
$ cat vcluster1/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: vcluster1-ingress
spec:
  rules:
  - host: vcluster1.<my-clyster-domain-redacted>
    http:
      paths:
      - backend:
          serviceName: vcluster1
          servicePort: 8443
        path: /

$ cat vcluster1/values.yaml
syncer:
  extraArgs:
  - --tls-san=vcluster1.<mycluster-domain-redacted>


$ kubectl apply -f vcluster1/ingress.yaml -n vcluster1
ingress.networking.k8s.io/vcluster1-ingress configured

$ vcluster create vcluster1 -n vcluster1 -f vcluster1/values.yaml
[info]   execute command: helm upgrade vcluster1 vcluster --repo https://charts.loft.sh --version 0.3.0-beta.4 --kubeconfig /tmp/346816742 --namespace vcluster1 --install --repository-config='' --values /tmp/431627021 --values vcluster1/values.yaml
[done] √ Successfully created virtual cluster vcluster1 in namespace vcluster1. Use 'vcluster connect vcluster1 --namespace vcluster1' to access the virtual cluster

```

Though the vcluster helm installation is done successfully by setting extraArgs in syncer, and the kubeconfig.yaml is also generated with the correct ingress hostname, kubectl is not able to connect to the vcluster due to TLS handshake timeout error as shown below

```
$ kubectl get ns -v9
I0620 09:38:44.333233 2175166 loader.go:379] Config loaded from file:  /home/myuser/kubeconfig.yaml
I0620 09:38:44.341869 2175166 round_trippers.go:425] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.20.5 (linux/amd64) kubernetes/6b1d87a" 'https://vcluster1.<redacted-my-cluster-domain>/api?timeout=32s'
I0620 09:38:54.349872 2175166 round_trippers.go:445] GET https://<redacted-my-cluster-domain>/api?timeout=32s  in 10007 milliseconds
I0620 09:38:54.349895 2175166 round_trippers.go:451] Response Headers:
I0620 09:38:54.349957 2175166 cached_discovery.go:121] skipped caching discovery info due to Get "https://vcluster1.<redacted-my-cluster-domain>/api?timeout=32s": net/http: TLS handshake timeout
```
 
I can see that the vcluster server accepts --tls-san [here](https://github.com/loft-sh/vcluster/blob/main/cmd/vcluster/main.go#L91) and also sets it while creating the proxy server [here](https://github.com/loft-sh/vcluster/blob/main/cmd/vcluster/main.go#L322)
The secret generated by vcluster is always having https://localhost:$port ( reference:[source code](https://github.com/loft-sh/vcluster/blob/main/cmd/vcluster/main.go#L384))

Right now everything looks good with port-forwarding option but we are looking into vcluster for running some automation scenarios, and direct access without port-forwarding would simplify things for us to a large extent.

Request some guidance to understand  what I am doing wrong, so that I can connect to the vcluster directly via kubectl.

**Comment by FabianKramm** [comment]
@ramanNarasimhan77 thanks for creating this issue! This was actually an error in the documentation, the service port of the ingress has to be `443` instead of `8443`:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: vcluster1-ingress
spec:
  rules:
  - host: vcluster1.<my-clyster-domain-redacted>
    http:
      paths:
      - backend:
          serviceName: vcluster1
          servicePort: 443
        path: /

$ cat vcluster1/values.yaml
syncer:
  extraArgs:
  - --tls-san=vcluster1.<mycluster-domain-redacted>
```

We corrected that and it should work now as expected.
