### ISSUE TITLE
Exemptions in isolated mode

### ISSUE THREAD

**Issue by rhtenhove** [loft-sh/vcluster#550]
### Is your feature request related to a problem?

Wanting to deploy a manifest which violates the vCluster isolated mode admission requirements. This can be anything, for example mounting a certain directory on the host.

This is possible with PodSecurity (see suggested solution). Sadly configuring this for the vCluster `kube-apiserver` doesn't have the desired effect as vCluster isolated mode handles this differently.

### Which solution do you suggest?

PodSecurity allows to specify users (and more) in an AdmissionConfiguration manifest for the `kube-apiserver`, which then allows manifests to be deployed as that user which will then not be checked for any violations.

For example:

```
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
  - name: PodSecurity
    configuration:
      apiVersion: pod-security.admission.config.k8s.io/v1beta1
      kind: PodSecurityConfiguration
      exemptions:
        usernames:
          - benchperson
```

Have this work for the vCluster `kube-apiserver` too (or use a similar implementation working for the vCluster syncer).

### Which alternative solutions exist?

None as far as I know. Unable to have violating manifests in an isolated vcluster.

### Additional context

[As discussed with Fabian Kramm and Oleg Matskiv on Slack](https://app.slack.com/client/TDSP6B7DY/C01N273CF4P/thread/C01N273CF4P-1655757490.859989)
