### ISSUE TITLE
Allow setting kubeconfig cluster name via the Syncer Flags directly

### ISSUE THREAD

**Issue by Blackmamba23** [loft-sh/vcluster#554]
### Is your feature request related to a problem?

No able to define the cluster name and context of the generated kubeconfig file directly with the Syncer flags. This is currently only possible with the cli via --kube-config-context-name

### Which solution do you suggest?

Add a Syncer flag to set the cluster name eg.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: secret-data-here
  name: local <- SET THIS DURING INSTALL WITH FLAG
contexts:
- context:
    cluster: local <- ET THIS DURING INSTALL WITH FLAG - should be same as above
    namespace: default
    user: user
  name: Default
current-context: Default
kind: Config
preferences: {}
users:
- name: user
  user:
    client-certificate-data: secret-data-here
    client-key-data: secret-data-her
```

### Which alternative solutions exist?

This is currently only possible with the cli via --kube-config-context-name but would be nice to set it directly with Syncer flags for when we are not using the vcluster cli
