### ISSUE TITLE
Can't run multiple etcd instances on EKS

### ISSUE THREAD

**Issue by dza89** [loft-sh/vcluster#589]
### What happened?

I can't run multiple etcd instances because the source ip is checked and is not configured in the certs for etcd.

`kubectl logs vcluster-etcd-0`

`rejected connection from "10.235.245.27:60200" (error "tls: \"10.235.245.27\" does not match any of DNSNames [\"localhost\" \"vcluster-api\" \"vcluster-etcd\" \"vcluster-etcd-0\" \"vcluster-etcd-0.vcluster-etcd-headless\" \"vcluster-etcd-0.vcluster-etcd-headless.serverfull\" \"vcluster-etcd.serverfull\" \"vcluster-etcd.serverfull.svc\"]", ServerName "vcluster-etcd-0.vcluster-etcd-headless.serverfull", IPAddresses ["0.0.0.0" "127.0.0.1" "::1"], DNSNames ["localhost" "vcluster-api" "vcluster-etcd" "vcluster-etcd-0" "vcluster-etcd-0.vcluster-etcd-headless" "vcluster-etcd-0.vcluster-etcd-headless.serverfull" "vcluster-etcd.serverfull" "vcluster-etcd.serverfull.svc"])`

`kubectl get pods -owide`

`vcluster-etcd-0                                     1/1     Running   0          13m   10.235.245.158   ip-10-235-244-121.eu-west-1.compute.internal   <none>           <none>
vcluster-etcd-1                                     0/1     Running   3          13m   10.235.245.47    ip-10-235-244-121.eu-west-1.compute.internal   <none>           <none>
vcluster-etcd-2                                     0/1     Running   3          13m   10.235.245.27    ip-10-235-244-121.eu-west-1.compute.internal   <none>           <none>`

There are numerous logs from this from both instances.

### What did you expect to happen?

Run etcd 3 times without issue

### How can we reproduce it (as minimally and precisely as possible)?

Run multiple instances of etcd on EKS, pretty much a default cluster.

### Host cluster Kubernetes version

<details>

```console
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.12-eks-a64ea69", GitCommit:"d4336843ba36120e9ed1491fddff5f2fec33eb77", GitTreeState:"clean", BuildDate:"2022-05-12T18:29:27Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS 1.21
```

</details>

### vlcuster version

<details>

```console
vcluster version 0.10.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
EKS
```

</details>
 

### OS and Arch

<details>

```
    architecture: arm64
    bootID: a68c9f08-d979-4ed9-a9e2-3cde084b6c9c
    containerRuntimeVersion: containerd://1.6.6+bottlerocket
    kernelVersion: 5.10.118
    kubeProxyVersion: v1.21.13
    kubeletVersion: v1.21.13
    machineID: ec2bf4579d87bbf143c2924283611718
    operatingSystem: linux
    osImage: Bottlerocket OS 1.8.0 (aws-k8s-1.21)
    systemUUID: ec2bf457-9d87-bbf1-43c2-924283611718
```
</details>

**Comment by FabianKramm** [comment]
@dza89 thanks for creating this issue! What values have you used to create the vcluster?

**Comment by dza89** [comment]
```
enableHA: true

etcd:
  replicas: 3

controller:
  replicas: 3

api:
  replicas: 3

coredns:
  replicas: 2

ingress:
  enabled: true
  host: vcluster.somehost
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'

syncer:
  extraArgs:
    - --tls-san=vcluster.somehost
 ```
