### ISSUE TITLE
Persistent Volume Reclaim Policy does not work

### ISSUE THREAD

**Issue by ddl-risong-na** [loft-sh/vcluster#600]
### What happened?

There are a few issues around persistent volumes. Here is what I did

 1. Create an EKS cluster
 2. Create ebs csi driver on the host cluster
 3. Create a vcluster and connect to it
 4. Create a storage class using ebs (The storage class can be on the host cluster or vcluster. I've tested both scenarios and the result is identical). The Reclaim Policy is `Retain`
 5. Create a PVC
 6. Create a POD
 7. The PV is created which is expected
 8. Delete the POD
 9. Delete the PVC
10. The PV is also deleted (issue1)
11. The volume on AWS is back to `Available` (issue2. If the PV is deleted, the volume should be deleted as well)

Scenario b, where I created storage class with Reclaim Policy `Delete`. Issue2 still happened - when the PV is deleted, the volume on AWS still exists

Scenario c, where I created storage class with Reclaim Policy `Delete`, after step 7
c8. Edit PV to change the Reclaim Policy to `Retain`
c9. The PV on the host cluster is still `Delete` (issue3)
c10. issue 1 and 2 also occurred

vcluster values.yaml (tested both `storageclasses` and `legacy-storageclasses`, same result)

```
serviceAccount:
  imagePullSecrets:
    - name: docker-secret
sync:
  nodes:
    enabled: true
    syncAllNodes: true
  persistentvolumes:
    enabled: true
  priorityclasses:
    enabled: true
  storageclasses:
    enabled: true
syncer:
  extraArgs: ["--override-hosts-container-image", "our-own-alpine"]
  resources:
    limits:
      memory: 15Gi
```

storage class yaml

```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: disk
parameters:
  encrypted: "true"
  type: gp3
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
```

a sample pvc json

```
{
  "kind": "PersistentVolumeClaim",
  "apiVersion": "v1",
  "metadata": {
    "name": "claim1"
  },
  "spec": {
    "storageClassName": "disk",
    "accessModes": [
      "ReadWriteOnce"
    ],
    "resources": {
      "requests": {
        "storage": "30Gi"
      }
    }
  }
}
```

a sample pod yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: claim1
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
```

### What did you expect to happen?

Issue1: when the Reclaim Policy is `Retain`, the PV should not be deleted when PVC is deleted
Issue2: when the PV is deleted, the volume on AWS should be deleted
Issue3: when I update the Reclaim Policy of a PV on the vcluster, the PV on the host cluster should be synced as well, and vice versa

I have verified that if I create everything (sc, pod, pvc) on the host cluster directly, issue 1 and 2 did not happen.

### How can we reproduce it (as minimally and precisely as possible)?

As mentioned in `What happened?`

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.14", GitCommit:"0fd2b5afdfe3134d6e1531365fdb37dd11f54d1c", GitTreeState:"clean", BuildDate:"2021-08-11T18:07:41Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
vcluster version 0.8.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```

</details>
