### ISSUE TITLE
users can break out of virtual cluster

### ISSUE THREAD

**Issue by protosam** [loft-sh/vcluster#63]
I've outlined in this gist here how to gain root access from a virtual cluster to the node that hosts the cluster that actually runs the pods: https://gist.github.com/protosam/a97d9c3db588d475fe686eb32280318a

This seems problematic for multi-tenancy.

**Comment by protosam** [comment]
After looking into policy options to patch this, I think using jspolcies to enforce rules to prevent this is fine. Closing this issue.

```yaml
apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: "deny-nesting-cluster-namespace.cluster.local"
spec:
  operations: ["CREATE", "UPDATE"]
  resources: ["pods"]
  scope: Namespaced
  javascript: |
    const containers = request.object.spec.containers || [];
    const initContainers = request.object.spec.initContainers || [];

    if (request.object.metadata.namespace === "nesting-cluster") {
      [...containers, ...initContainers].forEach(container => {
        if (container.securityContext.length !== 0) { //container.securityContext?.allowPrivilegeEscalation
          deny("setting spec.(initContainers|containers)[*].securityContext is not permitted")
        }
      })
    }
```
