### ISSUE TITLE
High Availability K8S Rootless mode

### ISSUE THREAD

**Issue by iMikeG6** [loft-sh/vcluster#674]
Hello,

First thing first, let me thank you for this amazing tool you guys created, it is exactly what we were looking for.
I'd like to contribute too. I know it is not officially supported but it was a requirement for us to run a high available vcluster in rootless mode. I dug into it and found some part here and there but couldn't found a real documentation that explain howto make it possible.

Below, you'll find a k8s-ha-values.yml file that can be used to create a fully functional vcluster highly available in rootless mode:

```
# DefaultImageRegistry will be prepended to all deployed vcluster images, such as the vcluster pod, coredns etc.. Deployed
# images within the vcluster will not be rewritten.
defaultImageRegistry: ""

# Scale up syncer replicas
syncer:
  # image: loftsh/vcluster
  replicas: 3
  extraArgs:
  - --tls-san=vc3.domain.ch # External cluster IP or Ingress fqdn
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 12345
    runAsNonRoot: true
    runAsUser: 12345
    seccompProfile:
      type: RuntimeDefault

# Enable HA mode
enableHA: true

# Scale up etcd
etcd:
  # image: k8s.gcr.io/etcd:3.5.1-0
  replicas: 3
  fsGroup: 12345
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 12345
    runAsNonRoot: true
    runAsUser: 12345
    seccompProfile:
      type: RuntimeDefault

# Scale up controller manager
controller:
  # image: k8s.gcr.io/kube-controller-manager:v1.24.1
  replicas: 3
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 12345
    runAsNonRoot: true
    runAsUser: 12345
    seccompProfile:
      type: RuntimeDefault

# Scale up api server
api:
  # image: k8s.gcr.io/kube-apiserver:v1.24.1
  replicas: 3
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      add:
      - NET_BIND_SERVICE
    readOnlyRootFilesystem: true
    runAsGroup: 12345
    runAsNonRoot: true
    runAsUser: 12345
    fsGroup: 12345
    seccompProfile:
      type: RuntimeDefault

# Scale up DNS server
coredns:
  # image: my-core-dns-image:latest
  replicas: 3
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 12345
    runAsNonRoot: true
    runAsUser: 12345
    seccompProfile:
      type: RuntimeDefault

scheduler:
  # image: k8s.gcr.io/kube-scheduler:v1.24.1
  # The amount of replicas to run the deployment with
  replicas: 3
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsGroup: 12345
    runAsNonRoot: true
    runAsUser: 12345
    seccompProfile:
      type: RuntimeDefault

# Plugins that should get loaded. Usually you want to apply those via 'vcluster create ... -f https://.../plugin.yaml'
plugin: {}

# Resource syncers that should be enabled/disabled.
# Enabling syncers will impact RBAC Role and ClusterRole permissions.
# To disable a syncer set "enabled: false".
# See docs for details - https://www.vcluster.com/docs/architecture/synced-resources
sync:
  services:
    enabled: true
  configmaps:
    enabled: true
  secrets:
    enabled: true
  endpoints:
    enabled: true
  pods:
    enabled: true
    ephemeralContainers: false
    status: false
  events:
    enabled: true
  persistentvolumeclaims:
    enabled: true
  ingresses:
    enabled: true
  fake-nodes:
    enabled: true # will be ignored if nodes.enabled = true
  fake-persistentvolumes:
    enabled: false # will be ignored if persistentvolumes.enabled = true
  nodes:
    enabled: false
    # If nodes sync is enabled, and syncAllNodes = true, the virtual cluster 
    # will sync all nodes instead of only the ones where some pods are running.
    syncAllNodes: false
    # nodeSelector is used to limit which nodes get synced to the vcluster,
    # and which nodes are used to run vcluster pods.
    # A valid string representation of a label selector must be used. 
    nodeSelector: ""
    # if true, vcluster will run with a scheduler and node changes are possible
    # from within the virtual cluster. This is useful if you would like to
    # taint, drain and label nodes from within the virtual cluster
    enableScheduler: false
    # DEPRECATED: use enable scheduler instead
    # syncNodeChanges allows vcluster user edits of the nodes to be synced down to the host nodes.
    # Write permissions on node resource will be given to the vcluster.
    syncNodeChanges: false
  persistentvolumes:
    enabled: false
  storageclasses:
    enabled: false
  legacy-storageclasses:
    enabled: false
  priorityclasses:
    enabled: false
  networkpolicies:
    enabled: false
  volumesnapshots:
    enabled: false
  poddisruptionbudgets:
    enabled: false
  serviceaccounts:
    enabled: false

# Configure the ingress resource that allows you to access the vcluster
ingress:
  # Enable ingress record generation
  enabled: true
  # Ingress path type
  pathType: ImplementationSpecific
  apiVersion: networking.k8s.io/v1
  ingressClassName: "nginx"
  host: vc3.domain.ch
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    #nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

securityContext:
  runAsUser: 12345
  runAsGroup: 12345
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

For those of you who are running Rancher, you'll probably have to tweak the PSP that apply to your containers by adding the following annotation below to avoid message like `seccomp.security.alpha.kubernetes.io/etcd]: Forbidden: seccomp may not be set`

```
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
```

Same for error `securityContext.capabilities.add: Invalid value: "NET_BIND_SERVICE": capability may not be added`, set the psp to allow capability `NET_BIND_SERVICE`.

Even though it's fully functional, this is still not officially supported, and things could change has the project goes on.
And the provided values file may contain errors, so if so, please share and comment :-)

Hope it helps.

Again, huge thanks to the lôft team for offering this amazing tools to the community, for free.

**Comment by FabianKramm** [comment]
@iMikeG6 thanks for creating this issue and the guide! So essentially you want us to use your example in the docs to make it easier for others to use HA with k8s and rootless mode? Or is there a problem with your configuration still?

**Comment by iMikeG6** [comment]
Hi @FabianKramm, thanks for your reply.

Indeed, not an issue, just a guide for those who'd like to use K8S vcluster in HA and rootless mode.

**Comment by FabianKramm** [comment]
Ah great, yes thanks we can add that to our documentation!

**Comment by iMikeG6** [comment]
That'll be great.

Just hope I configured it correctly.

**Comment by iMikeG6** [comment]
Just deployed a new vcluster with the config I provided and noticed that `#fsGroup: 12345` does not apply to the api server config values.

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "fsGroup" in io.k8s.api.core.v1.SecurityContext
```

Commented it and its good.


```
# Scale up api server
api:
  # image: k8s.gcr.io/kube-apiserver:v1.24.1
  replicas: 3
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
      add:
      - NET_BIND_SERVICE
    readOnlyRootFilesystem: true
    runAsGroup: 12345
    runAsNonRoot: true
    runAsUser: 12345
    #fsGroup: 12345
    seccompProfile:
      type: RuntimeDefault
```
