### ISSUE TITLE
Integrating VCluster with Clusterpedia

### ISSUE THREAD

**Issue by Iceber** [loft-sh/vcluster#739]
### Is your feature request related to a problem?

Using [Clusterpedia](https://github.com/clusterpedia-io/clusterpedia) to help view and retrieve resources within all virtual clusters looks very interesting.

### Which solution do you suggest?

I've been researching and using VCluster lately and I found it looks very interesting to use VCluster in combination with Clusterpedia.

[Clusterpedia](https://github.com/clusterpedia-io/clusterpedia) is a sandbox project for cross-cluster resource retrieval that can be integrated with most Kubernetes-based multi-cluster management platforms.
[https://github.com/clusterpedia-io/clusterpedia](https://github.com/clusterpedia-io/clusterpedia)

Even though VCluster is not a multi-cloud platform, Clusterpedia still automatically discovers virtual clusters within the host cluster.
The virtual clusters created by users can immediately use kubectl to retrieve resources within those clusters, without requiring additional operations on Clusterpedia.

```
$ vcluster list
 NAME              NAMESPACE         STATUS    CONNECTED   CREATED                         AGE
 caiwei-vcluster   caiwei-vcluster   Running               2022-08-26 16:10:52 +0800 CST   484h49m6s
 vcluster-1        default           Running               2022-09-15 20:57:59 +0800 CST   1m59s
 vcluster-2        default           Running               2022-09-15 20:59:34 +0800 CST   24s

$ kubectl --cluster clusterpedia get po -A
NAMESPACE     CLUSTER                              NAME                       READY   STATUS    RESTARTS   AGE
default       vc-caiwei-vcluster-caiwei-vcluster   backend-77f8f45fc8-5ssww   1/1     Running   0          20d
default       vc-caiwei-vcluster-caiwei-vcluster   backend-77f8f45fc8-j5m4c   1/1     Running   0          20d
default       vc-caiwei-vcluster-caiwei-vcluster   backend-77f8f45fc8-vjzf6   1/1     Running   0          20d
kube-system   vc-default-vcluster-1                coredns-669fb9997d-cxktv   1/1     Running   0          3m40s
kube-system   vc-default-vcluster-2                coredns-669fb9997d-g7w8l   1/1     Running   0          2m6s
kube-system   vc-caiwei-vcluster-caiwei-vcluster   coredns-669fb9997d-x6vc2   1/1     Running   0          20d

$ kubectl --cluster clusterpedia get ns
CLUSTER                              NAME              STATUS   AGE
vc-default-vcluster-2                default           Active   2m49s
vc-default-vcluster-1                default           Active   4m24s
vc-caiwei-vcluster-caiwei-vcluster   default           Active   20d
vc-default-vcluster-2                kube-node-lease   Active   2m49s
vc-default-vcluster-1                kube-node-lease   Active   4m24s
vc-caiwei-vcluster-caiwei-vcluster   kube-node-lease   Active   20d
vc-default-vcluster-2                kube-public       Active   2m49s
vc-default-vcluster-1                kube-public       Active   4m24s
vc-caiwei-vcluster-caiwei-vcluster   kube-public       Active   20d
vc-default-vcluster-2                kube-system       Active   2m49s
vc-default-vcluster-1                kube-system       Active   4m24s
vc-caiwei-vcluster-caiwei-vcluster   kube-system       Active   20d
```

**Clusterpedia can support Kubernetes v1.10+ clusters, with very** [**complex search conditions**](https://github.com/clusterpedia-io/clusterpedia#search-label-and-url-query)

```
$ kubectl --cluster clusterpedia get deployments -A -l "search.clusterpedia.io/clusters in (cluster-1, cluster-2),\
    search.clusterpedia.io/namespaces in (kube-system,default),\
    search.clusterpedia.io/orderby=name"
```

Clusterpedia has added [integration documentation for VCluster](https://clusterpedia.io/docs/usage/interfacing-to-multi-cloud-platforms/#vcluster-clusterimportpolicy), and the combination of Clusterpedia and VCluster allows administrators or users to retrieve resources across multiple virtual clusters with little additional effort from VCluster, which I find very interesting!

**I'd like to see if there are more scenarios where Clusterpedia can help VCluster, or add documentation for Clusterpedia& VCluster to the VCluster documentation to provide some ideas for people who need them**

### Which alternative solutions exist?

*No response*

### Additional context

*No response*

**Comment by FabianKramm** [comment]
@Iceber thanks for creating this issue! Great to see an integration for vcluster in Clusterpedia! I'm not too familiar with Clusterpedia, but would you need to install an operator / workload into the virtual cluster for Clusterpedia to recognize it or does it detect and rewrite the vcluster pods automatically?

**Comment by Iceber** [comment]
clusterpedia is used to view and retrieve resources from multiple clusters, synchronizing them through the vcluster apiserver without installing any components in the vcluster. clusterpedia will get the kubeconfig of the vcluster apiserver through the `vc-<vcluster name>` secret.


This file that automatically discovers the vcluster and converts it into clusterpedia's own cluster configuration resources —— [PediaCluster](https://clusterpedia.io/docs/concepts/pediacluster/)
```yaml
apiVersion: policy.clusterpedia.io/v1alpha1
kind: ClusterImportPolicy
metadata:
  name: vcluster
spec:
  source:
    group: ""
    resource: secrets
    selectorTemplate: |
      {{ if hasPrefix "vc-" .source.metadata.name }}
        {{ $ca := (get .source.data "certificate-authority") }}
        {{ $clientca := (get .source.data "client-certificate") }}
        {{ $clientkey := (get .source.data "client-key") }}
        {{/* Use a specific data format tofilter out the vcluster's secret */}}
        {{ if and $ca $clientca $clientkey (hasKey .source.data "config") }}
          {{ $kubeconfig := (b64dec .source.data.config) }}
          {{ and
            (contains $ca $kubeconfig)
            (contains $clientca $kubeconfig)
            (contains $clientkey $kubeconfig)
           }}
        {{ end }}
      {{ end }}
  nameTemplate: 'vc-{{ .source.metadata.namespace }}-{{ trimPrefix "vc-" .source.metadata.name }}'
  template: |
    spec:
      apiserver: 'https://{{ trimPrefix "vc-" .source.metadata.name }}.{{ .source.metadata.namespace }}.svc'
      kubeconfig: '{{ .source.data.config }}'
      syncResources:
        - group: ""
          resources:
          - "pods"
          - "services"
          - "configmaps"
          - "secrets"
          - "namespaces"
        - group: "apps"
          resources:
            - "*"
      syncResourcesRefName: ""
  creationCondition: "true"
```
