### ISSUE TITLE
helm init manifests conflict with same chart name

### ISSUE THREAD

**Issue by FabianKramm** [loft-sh/vcluster#744]
Currently we have a problem that when specifying multiple init charts with the same chart name but a different repo url, vcluster will deploy the same chart twice instead of deploying both charts.

E.g.:
```
init:
  helm:
    - chart:
        name: postgresql
        repo: https://charts.bitnami.com/bitnami
      release:
        name: postgresql
        namespace: postgresql
    - chart:
        name: postgresql
        repo: https://cetic.github.io/helm-charts
      release:
        name: postgresql
        namespace: postgresql-2
```
