### ISSUE TITLE
vcluster create support --image-repository like minikube

### ISSUE THREAD

**Issue by bitpeng** [loft-sh/vcluster#784]
### Is your feature request related to a problem?

Some users could not pull images from grc.io, and they must execute `kubectl edit pod` to change image manually.

### Which solution do you suggest?

Cloud vcluster support alternative image repository to pull docker images from. This can be used when you have limited access to gcr.io. 

### Which alternative solutions exist?

Reccommand to support `--image-repository` option like minikube. For Chinese mainland users, they may use local gcr.io mirrors such as registry.cn-hangzhou.aliyuncs.com/google_containers

**Comment by matskiv** [comment]
I don't know if we will add a CLI option for this, but there is an existing way to achieve this already.
If you are talking about the images used by vcluster itself, then you can create a `values.yaml` file with this content:
```
defaultImageRegistry: your.registry.here
coredns:
  image: your.registry.here/coredns/coredns:1.9.3
syncer:
  extraArgs:
    - "override-hosts-container-image=your.registry.here/library/alpine:3.13.1"
```
And then use it when creating the cluster - `vcluster create vname -f values.yaml`.
The `your.registry.here` should contain `loftsh/vcluster` images AND rancher/k3s, or k0sproject/k0s image, etc.
To pick coredns version you can refer to [this list](https://github.com/loft-sh/vcluster/blob/eba499bcdff242e4ca73c9450020f9fb4ab9afa7/pkg/constants/coredns.go#L3).

And if you mean the images of workloads deployed inside the vcluster, then you can set this in your values.yaml to pick a default registry for workloads(applies to vcluster coredns as well):
```
syncer:
  extraArgs:
    - "--default-image-registry=your.registry.here"
```
or this to provide overrides for the full image path:
```
syncer:
  extraArgs:
    - "--translate-image=coredns/coredns=mirror.io/other-org/coredns"
```
