### ISSUE TITLE
Feature request: init manifests that would be applied after charts

### ISSUE THREAD

**Issue by matskiv** [loft-sh/vcluster#834]
### Is your feature request related to a problem?

The "[init manifests](https://www.vcluster.com/docs/operator/init-manifests#applying-manifests-on-initialization)" are applied by the vcluster before [applying charts](https://www.vcluster.com/docs/operator/init-manifests#applying-charts-on-vcluster-initialization). I can foresee use cases where this is desired, but also use cases where a manifest needs to be applied after the charts, or different manifests before and after. For example, an operator with CRDs is installed via a helm chart, and operands that use the CRDs can only be installed afterward.

I create this issue to gather interest in adding such a feature. Please upvote and we will consider it for one of the future releases.

### Which solution do you suggest?

Add an additional helm chart option to specify manifests that will be applied after helm charts.

### Which alternative solutions exist?

Alternative - a helm chart can be created from a manifest and added as the last item in the list of init helm charts.

### Additional context

*No response*

**Comment by luvres** [comment]
Would it be feasible to include a valueFiles option for helm and manifests?
Example:

```
helm:
  valueFiles:
   - https://raw.githubusercontent.com/values.yaml
  ...

manifests:
  valueFiles:
   - https://raw.githubusercontent.com/values.yaml
  ...
```

**Comment by luvres** [comment]
Maybe it fits in another issue, but the declaration of values at level doesn't seem to work:
```
values: |-
    proxy:
        http:
            nodePort: 30081
```

**Comment by matskiv** [comment]
> Would it be feasible to include a valueFiles option for helm and manifests?

@luvres That is out of scope for this particular issue. But feel free to open a new feature request issue if you feel strongly about this :) 

-----
> Maybe it fits in another issue, but the declaration of values at level doesn't seem to work:
> 
> values: |-
>   proxy:
>     http:
>       nodePort: 30081

The values field is always a sub-field of a particular chart, and its content needs to be indented correctly. Please create a separate issue if this doesn't work. Example:
```
init:
  helm:
    - values: |-
        myValue: true
      chart: ...
```
