### ISSUE TITLE
When I apply a manifest dependent on the installation of the helm, no one is installed.

### ISSUE THREAD

**Issue by luvres** [loft-sh/vcluster#840]
### Is your feature request related to a problem?

When I apply a manifest dependent on the installation of the helm, no one is installed.

### Which solution do you suggest?
```
init:
   helm:
   - chart:
       name: cert-manager
       repo: https://charts.jetstack.io
       ...

   manifests: |-
     apiVersion: cert-manager.io/v1
     kind: ClusterIssuer
     ...
```
I think of something like:
```
   manifests: |-
       apiVersion: cert-manager.io/v1
       kind: ClusterIssuer
       ...
       depends: helm
```
