### ISSUE TITLE
securityContext not properly synced in StatefulSet workload

### ISSUE THREAD

**Issue by iMikeG6** [loft-sh/vcluster#846]
### What happened?

When you enable PSA on the host cluster with the following:

```yaml
pod-security.kubernetes.io/enforce: restricted
pod-security.kubernetes.io/enforce-version: v1.23
```

spin up a rootless k8s vcluster. 
Below, the sync parameters used in the helm values file:

```yaml
sync:
  services:
    enabled: true
  configmaps:
    enabled: true
  secrets:
    enabled: true
  endpoints:
    enabled: true
  pods:
    enabled: true
    ephemeralContainers: false
    status: false
  events:
    enabled: true
  persistentvolumeclaims:
    enabled: true
  ingresses:
    enabled: true
  fake-nodes:
    enabled: false
  fake-persistentvolumes:
    enabled: false
  nodes:
    enabled: true
    syncAllNodes: true
    nodeSelector: "node-role.kubernetes.io/worker=true"
    enableScheduler: false
    syncNodeChanges: false
  persistentvolumes:
    enabled: false
  storageclasses:
    enabled: false
  hoststorageclasses:
    enabled: false
  priorityclasses:
    enabled: false
  networkpolicies:
    enabled: true
  volumesnapshots:
    enabled: false
  poddisruptionbudgets:
    enabled: true
  serviceaccounts:
    enabled: false
```

Then creating a StatefulSet with the following:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 3
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
```

The pod is not scheduled and those not even reach the host cluster.

The error is the following:

```
Error syncing to physical cluster: pods "web-0-x-default-x-myvcluster" is forbidden: violates PodSecurity "restricted:v1.23": allowPrivilegeEscalation != false (container "vcluster-rewrite-hosts" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "vcluster-rewrite-hosts" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "vcluster-rewrite-hosts" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

If you use the same StatefulSet yaml file and you directly applying it on the host cluster within the namespace were you enable the PSA, it run just fine without any issues.

To me, it's seems like a bug in the vcluster syncer with the StatefulSet workloads.

On the vcluster itself, you can switch the kind to `Deployment` and the pod get properly scheduled.

### What did you expect to happen?

Pods should be scheduled as it is with Deployment without returning the error mentioned above.

### How can we reproduce it (as minimally and precisely as possible)?

See above.

### Anything else we need to know?

I'm using Kyverno 1.8.2 with no policies installed.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.25) and server (1.23) exceeds the supported minor version skew of +/-1
```

</details>

### Host cluster Kubernetes distribution

<details>

```
RKE1, K8S 1.23.7 Deployed with rancher
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here

vcluster version 0.13.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
K8S HA Rootless

Syncer version: 0.13.0
Vcluster kube api version: 1.23.7
```

</details>

### OS and Arch

<details>

```
OS:  RHEL 9.1 (Plow)
Arch: AMD64
```
</details>
