### ISSUE TITLE
SSL bypass for ingress that already does SSL termination

### ISSUE THREAD

**Issue by stevefan1999-personal** [loft-sh/vcluster#890]
### Is your feature request related to a problem?

I have my own Cloudflare setup with external-dns so that it will automatically synchronize ingress resources to match my DNS records. However, as I do have Cloudflare auto SSL enabled but Kubernetes API server runs in mTLS. Insecure connection means your client is read-only due to the server side not being able to verify who you are.

I just realized that I'm effectively blocked from accessing the cluster that way using my ingress server without having to expose my host IP to the public. I ran in a home network.

And in a cloud situation, I can't afford to have cloud load balancers for every exposed API service either.

For some reason I used to spawn Rancher with ingress that works with Cloudflare automatic SSL proxy. Not sure what kind of magic it is doing but I think investigating how they did it is a good starting point

### Which solution do you suggest?

Find a way to transparently bypass the mTLS.

### Which alternative solutions exist?

Using a NodePort based setback.

### Additional context

In fact, this problem extends to all other SSL terminating reverse proxy as well. I was helping my company to deploy vclusters but we are protected behind a IIS central server as a reverse proxy with automatic SSL termination and I faced the same problem.

We have to address this.

**Comment by stevefan1999-personal** [comment]
Related: https://github.com/loft-sh/vcluster/issues/144#issuecomment-938900546

**Comment by stevefan1999-personal** [comment]
Seems like we can try to do a service account login. I believe this is the trick why Rancher can access the cluster. They should have also had insecure server cert validation, but then instead presented a valid access token that the API server can validate. If the theory is right, then the following YAML documents would help you create such service account, and store the information under a secret:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcluster-admin
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: vcluster-admin-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: vcluster-admin
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vcluster-admin-access-all
subjects:
- kind: ServiceAccount
  name: vcluster-admin
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```
I use manual secret because the [automatic generation of token secrets is deprecated in 1.24](https://stackoverflow.com/a/72258300/3289081).

Then use [kubectl view-serviceaccount-kubeconfig](https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin) to get a context:
```
vcluster connect my-demo -n vcluster-my-demo -- kubectl view-serviceaccount-kubeconfig vcluster-admin -n kube-system
```
