### ISSUE TITLE
Allow Mapping Services Feature to Work With Headless Services

### ISSUE THREAD

**Issue by sharkymcdongles** [loft-sh/vcluster#901]
Headless svc not working as expected when mapping with the `mapServices.fromVirtual....` option

Details in - [https://github.com/loft-sh/vcluster/issues/901](https://github.com/loft-sh/vcluster/issues/901)

This is extended for headless services not mapping from host → virtual

**Comment by ishankhare07** [comment]
Hi @sharkymcdongles , thanks for creating this issue. From my initial skim through the code, what seems to be the case here is the service is created but the `service.spec.type` is not taken into account. Is it what you're seeing in your case as well?

**Comment by sharkymcdongles** [comment]
> Hi @sharkymcdongles , thanks for creating this issue. From my initial skim through the code, what seems to be the case here is the service is created but the `service.spec.type` is not taken into account – hence the `headless` part not working as expected. Is it what you're seeing in your case as well?

Yes, this seems to be the case. Also, a headless service is created if ClusterIP is set to None. We were able to create a workaround by customising the CoreDNS settings but in general it would be cleaner if the map services feature worked.

**Comment by sharkymcdongles** [comment]
@ishankhare07 this works as expected when I am mapping from vcluster to host, but if I try and map from host to vcluster then it doesn't seem to work. I checked the code, and it seems like it uses the same method even if it is to host to virtual or vice versa. Any idea?

Here is what I see in the vcluster:
```
Name:              mongodb-headless
Namespace:         default
Labels:            vcluster.loft.sh/controlled-by=vcluster
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  RequireDualStack
IP Families:       IPv4,IPv6
IP:                None
IPs:               None
Port:              mongodb  27017/TCP
TargetPort:        mongodb/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

**Comment by ishankhare07** [comment]
alright, I can see the `selectors` field to be empty first of all

**Comment by SCLogo** [comment]
Our use case would be to link a DB e.g Mongo from vcluster A to app in vcluster B using headless svc-s.

**Comment by sharkymcdongles** [comment]
@ishankhare07 Here are more details. First, using your change allowed headless services to work from vcluster to host cluster and work as expected.

headless service within the vcluster:
```
Name:              mongodb-headless
Namespace:         default
Labels:            app.kubernetes.io/component=mongodb
                   app.kubernetes.io/instance=mongodb
                   app.kubernetes.io/managed-by=Helm
                   app.kubernetes.io/name=mongodb
                   helm.sh/chart=mongodb-13.6.6
Annotations:       meta.helm.sh/release-name: mongodb
                   meta.helm.sh/release-namespace: default
Selector:          app.kubernetes.io/component=mongodb,app.kubernetes.io/instance=mongodb,app.kubernetes.io/name=mongodb
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                None
IPs:               None
Port:              mongodb  27017/TCP
TargetPort:        mongodb/TCP
Endpoints:         10.114.11.25:27017,10.114.3.8:27017,10.114.7.9:27017
Session Affinity:  None
Events:            <none>
```

Headless service mapped from vcluster to host cluster:
```
Name:              infrastructure-mongodb-headless
Namespace:         loft-default-v-my-vcluster
Labels:            vcluster.loft.sh/controlled-by=vcluster
Annotations:       cloud.google.com/neg: {"ingress":true}
Selector:          vcluster.loft.sh/label-my-vcluster-x-71dafa318e=mongodb,vcluster.loft.sh/label-my-vcluster-x-9039c53507=mongodb,vcluster.loft.sh/label-my-vcluster-x-b71e98ce1a=mongodb,vcluster.loft.sh/managed-by=my-vcluster,vcluster.loft.sh/namespace=default
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                None
IPs:               None
Port:              mongodb  27017/TCP
TargetPort:        mongodb/TCP
Endpoints:         10.114.11.25:27017,10.114.3.8:27017,10.114.7.9:27017
Session Affinity:  None
Events:            <none>
```

Helm values for this vcluster:
```
globalAnnotations:
  iam.gke.io/gcp-service-account: sa@sa.iam.gserviceaccount.com
hostpathMapper:
  enabled: true
mapServices:
  fromVirtual:
  - from: default/mongodb-headless
    to: infrastructure-mongodb-headless
nodeSelector:
  persistent: "true"
serviceCIDR: 10.115.0.0/16
storage:
  className: fast
  persistence: true
  size: 256Gi
sync:
  ingresses:
    enabled: false
  nodes:
    enabled: true
    syncAllNodes: true
  persistentvolumeclaims:
    enabled: true
  persistentvolumes:
    enabled: true
  priorityclasses:
    enabled: true
  storageclasses:
    enabled: true
syncer:
  image: harborrepo.com/library/vcluster:test
  resources:
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 2000m
      memory: 2Gi
vcluster:
  image: rancher/k3s:v1.24.7-k3s1
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 2Gi
```

helm values for mapping from host to vcluster
```
hostpathMapper:
  enabled: true
globalAnnotations:
  iam.gke.io/gcp-service-account: sa@sa.iam.gserviceaccount.com
nodeSelector:
  persistent: "true"
mapServices:
  fromHost:
  - from: loft-default-v-my-vcluster/infrastructure-mongodb-headless
    to: default/mongodb-headless
vcluster:
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 2Gi
storage:
  persistence: true
  size: 256Gi
  className: fast
syncer:
  resources:
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 2000m
      memory: 2Gi
sync:
  nodes:
    enabled: true
    syncAllNodes: true
  ingresses:
    enabled: false
  persistentvolumes:
    enabled: true
  persistentvolumeclaims:
    enabled: true
  priorityclasses:
    enabled: true
  storageclasses:
    enabled: true
```

service in vcluster:
```
Name:              mongodb-headless
Namespace:         default
Labels:            vcluster.loft.sh/controlled-by=vcluster
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  RequireDualStack
IP Families:       IPv4,IPv6
IP:                None
IPs:               None
Port:              mongodb  27017/TCP
TargetPort:        mongodb/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

service on host:
I don't see one on the host for this at all

I also tried another with the test image using your change:

service in vcluster:
```
Name:              mongodb-headless
Namespace:         default
Labels:            vcluster.loft.sh/controlled-by=vcluster
Annotations:       <none>
Selector:          <none>
Type:              ClusterIP
IP Family Policy:  RequireDualStack
IP Families:       IPv4,IPv6
IP:                None
IPs:               None
Port:              mongodb  27017/TCP
TargetPort:        mongodb/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

No service on host. Here are the values:
```
globalAnnotations:
  iam.gke.io/gcp-service-account: sa@sa.iam.gserviceaccount.com
hostpathMapper:
  enabled: true
mapServices:
  fromHost:
  - from: loft-default-v-my-vcluster/infrastructure-mongodb-headless
    to: default/mongodb-headless
nodeSelector:
  persistent: "true"
serviceCIDR: 10.115.0.0/16
storage:
  className: fast
  persistence: true
  size: 256Gi
sync:
  ingresses:
    enabled: false
  nodes:
    enabled: true
    syncAllNodes: true
  persistentvolumeclaims:
    enabled: true
  persistentvolumes:
    enabled: true
  priorityclasses:
    enabled: true
  storageclasses:
    enabled: true
syncer:
  image: harborrepo.com/library/vcluster:test
  resources:
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      cpu: 2000m
      memory: 2Gi
vcluster:
  image: rancher/k3s:v1.24.7-k3s1
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 2Gi
```
