### ISSUE TITLE
K8S vcluster:0.14.0-beta.0 CrashLoopBackoff

### ISSUE THREAD

**Issue by iMikeG6** [loft-sh/vcluster#908]
### What happened?

Hello there,

I'm testing the vcluster version 0.14.0-beta.0 to see if the problem reported here (#846) was fixed.
StatefulSet app are now schedulable which is great, though, it somehow, introduce a new bug. The `syncer` app is crashing. I don't know if its related or not.

### What did you expect to happen?

`syncer` should not crash while it's started

I know it's still inn beta and such bug are expected, though, I'm trying to help testing the new version before it get released.

### How can we reproduce it (as minimally and precisely as possible)?

Start vcluster with the following vcluster helm values: [https://gist.github.com/iMikeG6/5e08e9baf52728efd3a56b813411d0f8](https://gist.github.com/iMikeG6/5e08e9baf52728efd3a56b813411d0f8)

Wait few minutes then see syncer pod crashing

### Anything else we need to know?

Here's the syner pod logs: [https://gist.github.com/iMikeG6/76197b22718e3d3332bf1cda0e9327de](https://gist.github.com/iMikeG6/76197b22718e3d3332bf1cda0e9327de)

### Host cluster Kubernetes version

<details>

```
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8", GitCommit:"fdc77503e954d1ee641c0e350481f7528e8d068b", GitTreeState:"clean", BuildDate:"2022-11-09T13:31:40Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.24) exceeds the supported minor version skew of +/-1
```

</details>

### Host cluster Kubernetes distribution

<details>

```
RKE1, K8S 1.24.8 Deployed with rancher
```

</details>

### vlcuster version

<details>

```
$ vcluster --version
vcluster version 0.11.1
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS:  RHEL 9.1 (Plow)
Arch: AMD64
```

</details>

**Comment by ishankhare07** [comment]
Hey @iMikeG6 , thanks for creating this issue. I see based on the logs that the syncer errors out with `error parsing the config unsupported configuration version`. This is because of the recent addition of the `genericCRD syncer` becoming a core part of vcluster. But since you're not using this feature in your vcluster creation configuration, this has to be set as empty yaml document `---`.

This is actually handled by the new default values in the chart - ref: [charts/k3s/values.yaml](https://github.com/loft-sh/vcluster/blob/v0.14.0-beta.0/charts/k3s/values.yaml#L92-L94)

I can verify being able to create a new vcluster (`0.14.0-beta.0`) with the following set of values
```
sync:
  services:
    enabled: true
  configmaps:
    enabled: true
  secrets:
    enabled: true
  endpoints:
    enabled: true
  pods:
    enabled: true
    ephemeralContainers: false
    status: false
  events:
    enabled: true
  persistentvolumeclaims:
    enabled: true
  ingresses:
    enabled: true
  fake-nodes:
    enabled: false
  fake-persistentvolumes:
    enabled: false
  nodes:
    enabled: true
    syncAllNodes: true
    nodeSelector: "node-role.kubernetes.io/worker=true"
    enableScheduler: false
    syncNodeChanges: false
  persistentvolumes:
    enabled: false
  storageclasses:
    enabled: false
  hoststorageclasses:
    enabled: false
  priorityclasses:
    enabled: false
  networkpolicies:
    enabled: true
  volumesnapshots:
    enabled: false
  poddisruptionbudgets:
    enabled: true
  serviceaccounts:
    enabled: false
```
```
./vcluster-0.14.0-beta.0 create test-vcluster -f test.yaml
```

Can you post the exact command that you ran in order to created this vcluster?
